apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: forecast-solar-credentials
  namespace: lares-diagnostics-engine

spec:
  encryptedData:
    api-key: AgCTX4o+XQZk6n4OOU9objMs9+R/kaG0BZpi0Secvw1yvPLmmrXu2L6taCT9SwDFgnILVjgyDsYHc4ieVkMahNsyS28J58aJptTkEIXirUgaDeO1MNrG109CBKCzZ0QOeSrAcWOAchpSyAlRra+6Nx9fX4yYBhyA1JZrLun6hpww07asSj5jfm1up/4GXXprvvsu16n3wcGqWQI0rWb18vtDlbunf5hPfSb3hEd5t3EDXwiGRLMhWpfemuo2eVdhmzMOJqZY1ZsYGJqLtbDXqDki3cmSQ7ipzrrBl8I0qo7Awg06AJZdZspK3BiySieRj05L47DFLGPaQ4t6COTwuZ5WZFFDlSxyjAF8syTITKQgI+Fp6AgaTRlO87qvkRsgSIL7Bik4D/2yE7kwXqNXapwO8loKIBwml1K7hDXWRRlrKOnEcWLapnCp1XdjIorOrVZOOOJBrgqiCDT1GZ8aCCIR6EZop7ngJ9IVCuxNwfFZ2hdImrpcYc5Rn1RmXpSJ5R0EgKLIaJ9jN0EKX2t45Rt0f5/Un4vAtR5yLq5+bYHkcsR44fD/d30d40u7n+bxMwGooJQGzslOmw0xImdypI0t2Q9sz7ZYnBUXGsqUMSapP2YkvDBzfgRBiOEwj8P3YpiwHjoCcQfyhtcGZDT5qHPkLU8xpsRxr45hZ1uUItwm8wDcqDZ3BegLtiAxHXClvkF7cHOTlC1rXaYctDqZ5Hdu
  template:
    metadata:
      name: forecast-solar-credentials
      namespace: lares-diagnostics-engine
    type: Opaque
