apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudnative-pg

helmCharts:
  - name: plugin-barman-cloud
    repo: oci://ghcr.io/cloudnative-pg/charts
    releaseName: barman-cloud-plugin
    version: 0.7.1
    namespace: cloudnative-pg

labels:
  - includeSelectors: false
    pairs:
      homelab.app: cloudnative-pg

commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"
