apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - unifi_events.yaml
  - pv_surplus_to_warp.yaml
  - unifi_arm_alarm.yaml
  - warp_onoff_from_knx.yaml
  - warp_charge_mode_from_knx.yaml
  - warp_mode_buttons_from_knx.yaml
