apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: pve-exporter-credentials
  namespace: pve-exporter

spec:
  encryptedData:
    PVE_TOKEN: AgCD7QPqT/Eqt/5FmkGTFG8O79fr5TCyaAYkwhLHWSle4UpS4xBle0n+miRqnbwtAsLIc8DuaPVy3SlmsaYKaLbrfffzLac1wnE930LVIhEPbBDO0BCbTO29fYkCQ3OYB8ymZ4r500l5HqG/hoa2DojnlnEUY0VcKgG2O/XPg5sDqIlGcQKNEvWOFmiOK/fEh/TiXKr9S0SXhC1xlwh8egwd1Va8+Ngvkox0JdxforeGAZnNfoq/bNrH0Bv8aEo2+L8XR0P3OOO6gckN2HeM9CqORo79Zu67S3DfOTWO65OOjn9mSPXddF+3dC4h9v43wTFwEXmkc7D7+CVROsDiVE7sUApvSUemnWZlr/J/9bvwGSzivybmmZ79lpSy9vEN4JH6yPPp9lNB6iElzMBjhxQ4B96XFEHmduaYn/kNSrD2S3i4ijSdxUe1x/eiEq0idUSGVSIUOSK13O+TlPPT6OhIC7eGNCSGDgcEUT8k+xIYH7k5j0dvD7pVxk0ldw/X+aneczYfUXsi0dxqSyj5w3GdMs8+LSFOR9wlV+nrNy6UQ51kEEX/OJzMs0JusG4lPEI/H81MFX/LI5jlhrxm4IbnhUdENfz8GxFFwCtxa725rsUl+B3TnHiWpfnnY3RTYw+T2haJLAVIjsTVLNabewMPjRBweRUAXbDULpcETtTxH5/B44+aWtmR20BKnZcudqzOk23Zxww5Pa3U0iwakV/z013fLvx1bGgrJwKmMMNUJx1hUCY=
  template:
    metadata:
      name: pve-exporter-credentials
      namespace: pve-exporter
    type: Opaque
