apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: pve-exporter-credentials
  namespace: pve-exporter

spec:
  encryptedData:
    pve.yml: AgAh1IeeTth+nzdeT+YlD92wUNspwFuIahI7tJBmWz4Nl7zn2JRK0w2SfgZAoeLY070LMSpUxEW3aYGjWVlJ6jHB3D9XkGgjD1eGR21sjxybYNxyISPbfDMnA73khsDbMIbm42xOGMpBd1qRoEqdhbyqPcXF2iVW4iD4sUQhBpcyr9RhO3LgtUiB9nnxqMohzpUhHtvc2WInqk8xZn4PkptRy8Pz04jD14IP+H4MjpaL/7wnRh9JAf+mu5cA1N884G9AeaIFQOlUpTV1sYGc1aVRcXcJ+p81MCGEA4kUOjeUVSjMhPVHQrFJ9khNbSeJZX5Yla8OqOltVV9Sy7yInAXsSI8xWpZWUL0jZ99bh1DYl3c4XSyepMpyc7oC/wugjzVU0d2hwjH6T9WoFFeNyfZHPfRxq0aMfftLuFoKQP0P3eiPirhcmD1juWW9ir8Y8LMZDtlsKc9RieaU1BJ2U9QlMmdOEbGl7Yue+2yYbYZOPMhWIiKrNjFrEXw+gNPYLeseXLFrqt6kSID5GVlDWzXo0b7eYi9evC4vN5ljbQvkMfxNt2HeFPMNTGDTN3z3WkCPTxiKK50g8ux0EoTnb1vrp71z7fSkVtF05qZErEco+fUj5K0DI4SXOOApMsOdZvpRyxshXu8yxdznIpw/dTByUA8Cj995svmbYd6mnJ3rEekdgclpQNIPWTMTQCWN5jmLbNVra1iVoufdwox/2BoqdjB89TTpd1I1f/Tdwc03alUUNSEWaFiR0q6CLWDzQFaONqbn5IszqhTdaPT8lLwaXLNU+kzqxJ0rW9iuHfy97kpFxA044mOI36L/v6gc9ucOmjUdE+1BUFVOtNBRV4Rf6Ya/BMd738/6xV+vxOVI3Z9S741CUA==
  template:
    metadata:
      name: pve-exporter-credentials
      namespace: pve-exporter
    type: Opaque
