apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: pve-exporter-credentials
  namespace: pve-exporter

spec:
  encryptedData:
    PVE_TOKEN: AgCSJcR66COXc/aavbl0WirzZDtHIYZTEuUwdP59V2FilLPCsGXf7KJGtze0XjzClDh4tTiOyUlN9K1ccw37WomJtFQFDKlITrn50SqTxH544AU4+twTyEr7OMt3z6ym62QM2i448eM4fQO3VOeyvXy0btJV0TYy+8GF99nWLIewBjCcobLQ+KkTwIS8wtnvcJcchODKQ2IGJEbeOZ1sJ6RR0QP4oWdfDoflwoquja5bmfxthlcKh8hkrZ++bEpe9Noj6AIW6crYKdX0rVC00dR8/9AA8Yf0JGD9JsOacOZc6AjR0AQl/pZWrsWxiWu+BROEz3sIOwUxsJqyI7IN78hlGw9U0PaDBIpzFDc7wRphf59dS1WR49boCOKD+TlEzTXGdjSrwKAYo8V6WXmMCZejd8tWJnPPjqt6UwOixS64VHd12tNHtayDVVCwOy6LgzOpTOFCcJ8JnS2lKlOtGYDa4IblayfQlXFToseZKlhlSuBODZ2UiW890Jv73CWlFmCBpiyCQg1rVIdPnB5xyTr+5NJogr1GEj3kh63qeNC1hcADncadziBL7Y8rQhKi3VLBVivteaw1e4jt2MbzuG7nz3s7MFj0nn7kuWLI8toO6bsBjYvxJ22AhL3mXZpe0KKlUv+ogxSdYoI1uS/SwHyo3QOJG5fhmbztQz0Nh+E01/xOKRzB8RmQ/dhg4uJPXm57W/rh5ovVCGrBTL/ygHw1YwtzqA==
  template:
    metadata:
      name: pve-exporter-credentials
      namespace: pve-exporter
    type: Opaque
