apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replacements:
  # Inject domain name into the Certificate, IngressRoute, and Service
  - sourceValue: mqtt.zimmermann.sh
    targets:
      - select:
          kind: Certificate
          name: mqtt-tls-cert
        fieldPaths:
          - spec.dnsNames.0
      - select:
          kind: IngressRouteTCP
          name: nats-mqtt
        fieldPaths:
          - spec.routes.0.match
        options:
          delimiter: "`"
          index: 1
      - select:
          kind: Service
          name: nats
        fieldPaths:
          - metadata.annotations.[coredns.io/hostname]

  # Inject JetStream storage size
  - sourceValue: 5Gi
    targets:
      - select:
          kind: StatefulSet
          name: nats
        fieldPaths:
          - spec.volumeClaimTemplates.0.spec.resources.requests.storage

  # Rewrite external-dns target annotation to prod UDM Pro
  - sourceValue: udm-pro.zimmermann.sh
    targets:
      - select:
          kind: IngressRouteTCP
        fieldPaths:
          - metadata.annotations.[external-dns.alpha.kubernetes.io/target]

patches:
  # NATS container resource limits
  - target:
      kind: StatefulSet
      name: nats
    patch: |-
      - op: test
        path: /spec/template/spec/containers/0/name
        value: nats
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: GOMEMLIMIT
          value: "966367641"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: JETSTREAM_MAX_STORE
          value: "5Gi"

  # NATS service with static IP
  - target:
      kind: Service
      name: nats
    patch: |-
      - op: test
        path: /spec/type
        value: LoadBalancer
      - op: add
        path: /metadata/annotations/io.cilium~1lb-ipam-ips
        value: "192.168.10.26"
