apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: lares-mcp-bridge-wikijs-token
  namespace: lares-mcp-bridge

spec:
  encryptedData:
    token: AgAHDqwLxf2+Y2jd1tq27239ixaI1p53kgXbdVJuvvoVfdYdMCQijCRro70/JZ0AKtUvZ/wi5i8v15mJhy8cawXNUTj3gtQ7ngopt2iRffQAkWR/iefC6d2mtEFJjG8dGlHSd0aI0Khwyac5vGo0VprBTGyalwdGDRRbARjfrchKl3i+KgzaYdlrdsuYNKLAcxEKP42wV41uMez+i84FU5aKzG8GT1DSGw6IGL2JTKO5U8bVpAwEwHYZwmLIwR0rhDVLt4/kVqpklTZpqNnhZ6Mg6gk9DnVBRGeP5Z2e8hoXAHl6BSiLFQRZ5zTRkIsDcTNsPeVsbcXqPiZmZCFVXtQ6djWJaIk+1tGfdAnQbl3DhIjG1JgOEMd1KBGSyXCHKJFkRnuWjUJkq7PkWMAO7VWpXJ3j+m3t3O+9HrIF1Mf/AqutcIafy1VjUINEges17hkw7YrZdSja8Jw4qR2yVVWDcHTG3ER7CldX0LEBn8DT3jpGA2u6MdvHZ8eVqr1hdAxnQVNt+VY3TgbSsHpSjAvzYUDw42IOyNx6LizNgYMzMYNoi+2AQdk4c5OMJQqByQwcLuZPKfaZlPH+Uo0tZQQTlH2lPs0bsXvtZJ6ZUyG8wGMFTmSHyjDVhOhh10V/+hzYxckeWpiQkfK3RrPvS9UL6zbfqdesWI0gdE3YfcyPEXf0G4UwHauaCdz4/6Lsl00GkT9yaCdiPC6OgdC7Q58/3mShVmAd26zSIhW0Fhh2MPYyRJOBE6z2Plf7hDPv/6E5p46/03fgPMxcgsTMLdChboouMTsIkIMErITjdnrqcvN95rQ3IT73HmqF5RcBwiNaqpoCKyzyJTv+U14Hh7PQPZbKGC0+ZV5AYXzlszLIqL5LFlKVlDOIlDcJM87fAso0KF/SeNqfg8ovuZhvwwklVRLjKLwRIgwTyfUfJ+Uwn8Z5FhJJHPVJNjwqlVunHvMdDI+7Oy4s+bNK9xOCRIZEbGHgrhx+AuvSbhwnwiM+zCBj8CFf6pnpIIG3Vj8jniCU57CMC+Jck86J1kXqBLRinN06BYeLauYoTsvrOSnv7VF0CXg4cvnG8erdQ5ScfpERJyKWaRWzqSgXU60N/YmCFVMtn5FxjIIXx5QqNKI1IBIrGMPeW8bTlxzLg+/a+uh+GOkC0b/F4tAnUI4V7+k9i4ekw/4JXrHJMllNy1OBV2X9E9irnIDH9GtC9S4UxbR50u38im/GRfSd46vuRlyNzJ3lL+c+WfCMXPw2LN5pBC5RVD7UlJVtUlnqU0Vqsnt0PYTSiTEhuOFoGlhMONtns8rZhJkkl8b5cX5lR2W+uVGz0Lj3FcI1W8Z3/yml3Z39nMiJIt/5IzQFGP6OOJRMvzejPcrW
  template:
    metadata:
      name: lares-mcp-bridge-wikijs-token
      namespace: lares-mcp-bridge
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: lares-mcp-bridge-auth-clients
  namespace: lares-mcp-bridge

spec:
  encryptedData:
    clients.json: AgBIzeC2xzXMd/Xe0vw7IrUG7d9Z3YDigF9vHdSpJusNiBQt2FQ7g3UJ8GQXrhr08GbZVQauLQrSWF+cRUQ/Pk92qxWOvmtYOKD5OPaNXrC7hn+Vod9Be0XWEdzjKGDRviGCgfF0+40HBFJ0iUWStzI+i0OygyEnDMhpU0knk8tH2+baZUTSlCyuObhYEKlZx9bOlfv6Vr79F6Ax3e6dLIorhYFVUzWs5cig4BAUTh8B0i0XDnihBoLWetQNOKIMNSBWBoMEESHHkXnG6zNfe/JDUD4kuW4Kwa7IONRfNFTLXH1+vQPtmAmG8yq7nVZqGdX+J0DL5w0hoSeV6GcyKSiCk24jZPA4zi/GHVwACT93K0CF6XKN/sEM8ibqVVEi/pUQ6cZHBHaL+sG+QLJoPOz62hMECzBJMypST4gvCm9zG72FzhbbCi42VZsbad5RGZ8VFDbF2Q1OrXYUq9r9aHMt7UkOTqwXJmfgRr28qBazYgfz6f3PB8/+/7c6ywsS/nU/iSsPGEpTd67oFRccebvMU2VBkZyq4adppZubh6jQFv4JVX8U7xpAv3ZzfxGIHzZQ1TJ2mkG0qqHzbXOjHsHkali8M8yeuWq+tfeliZi3T15TS4EA/faY+Y9TF8jcuor2zaCxpbN+etHLzIlPo3LSivOII5Rs227vpXw4S8GMZsnZaPDLDq3yg+m4PNrvm/w0GuV3R/LJykdu8AR2TmTY31xsZql551YydqbHaDGrteRp0DTydoL5/J5ODs7NCVD/7HzpUxedFmzFlYThULPudiHAuwWoyKoe0DCPKGGQY7lMNODrA+qdDxbJtQOJ1xOtaSW+gN1YS0+8+/XsLlM6Yk1OKKD7rGZJr89e258a7kctTiRDZvXRvpIhuJZzrfoZD2jO/WnUOtvQbYxcQKrak/6/+4U=
  template:
    metadata:
      name: lares-mcp-bridge-auth-clients
      namespace: lares-mcp-bridge
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: lares-mcp-bridge-trigger-api-key
  namespace: lares-mcp-bridge

spec:
  encryptedData:
    api-key: AgBBc2iJTMW7i9mmbpWFLJXqAJxY314Bbfefca4ylfYDMY0l9Xn3MvD8Raqaz8go6U1LS1s7oaSpUTwpnae/VYmS5VqRjx63jizY3799LbcjiR76WX+vtvHca9muOqbga3qI0y1ugIVNRLTGBlLZ6bLmNEBtm81LYroPo9jPNnfrAO3/hKxcuMmZ248l6Pn6HFHg3LZA6EIAZZfG9V/iI7mFy/m6RdEkpHTgkyMfOnu8ohOpxUq46rg7mnw1QULCSkivlmGkJUTkfL3iyrbPk11djMKhcUTGKakzrlM4gKrJGZ+FhtaFriU4sWIuAgX5ltxP/Iz6PlSVFtB+DJemA+dVpPK0wYHkeGss3lceFtn3RvLfx4lBro+TWa4vBb2g2jq/bLMLGFvMbukG36fH1WU+UIvSyKJUvWAHveNZ6C6s9O759OCBk1Eeg3GjwZciOJOEY1meB5S5Lk8JbOFEtyE323L40LmXVyRCkJhzHyLyZG303vPxFwTZBk7VRFOfQ2Q2bGQewgC20I7kFQNxgF+vICvJAv3Z787qUAKjBh7cbgjo50APDRQl4vX3hPSP9cuhU4uEXimThxfBo3Xv6yLGJRpkes1VwJtK96wTmHAalpfKweCU36gMI/SDwfqENdGYIj+9GjBANqObSEOJEBpV5j5J9nUnoyO3evWOCOCcM8VaNYynUzwt+jJDBgHgEF7/2zfx30eWuJ11GungDMI/PxeYKAmB10eK072o9zL4Vnh+8wo6M8fx2ynuov+09M9Y6ybt+lRRK2qPWqLun3PK
  template:
    metadata:
      name: lares-mcp-bridge-trigger-api-key
      namespace: lares-mcp-bridge
    type: Opaque
