apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: lares-mcp-bridge-wikijs-token
  namespace: lares-mcp-bridge

spec:
  encryptedData:
    token: AgAGGTEe7l79bTvP6X01bnbU/lbLAIPPtJAX+0WP5JeOX7uAo8f1x+gdRfcrSIF9AH0TRyMPQDGuhj5/MVZWS+CKBpwRCqWwT1nPg9zYKpeJp9WGMtmJj3CiUOqz8495REru+3KSJHvKPgWdbcr9pMYc3xUPYKHBPyQCKM54F9YF1HC6EzF+d4CiKaMcTPWDTT/z6Slk+67D+LwRFYkf7j9TyhFyzUkSv4c27s5aemC5wckoc2uILgPD1qlZaGDDiRitV/TynKgVbBnN7muNasGduYVo0X871yje0Ms1E2aDb9vGd+hPv+T7j0bCgJYG1VVQJqXY2hT37xyDih0IFxB2u/b0eefk6N/TRvYB7BKaq0uKe1IAyNKqFtSHKFxLNhlmiBILuib9cx4ycPnq/3/TnLkYi9c1LV/dgt7q4ak53JLTW8xqcKGHEwQHiZvE0HyjqOPH768TrhVYonvphi5ACBtm5A9y2pJW6lS6bdsAo0YtYyT5tZnAF0bnQe0j0/OdqjsATJ82Z0p+XHg9jt3QoPV0qtKzEqlRabswXKki9+CYwoE1hwm4avfejMBNCol+/5F/7EGyHbOzwkmF/ro9VsHTMFz6svzVfiu9XMB5AfLcm9c5ibQ1uBoGTlqHoUVQdC4nWcl4mLCV8K26WVXqMNrXnGAlp1gpJHQaeEjQDloZT7WN8cwsCPfuLhfE9EigewcOA5Bg8xx/OGahcc7U1xqJNGtpfgESDR8+u3toS0eTwaQ7sN0iiDFn4r6sOMHesUoLPgSXDu7Z8Btm0jFWhjh5bbrCHCP6tL/JgTPYROlfcKganvbC7NVzhFJvueyDAQJHxu8zKEc4xYZCFoA760/kaGojYxkoVd0DiQAfbe6K+ffCvZFa+DIZUTxEKeIO0o39tVb8uGaFZql7tkntJ1x7P8r5SLCwoaOeO9oM8vHbzT8FnRjYRXdm04YZBQPKhKvnK9sgDqiuzMQC740XB+Lr2JnVdJ31ALAwXb3UdItsji8ylSkjnXvoDWedRcEa3SfSdR30S69RvIr1VCV2FRNXXcr0gAtHU09/YU2QSxR5QEVQOGDNneFRb0LEBMgKKZ9Ke5mROx86RaRijSQOeBLYF4woZKtLIL2lZ5CL24ZCSaGJ1eo67sqW3w+9ROQ0jPVUPv9CXReTTHLPS3GgC7smI3zz4Vup9AX3Vk26vwotsuPyg9tAuIfly9yxXrGr8vuM9KFmiVNzjbheRSr6QvaH0Up/BLmGZNTDKjoutIEtc6AciYFMtZPi+LIvyaQ0I/4Y5oWx9bMIQJUOq7F3HSZ9qdGSiKRQ+ENrx5MrBGOv7cAHF8IeKlCOmTto13inO2yhmhxtd0gb9LduL5IjGwujL2g4
  template:
    metadata:
      name: lares-mcp-bridge-wikijs-token
      namespace: lares-mcp-bridge
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: lares-mcp-bridge-auth-clients
  namespace: lares-mcp-bridge

spec:
  encryptedData:
    clients.json: AgBpvWFEVev5wlbyiGVehFxbtLcFUEqnnzduoy3e5bj6kTXJQSCRAGSkV4wuSQPOX2yJajKGQn7ykeAiV/wa2oI9JFrTopsFMXDmI4R9ysIVrgaI9P6cjdHE0f9/qQ27vWl+P6uddJkk7yM2xpwDh3W36lotm7GCv4/slcapChyp7UbUZOIDBy/bAvkjYT2ubU0QRtqAsbTbzayGR85s3eAKlN66ht5pde0IZqNlETxnLrgRZyIOlFGNClKePWFTktLBoLT2t5ghmtvPdcNe8BmNAnl3jCTDkJsY2jsnORhobhMX8Z+Xw+48fFsuD9NrjSUrTlfbkHgzEh1tG1noIgQKhomHSX0S2Sbg8ChmguQ0Moam1xkmYNDDdekrQTzP7ewUBCHoWCZMRbY6zkJnKH4EKV1XbZQg/x3n617XQcx5HhXcBFK5K1xYjRrxseyQCvxNja4GgP8D/634vJqjji2JEVe5Y054Fmw5P37WS+wrdT4MvEHlc5BK7hwaPjmOyCx7Kzrqdoj5CYbWTs1wXNfnjq7lJHKh/AuB7tGLz66u+cDIZaI0Ydqvuw8b7Hp6gLLFqLAWjzrOuAgrGSZ4R3PBjdGVndXB5o4ebKDBFAbxkn5AHge+BVEk3Sz8qIIjZRrkYKdIj46ItPfRDRO9SuRA6x0c33pCmO5UzAh0CJ5ow6JWElOA9qEeH2GcT56kC9Mrf8XxL25NI1Ob4lGSBcRvVz9OR04S6RwfxvaQe5VShXwCsC/l3Nt3zzFPPoR7DMeI4uX8FOuNk5+mdeQCjQWlqozDJRsvJV4ZIQcBVFbmqWuYyv5sXMW0j4YENfJhRmduKdURDDuJUgmKSot4MU4EcqhxTDJ/IYok61DV5ReWoQChe9IxAFRYebKqtxxueObmyZkJgygCRRhPnVZXySzvkL3ktGPYRq0j40JIyeSEuYcjxnYv/Foz8IZZP/+aL0eqMcC73SR8FHYp9jWXtpZr/CFIVYJiFEZtuk0yPJQlwrk/dcZ/VZlAfR+XjLYL/tq5t/iE3+LIjRiuvjH8ODxU/WZADVHeZdzjaLwjj4OCbl2GYwKvqu2V9tO5xnvmbk6lhblO0hvwHiEtmQAJ8eHwyzBF5XuhlP9xidYTRXIdN/QqCu74xR0zcXuJ
  template:
    metadata:
      name: lares-mcp-bridge-auth-clients
      namespace: lares-mcp-bridge
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: lares-mcp-bridge-trigger-api-key
  namespace: lares-mcp-bridge

spec:
  encryptedData:
    api-key: AgBBc2iJTMW7i9mmbpWFLJXqAJxY314Bbfefca4ylfYDMY0l9Xn3MvD8Raqaz8go6U1LS1s7oaSpUTwpnae/VYmS5VqRjx63jizY3799LbcjiR76WX+vtvHca9muOqbga3qI0y1ugIVNRLTGBlLZ6bLmNEBtm81LYroPo9jPNnfrAO3/hKxcuMmZ248l6Pn6HFHg3LZA6EIAZZfG9V/iI7mFy/m6RdEkpHTgkyMfOnu8ohOpxUq46rg7mnw1QULCSkivlmGkJUTkfL3iyrbPk11djMKhcUTGKakzrlM4gKrJGZ+FhtaFriU4sWIuAgX5ltxP/Iz6PlSVFtB+DJemA+dVpPK0wYHkeGss3lceFtn3RvLfx4lBro+TWa4vBb2g2jq/bLMLGFvMbukG36fH1WU+UIvSyKJUvWAHveNZ6C6s9O759OCBk1Eeg3GjwZciOJOEY1meB5S5Lk8JbOFEtyE323L40LmXVyRCkJhzHyLyZG303vPxFwTZBk7VRFOfQ2Q2bGQewgC20I7kFQNxgF+vICvJAv3Z787qUAKjBh7cbgjo50APDRQl4vX3hPSP9cuhU4uEXimThxfBo3Xv6yLGJRpkes1VwJtK96wTmHAalpfKweCU36gMI/SDwfqENdGYIj+9GjBANqObSEOJEBpV5j5J9nUnoyO3evWOCOCcM8VaNYynUzwt+jJDBgHgEF7/2zfx30eWuJ11GungDMI/PxeYKAmB10eK072o9zL4Vnh+8wo6M8fx2ynuov+09M9Y6ybt+lRRK2qPWqLun3PK
  template:
    metadata:
      name: lares-mcp-bridge-trigger-api-key
      namespace: lares-mcp-bridge
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: lares-mcp-bridge-wikijs-write-token
  namespace: lares-mcp-bridge

spec:
  encryptedData:
    token: AgBxgDAX3x51HDefrQZ5nY5ZPL5zHwVHFy2r47t3xxQt5SVkgQz8prR6KL92GOdt0eDsnfAwP9kKk7zmUMDVZfrKN0p1cLVTHBl8+TnvgrIOiCTe2xWFQUAvf1DbzmYjQOFnPKbwOxQijCAyOUxLl11pKnBQO0Uldoh+MsbWDlzXwVtkQRAs3vZumZ0JIj6aQJhDK761SQud/JFIZBa4OSJOPA79aoK3L2dS9mwWz7R6k4t9lVI3V6Oor0snH/8jDDHLmMkYhhhcnF18yMu82tgRb2fHiyU7RZL6DqsujreHrYKLk1F4TddH7nOzs1hRImsTMxEgEJ7FRjXXSchvDL/Tg2izoZoCV1u1cLCkRfnVcRkYF83Gv3B2ygEB4JvZY8S43YQWLbIuQyqKz0ra5wpaAbFhtrPwW6ighGvFWqnTy1jX+mdxAiPkg0qu3ZzID1gZfjI33bPUCnQFKdgaiQ5uYujIpluRgaVCXy9fgvT7JSWYTGKt5VRnQ+nbQxEjB79aKcZtWGWA1fFrh3KaacAolvTpeY7x5mS0LaZh9IBmRIjAkDgVhMLANt5zJAefQeCi68EmXs5dk5Bzi9RgIt++/CHBAcXW8uFwnFM4abcyc8PcobngwI1C7+J0kfHKHEDTMYbpgGp4iF4JOIDfvdS4ehWSiFu+v09GfOE02FNs25HajagRRJ1EjaUU3Rk36X+WGfVHsuMvDC4xhsKGfaH7NS58izAy3Wkjmnh+mFMP32fiJc5uZ7PjcZSJ7zBr6bjORfCAhfbTkevMO78K8/4Qscpy3jC61k6kcvaq41AFy6d3CkHD46wCxulXv582YZHXYe1xWWMi6eJ7HwCFM57H+h6Vsz/1p7E0tyMdyNAC1jefpOwSaNL1WPCz8mLhFhh2B1kuRkUSvgbYuXRQ8RP5VLCYpnQZTymnbO98HabMrP8RV0AvgUUpQUHb9buPvxeokfnGAnTx9boLFfT5Ykk8bpZ1Kxx8KdBoFkacbJmPgwmNASn/uwC1uo8OuYNv/pj68ZU46P2LJnPdc78YInRNJZNonCR+M7aQJgb0nOHJOl5VSaJ5A4cO1OvGtN/bT3hhj22qCuz7QkwXaAg8pEfJsasjDCANRnbXkbyO5fY9DEVZbM77JNCSv/fUNbyzJyO1DZoobzbzFWUMJQODKwIM/Wz7vEEGzeGgy1A3ZmYbyAD88ZdK7CymXaMfobgt4Oum+mwZq7Dgl+GCN8S6/Lv1mUUqvHyhbMj7KFL4wkcnqRYH4Ef6vfDA5e14oREEysR/e/qH+BB4Iyp+D3nEAwSTOWve+bfFHOE66LnEI8lQ4F+lc6d1oPeWn8c8uVg5AR8OfyhG+ET1A9/FyU7U1dit4Y+0jYva
  template:
    metadata:
      name: lares-mcp-bridge-wikijs-write-token
      namespace: lares-mcp-bridge
    type: Opaque
