apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: lares-mcp-bridge-wikijs-token
  namespace: lares-mcp-bridge

spec:
  encryptedData:
    token: AgAHDqwLxf2+Y2jd1tq27239ixaI1p53kgXbdVJuvvoVfdYdMCQijCRro70/JZ0AKtUvZ/wi5i8v15mJhy8cawXNUTj3gtQ7ngopt2iRffQAkWR/iefC6d2mtEFJjG8dGlHSd0aI0Khwyac5vGo0VprBTGyalwdGDRRbARjfrchKl3i+KgzaYdlrdsuYNKLAcxEKP42wV41uMez+i84FU5aKzG8GT1DSGw6IGL2JTKO5U8bVpAwEwHYZwmLIwR0rhDVLt4/kVqpklTZpqNnhZ6Mg6gk9DnVBRGeP5Z2e8hoXAHl6BSiLFQRZ5zTRkIsDcTNsPeVsbcXqPiZmZCFVXtQ6djWJaIk+1tGfdAnQbl3DhIjG1JgOEMd1KBGSyXCHKJFkRnuWjUJkq7PkWMAO7VWpXJ3j+m3t3O+9HrIF1Mf/AqutcIafy1VjUINEges17hkw7YrZdSja8Jw4qR2yVVWDcHTG3ER7CldX0LEBn8DT3jpGA2u6MdvHZ8eVqr1hdAxnQVNt+VY3TgbSsHpSjAvzYUDw42IOyNx6LizNgYMzMYNoi+2AQdk4c5OMJQqByQwcLuZPKfaZlPH+Uo0tZQQTlH2lPs0bsXvtZJ6ZUyG8wGMFTmSHyjDVhOhh10V/+hzYxckeWpiQkfK3RrPvS9UL6zbfqdesWI0gdE3YfcyPEXf0G4UwHauaCdz4/6Lsl00GkT9yaCdiPC6OgdC7Q58/3mShVmAd26zSIhW0Fhh2MPYyRJOBE6z2Plf7hDPv/6E5p46/03fgPMxcgsTMLdChboouMTsIkIMErITjdnrqcvN95rQ3IT73HmqF5RcBwiNaqpoCKyzyJTv+U14Hh7PQPZbKGC0+ZV5AYXzlszLIqL5LFlKVlDOIlDcJM87fAso0KF/SeNqfg8ovuZhvwwklVRLjKLwRIgwTyfUfJ+Uwn8Z5FhJJHPVJNjwqlVunHvMdDI+7Oy4s+bNK9xOCRIZEbGHgrhx+AuvSbhwnwiM+zCBj8CFf6pnpIIG3Vj8jniCU57CMC+Jck86J1kXqBLRinN06BYeLauYoTsvrOSnv7VF0CXg4cvnG8erdQ5ScfpERJyKWaRWzqSgXU60N/YmCFVMtn5FxjIIXx5QqNKI1IBIrGMPeW8bTlxzLg+/a+uh+GOkC0b/F4tAnUI4V7+k9i4ekw/4JXrHJMllNy1OBV2X9E9irnIDH9GtC9S4UxbR50u38im/GRfSd46vuRlyNzJ3lL+c+WfCMXPw2LN5pBC5RVD7UlJVtUlnqU0Vqsnt0PYTSiTEhuOFoGlhMONtns8rZhJkkl8b5cX5lR2W+uVGz0Lj3FcI1W8Z3/yml3Z39nMiJIt/5IzQFGP6OOJRMvzejPcrW
  template:
    metadata:
      name: lares-mcp-bridge-wikijs-token
      namespace: lares-mcp-bridge
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: lares-mcp-bridge-auth-clients
  namespace: lares-mcp-bridge

spec:
  encryptedData:
    clients.json: AgAUg77dWX7N1xuEGhPFoqs8I3swdJTOu3zmipk94/mosU8SGb345gTh7vPCcVKT2LKFurmO1FT1kdz0xaYcPmn6PrPv1ZZjbeZeZeWhh8bEJ60wbEBLUGq6+r7dy8eTFCt2X/r8LBL7qtDE+8iKYZIGorn+GXkPyuYT596d2o/sRl7IFi8dEMAcPCNd/Y0OfKuJOou9cMj/hkpsiIcPyVl7ZqLn2rvnZn04XoUo48jkRVMCXnxp7HVKmIzRXTnOVng8FMZcLXwNLdA1fwhP1loEmWNW5x8gqIDf3iNjIe2T06u0kRBu2ObY4Ee3QQuJBLG7lYLCnBU2FGi5Qi3y2GbmllOl6SDUqLmXvZS20bi2213dlVcQBC4L7qlLJHnXa6d7PAV7btcLptykTzjfvC8d+oa8/z0BT6U5xk+Nj1QdSBqHshIvycZLfC5ZtgxzbIGbFZqCPMjtdzq/eTo91cdJ2/LppOCuaxJPD95mJ7NsXyE0NWwZcAas0f+FEbHvgjAVigyOPgWRJQIeoJCSwMBZNKfiH7ZmLEX+QYoy7O0LJzovLavVv5C6DHkGH5lhIqh4KI1a1DBntthkvPaFmACy+QnsYMfBMzckKLhDrHRx4Zi6EASsl4IomjJmBEANMsJAdW+NUN6nYjIY07+l6C0Br2a6VOGvV+YSDC/AFkFk8ibd2ACBchTZRf6mD88u9DKm0H9y39vGwFVSBduDloWl2Blcm3u2ZBwDu35KJTDPZzLXfa49BgS+JwVSOEkDON6g4KD4DlTlXVdtceboOYxG/XJSEKyE6KBIRMxUAeKbBTDKJ8NYQzoJNnOTuVfcaFwg4RUsZkhrGqA9cMyN/uGjTjBJwnx9PJLrdyy/sfWB9JLzPjcOxJaXTnIN5oMHBPIIosf1pZzO4zG8FoToqJyZvS82QbGET5Lp2s1Gdkgs5J0SLdzuRz+T0CIhd6IkFZB9XjDwamc+3rXVN3kAmjLRv81OWQ/QAyvd+JG6U4khGWf8MSx3mLOyWJlDAeUXyjkYb9DOMpV8AY8=
  template:
    metadata:
      name: lares-mcp-bridge-auth-clients
      namespace: lares-mcp-bridge
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: lares-mcp-bridge-trigger-api-key
  namespace: lares-mcp-bridge

spec:
  encryptedData:
    api-key: AgBBc2iJTMW7i9mmbpWFLJXqAJxY314Bbfefca4ylfYDMY0l9Xn3MvD8Raqaz8go6U1LS1s7oaSpUTwpnae/VYmS5VqRjx63jizY3799LbcjiR76WX+vtvHca9muOqbga3qI0y1ugIVNRLTGBlLZ6bLmNEBtm81LYroPo9jPNnfrAO3/hKxcuMmZ248l6Pn6HFHg3LZA6EIAZZfG9V/iI7mFy/m6RdEkpHTgkyMfOnu8ohOpxUq46rg7mnw1QULCSkivlmGkJUTkfL3iyrbPk11djMKhcUTGKakzrlM4gKrJGZ+FhtaFriU4sWIuAgX5ltxP/Iz6PlSVFtB+DJemA+dVpPK0wYHkeGss3lceFtn3RvLfx4lBro+TWa4vBb2g2jq/bLMLGFvMbukG36fH1WU+UIvSyKJUvWAHveNZ6C6s9O759OCBk1Eeg3GjwZciOJOEY1meB5S5Lk8JbOFEtyE323L40LmXVyRCkJhzHyLyZG303vPxFwTZBk7VRFOfQ2Q2bGQewgC20I7kFQNxgF+vICvJAv3Z787qUAKjBh7cbgjo50APDRQl4vX3hPSP9cuhU4uEXimThxfBo3Xv6yLGJRpkes1VwJtK96wTmHAalpfKweCU36gMI/SDwfqENdGYIj+9GjBANqObSEOJEBpV5j5J9nUnoyO3evWOCOCcM8VaNYynUzwt+jJDBgHgEF7/2zfx30eWuJ11GungDMI/PxeYKAmB10eK072o9zL4Vnh+8wo6M8fx2ynuov+09M9Y6ybt+lRRK2qPWqLun3PK
  template:
    metadata:
      name: lares-mcp-bridge-trigger-api-key
      namespace: lares-mcp-bridge
    type: Opaque
