apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pbs-exporter
resources:
  - ./namespace.yaml
  - ./sealed-secret.yaml

helmCharts:
  - name: application
    repo: https://stakater.github.io/stakater-charts
    releaseName: pbs-exporter
    version: 8.1.2
    valuesFile: values.yaml
    namespace: pbs-exporter
    apiVersions:
      - monitoring.coreos.com/v1

labels:
  - includeSelectors: false
    pairs:
      homelab.app: pbs-exporter

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"
