apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: pbs-exporter-credentials
  namespace: pbs-exporter

spec:
  encryptedData:
    PBS_API_TOKEN: AgCQ0WKPt0Z7cs7k+/sHzWCzs8hv4ZOYTJF7fr70EBxdJft+eHDqDXG3G9ZSuag7m57h/H90DQYXhQ1r5R8AK53xQ8/gw0l8I1tkLXunlZr5GK25GMdqGijYLqeqibID3IhDm+Zo/gHqzI6hSEoh7Pyt4nSTZSjOH8NXFVEhIqmCmhehzstnTykvdpRLIP3qA4dFsSGRa7hCjeq2eyv/zxddwckYS2QTQNfxnZBFwDOLyRcjrL4m/nO3iY0/iLyhfyVBbjTJLLeTJFOQb5PRcG6bdo3XadD41qRbG5tzeUEm49nOZZB/BNQ4DU7ai43g5XfW4syJVw7ZBnpRUJWuYi6cP47Y3qrLotmH+PNEey9XPdBskNlaY2scotDSvSlR9/EPSJGO1L2Zdy8mdywMEU9Hzf1tSEiNN2qVTln7bdkbLmzSlqS7fJ+AAvQ3kao5KeBv2yBhORh8WCxWi47o4TAeVWRyowmal/GhUYTpyo1EiWkXl9LIFkwR4Vy8EXjcdPt2WsVE8wwTkng4ACNUNDosGwm4Qwu2HYUbLZah3fG/TuSoYC+sZ8KPihA2doBERH0EHoDzB8sUdpDQUdhJlQ+vtOvXThdT8dZmpF1xLU7tROcfrIqM/mvMwFiZNJhw8F4jzco1wDMZ0Gi5fSqRfpitmeG2sBLV93lO/nsBGAwjQ9vr7X5YhisHt0aG8oJAXsgLlogh7EzA+x/QoDPdW7+oVqDjhaUzrURq/C+fLT70vSg6YYQ=
  template:
    metadata:
      name: pbs-exporter-credentials
      namespace: pbs-exporter
    type: Opaque
