apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redpanda-connect
resources:
  - ./namespace.yaml

helmCharts:
  - name: connect
    repo: https://charts.redpanda.com
    releaseName: redpanda-connect
    version: 3.2.6
    valuesFile: values.yaml
    namespace: redpanda-connect

configMapGenerator:
  - name: redpanda-connect-streams
    files:
      - streams/knx.yaml
      - streams/solaredge_inverter.yaml
      - streams/solaredge_powerflow.yaml
      - streams/ems_esp.yaml
      - streams/warp_system.yaml
      - streams/warp_evse.yaml
      - streams/warp_charge_manager.yaml
      - streams/warp_charge_tracker.yaml
      - streams/warp_meter.yaml

labels:
  - includeSelectors: false
    pairs:
      homelab.app: redpanda-connect

commonAnnotations:
  argocd.argoproj.io/sync-wave: "4"
