apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: redpanda-connect-unifi-protect
  namespace: redpanda-connect

spec:
  encryptedData:
    UNIFI_PROTECT_API_KEY: AgCEyU3FD399Z3Dy7sccOu5EyoqjdXCGpLXGzt2bziySvHIv47tS7IhlfdPa5bMtc/Lky15r2JPzQo1RwYD/q/6maX+0vd4J2EkAMnLatAr1RDejlZeL16fY56uEmUnUVxJ40vkmqHSS4g5vWZXAE2XDJmHBvItc9s21+azu0FyzqtP3yaDsjAZ9TFiK8t7FYpHHNAcCWkq9MfsTbmjkabGcphpdXYbVjZQB2dEHa6491EL83CmUVY85ZsoLfF7//nkfWBG98ykLXPq61fn72G4VTIEkcNoSSCo4RiRcqDj4UX5NYKG06XSM0dloKJAnUtH86rGbwiV2zlNXZ9IjE7b3fj4xgXa+dgTJhh3tDQMrIdtO2vX7irqjEot7xiqyM+BdodZmOJTcgYAgzSuxZJkFZMWzeSa7FP0s215QTMEuYfQ9AaWkdgWj/DrO/VnPj84Jv6YJOsWq8kwzxuss9sGTmZZv2PE6hc+tsq6KhGtFPes7InRzRJtbF6xasMTjO3cZ+2tf461ZtRUdZW1orq5omW211dd8P9tuSEnsJJrWBYrgIBHUF+uNazlkE5OPCMCkotirZGs1kcq7xomlx9PIpf8gavjsfj0aT4T4Ij3/WwA3vrUIG8C/5US1sdDggyrklkG0khD2a6B2awvWSGM04f6FwmSWplb7WPdgQHEWFGUexpTEolLvbO1fOldh1lnTbSImn5rPjgfzzilNFaoYzM9eDAPBA/wcdeqLVSQ3zg==
    UNIFI_PROTECT_ARM_PROFILE_ID: AgBwOBfLGmcd/QMcc4mn/ZPULS7IFJLz4sj3GliWPDkF2uHKmjG3XHS/caxHqFbHAW/VUsGm0IG7ogp2W6/EnmZ8blGFqOu4NpTBE3mEHwAEZEeClew42Jfg6W/pLAh8jkoI3mwUN09o3jVIpfUQLykCXkCXOjq8QiTC8Fr0uktZGCaXO2hhU0+c68x8hbwY69YZa/9V2sz7g2D52P1tNuIXJ70DWGDnFKZmA17ICw07vnwsjFBqKNjDwmyGIAHPNRwY43UOrPOhY31B3C1ElrMqU4+UM7uB0zOJ/LXK2q+DwxCTuv+t7ZdF1Z8Xi0H4KUfVe86eD/GuXny3X4gpr7ow4DVJZG5tjoVCRCQfBLTL3pTHYgLvWQ047c1ljfdODL5EZYLkXhVXrAal4DiFV3R3wJN3wEQvf6uGprWAdfsLZKDv4/aiyF+B5BM7RZXj77+gVI0sZyprHDoXUHrxK5EG1DxZTCh8UYWfApNXuazrYGWZZk7JpHzOCIl9B6fv7y6+T5rbmffbP09E04TENbSa6CluOyAtVO9rt6AU0LnjFPcxSGlRdT7SVywMXNWaVh0vuHZyrWLyWBgSskEyhVN+ndyGFU6Bapbq51uhbCyEsIPDdZab1Dsz5/LihjGeNh1Fv0WCgHZc18Ls1FkHNnaTUe2Ufc5uDzUM2R5MXBB4t82A+MNEdSA8+IyLi8jk1esl4lFfvQ5g5qTLoMMDNDbzPYJKDkVsBgw=
  template:
    metadata:
      name: redpanda-connect-unifi-protect
      namespace: redpanda-connect
    type: Opaque
