apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crowdsec
resources:
  - ./namespace.yaml
  - ./sealed-secret.yaml
  - ./database.yaml
  - ./rbac.yaml
  - ./machines-prune-cronjob.yaml

configMapGenerator:
  - name: crowdsec-machines-prune-script
    options:
      disableNameSuffixHash: true
    files:
      - scripts/prune-machines.sh

helmCharts:
  - name: crowdsec
    repo: oci://ghcr.io/crowdsecurity/helm-charts
    releaseName: crowdsec
    version: 0.24.0
    valuesFile: values.yaml
    namespace: crowdsec
    apiVersions:
      - monitoring.coreos.com/v1

labels:
  - includeSelectors: false
    pairs:
      homelab.app: crowdsec

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-1"
