apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: forecast-solar-credentials
  namespace: iot-insights-engine

spec:
  encryptedData:
    api-key: AgCOtIHNKGkFtpQUp2U+WrpOKtbbqk7nRKmioEiZa65qjYDH/6vnFa+cfYv39UkuHvkkDwN/CjZ9P5lFFvmd/iG/yZmDGUKeaiJ2fdxkNrQCmeT1cVFweYCmet1YrPDY155QNYu4KelosA6VN7f0OhZZ8PpN9NFS6wQlAMhCyV3OfX4hmmXop+KSc1FEYpvpWubRDuFJ8RdCr+bFYkXk61e6nrPgriWeCI1XGQolCzAiK22w3imbKr+pDqsESIfjsDyRZlyYy2hf/VdDN7rHu78L8N2/MTgYPrTubupytUD1muuZOrlU6SMru5Uw1TPOkO6Ow/hFeIbkN+5s6J+Hro8tWqdEJc9byJAuvkXDXLTgYOvtYZ2mWMx6QwJCk5Dn8MOQDCIIimAih5mFsZnEoxx3mUVhZ1cVn93ARJm2WfNIXC2lCNODEjcoP/rFiJxNYinHMiO6irPP1UAkZTRnE1nad8Khx5TKA7+qYAZQPONg2k+iyiN3HeuA/dPP/Ljpeu7s7d8JJaDLkRcT2kjtlO8GG2SR+sgH9yzUzm1c9ypEIvvRwTetphcS/Tr4cYP1JBqP0Hc+TO7UAbOX0x+j3Na55nU7fVTkswaxlKE6FEmuIgiaAZ8DGb8AMfIzVY1ymOzAkn19zsgka6l8ul2x7vohq4buHXPJlCrfudpqGwZ7+HNa4zJVT8kPHT1+Uwl/J8tyqsCjym3+q0VlrY5PC5fH
  template:
    metadata:
      name: forecast-solar-credentials
      namespace: iot-insights-engine
    type: Opaque
