service_accounts:
  - account: homepage
    secret_name: argocd-homepage-token
    secret_namespace: gitops-controller
  - account: holmes
    secret_name: argocd-holmes-token
    secret_namespace: gitops-controller
