title: Home Automation Dashboard

headerStyle: boxed

background:
  image: /images/house.jpeg
  blur: xs
  brightness: 90
  opacity: 60

logpath: /app/logs

layout:
  KNX:
    icon: mdi-home-automation-#FFFFFF
    style: row
    columns: 5

  Smart Home Integration:
    icon: mdi-devices-#FFFFFF
  Infrastructure:
    icon: mdi-server-#FFFFFF
  Networking:
    icon: mdi-network-#FFFFFF
  Data & AI:
    icon: mdi-auto-fix-#FFFFFF

  Observability:
    icon: mdi-chart-bar-stacked-#FFFFFF
  GitOps & Operations:
    icon: mdi-all-inclusive-#FFFFFF
  Security & Identity:
    icon: mdi-shield-lock-#FFFFFF
  Productivity:
    icon: mdi-list-status-#FFFFFF

providers:
  longhorn:
    url: http://longhorn-frontend.csi-block-storage-controller.svc.cluster.local
