apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: midea-nats-bridge-device-credentials
  namespace: midea-nats-bridge

spec:
  encryptedData:
    entfeuchter-kg5.key: AgB5xpebL/LM83VLqIPmCtJ4pfNwl6tp678Kj/rSMWMVil+dccbywbnrXoyzVq2YKx5RlaSFuxY1ezk8DoST5w9/nat073BgxmjisQXT5RyMyGFomoemBmnBcDSJGazA8Jb29wxIRo9jhWdqmhRlB0a8hNKrmpFhHwGPMf9DBzYgQHMKN9dPgGZpZECT5/AJxCdX7uve/VHggHm28HCOW6k8igTJAD2X5Qt4Y+Va5qUbxshVhsSlbrKJ3ScMD8v8ig+FNKtI2OEcOv78FmPNKqkyOpnwOiCBK+860K6Fhu7FEEZIXSNN/W8h+QBN2J45dFp+wLel/kzXIqokXGUeUnbhTLYViFd46Zyua7Bwmg7nO7V61lkElO8HP2cYycWYbshF73C2djl4sEN7Vagzp0H2zlf7m/kSWECzuQ9gELGVGDzf099CEheBxtsjEk9BnuoQhMO5aUa2C9GYN+TCnwTxL3NJVCD7Nfb+JnvciwGLvrTda+u7cRGfGs5iw1GkU7dp0jeIZe/6TT1o2UjvR42fTPyJ48CFZc4GpDNT2uwVwQOztSJVFsqdKsZsnNDpQlTSER4K3WpYPgdPd2Dr3fJiB0xPCQoQ5ExLrI9hmIQELuKNsWPW+8bJmZWf1fj4TO9o+LxrniMOa98Rr+2en9u3Rzs88et2GAmSnZNuhewWeLH7J/P27QnkPhl8u9fDDCs1h2OGevAo7bF5zZs7jjklW8M3cR7miqrxnUmqDaYBVJAj0WiylYjfmhS+JzlqP7JT6gSQ2DsLi9SnD5QIp2dA
    entfeuchter-kg5.token: AgAjd59TqtYA8Mzj3BjW6hDMKO/YKwhfr8xyGDWAwg+mNS2ZFmkJNRkqAA/TqmNRcB8Gn5hfXWyO3CgEHJ7LNDZI8yg2Shlm8Og5fcZcJidSH3AVZBuJ2dUciA5chhGJh0ciK3ApDQpoMb3DdH4q6Q4cMzIr7ZzDhVg/HIWB2yuS+790u1mD2Ez6UY2gAgE5Tqd1/+3FAxaCRjvYTN9naeW157JOPZ/Zn+Zo3LDhtE+JbLABXicgZKNcqZKkm35YmeC6n+k3tlrwQcWbsY4fh4O3LtWJyW/r+Y8/7F6vgEm7CPWidSXcAX/hdAiG3dv2oKv99ctoXGfET7SsBbxWlLR8hs2oRt1nfUYVd43eeCE9l1f1SFetOaeVtIopWVl+946xmjoKmNgKQ5hhPR9CSqGW6MuJ24qSzgCkyM+fTGDe92tPeCzS6N3nqmJIiUjloxpHhVwNQOgG4XloLLjK4f4ph6YS2Vg42jttdz6qpSzosFgxmBnrfzi4wAhgBT5D/BcDoBM1VQutNN74LkthBm0EjOVKaNuNvIyLYmP1XFZCxk+3SRMFmmNY/ghZUoJqeqlmpCJxrG9zYB468AxUxgW/2BAkb5T/EOm/M0gmb/uOVDN6W5oycsDk28A+7T5vWwqwJOnDADc5ibO0eQ6ijY3NYTIASyL1VM780igpc0YDOcGvDBoVHCdEFXej4keCypQ1SelcEiIgxcZwBtFjqAkYbj0CTGWGc6hKK5zqtAqohRM410XyznaVGp5W7D8DjUgNl0fYD1iDIUnC9rpxydnqnKGhpXxOecQrUgC3+aBQpXpyxhvIrhYGrZ7R3IDGzHwcAPiZPFk0p5nnKRcx0H8LNS7wp6J31N114r8cFG3a0Q==
  template:
    metadata:
      name: midea-nats-bridge-device-credentials
      namespace: midea-nats-bridge
    type: Opaque
