apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: midea-nats-bridge-device-credentials
  namespace: midea-nats-bridge

spec:
  encryptedData:
    hauswirtschaftsraum.key: AgBglZcsMI7f6yCmS6VEoiO0/zzWuACF6Ab2nFLhkBO8U0dZ3LHydO/WlxvKO8b4mNGkhnJmBstEV6HIkAXR/PM05IkW9ecix9LE5a74JGuHTqJcZzTWu8Se8QBNWd4+RVPddsUNQvwCyKsxU6/9rnPyDfFUFmksS1F1TjifI8lTkPFwFGA8BFT8AMsJ2F4QoZVKuKm7/5cRrxIrfV7lk7ybPeCIF1Zw4kqExNjrOJSrmhnAL+9yHvcLjSXU1F1yPV+90TFKlSV4/yzYjMQ/zDm3rLPAYZbNSw2UC1JmAJT5Q8rAeWUelGDTyxD8rbmet8YjHB2WK/4NP64+OSob03ByLKYfGYH7OEA7+StKN9qRcdR41XDPZOrYXz+3jKVBFiztLyiXVlyILY9LneC+OHrNITjaurVZcUBEzRghBrkQkyLkCoU4indtENnUZ48dvBH0Dqrs3gQ8AnVtEyyJefIvIIQ8VwphMTd0zbcUsaY+m+WcH3gEapirEdu7sDhNaBE5geltcfsDfvKPitNEF4qCqfTAaTVGrn1Xxp93UeHqHaFgx1cnx1DXnTG/ugZJrZ/pwNfP3MUjlggzs6aDl4nwmHN7URJDTAGaM33EfunRB2S5ZlJe0fzv2EzppOpbv0aryvx5wx2zK2FBz9bjv1Zd/+yqkdLJ7QeM7X87dDzdxBsuBRr5VL6CPiHL99Ky/lif55kDp1vUw1caHrfPWLj255MB/KtcisOko2ihGqe6QxxtBmB3QNX93lF+V7zsN0lFB7a9d8t8HZS/Ao44sxRf
    hauswirtschaftsraum.token: AgBAUB6hZaueVAoj0qpUOSEWDaIu2LmtQiu2MjF833V8gdHMqutNI5TYethW6pO6nz+mQjHCbXCbC1h63EFPiXcOpc0Q4C3PrQqOpV1fovjXmw2rANK3wrt57R76nyXT5ZITejLTQ2NzSIO/8y/vJZ10SosOHW1+nk0wqA9OPU6zc3CH7RIzQ1G7C0uxe2loIVyRkEio2+ATWwIiEdZhygL9ap+ELme6jUUxu0KaLp49XFBBE/xkktaFCsS6nnYwh7AHXx2GMFXrwHGBYzElpE4ZToTOkytIXZlyw8EIU1za7ZEoILv5ZzL70Fxj+8v6NZpb60QHMtKex9h+JzIQOHtaXitKiq16rGfslGmOoGLnrFk2D1tnHPCMfjcIAcvTeLhvRnWPs3+USNB5fXlYFHKuZOoAiRYlXJmGctLDirzthEEtYmxIw+KHcwWZUya51B71c1vVzW1ZJc948sK2MVu+iF8z8W7tz/NB1j9a6fI0LSbKptWoVRMrAkbJsiMetPNwFcz2qz6oKc5+B44QNGd1eOLe0q3+ATxF3VB4S0sGrT15Ooe9Z2TNvJhDde2eFbFQTe0s1uzbvUfgTjPPPIALFVnlnyX2r3UAvsaWSRV+skBZkYTdMEj3xJReIlRsHHqRGJY4UdJ2DnnV5nAFZP1zIsMqr+R62IXq3HhWkpj83jWMY3pev6dPfjj8X1j3LElFmIIuASB8OXMnJBSdbcgqieWiPPfNqblu5ixvc6ht5E13MBVH9rwjbPOuqKZ9iabT51EqYrrqbaueos/+/U46T6ELrpVuUh04D2iVLLPpUozvT8CSMVLDjZwghcP/hRwCQfKW0nQ1/OtuuZO6OgR9mAsGVj6Gd+9pO8cF4HdrLA==
  template:
    metadata:
      name: midea-nats-bridge-device-credentials
      namespace: midea-nats-bridge
    type: Opaque
