pve_node_core:
  pve-1:
    timezone: "Europe/Berlin"

    dns:
      servers: ["192.168.5.1", "1.1.1.1", "2606:4700:4700::1111"]
      search_domain: "zimmermann.eu.com"

    local_content_types: ["iso", "vztmpl", "snippets", "import"]

    repositories:
      no_subscription: false
      enterprise: true
      ceph: true
