apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: nats-auth-config
  namespace: nats

spec:
  encryptedData:
    auth.conf: AgBsRr+FhQQpDlRrkglh4oA80mukfD3sJmUIQRUcG3ihQulDMXOeIxNZguvTKuX9SMy5GNnmIlRcc4em6uRKC15dPlnQMMcojNCXolSGZOaQ5KZ9OYA8lPB/aSA8ZYMpkZrMNsWzpfP1tlCfNtp8tdfPle4DwMgRsqdEmBj2NVWxanNJEl54VUs4KbRH80F6e2uZeaEmbQRjUSTwaNBpwN9wNX+WZAGoSqe6GdzujrTMW+BntJqnAVz6LWmFgqIn8h5xJj3fwEU/fAwFFlQmcvg5KgaxOjtwYGRhCdfFXvcbGXjFMjwxPhaOkm+xPSwhfjEiANJt+zeiMgv2LR9j6FZcVy75el2IkwwjscMevl7tbLAHBZt0mcGQq68S0RoSXG8BfNEKJZ+0TJrf+SRfNvzP76X6vCXzc6Ru8psx8TdEPL14sfj8JjknBCoxUWNDTYJc8dCUsN1LaAgD7I4cYmPCtf2t1HGSZZoGA/QB7bthPSfdbeOM57zEUxe8yJkRK/i24MJf+f8RHLgou/J9nlD7c0UcT7sI6O6r1GzQqIGM7mMVj8fG0iS6APjuVpLz60IvkF2ttXk9qd2sVYpj7UJZMDX4vpwD5a4Sj88VLX+ApvgDD+N2GAsMn6ykX0GuN9uEdJI7Hnzvy8Dt59OeC9AK2F8DDAptg0Vm52q8NuoMZXLfNM+azW2KJQ2KWXwi11So3Z7cQI0SDSpsjQOv41VZ+S1K/OjKunsfr/TK/BweMF9Yki80mSyowp+ZqyllGc5o6jCMHecHyR1diexM5JKEhLYRZa8XiVCmikDAtLZZEuTby3bvLo1HNjeyGGV9YZMaBCFZnrw56FZ+9nLzlYHLEIPPMcHp1rg/pkOno4cEi/LIHq3O6WaVUROof/Q8SJGnt3IF0Ah9MW+5eoWe9zTvYegMd5bL/hJewrrYpJddsSiXOb2NNTomvEi+NRnHdPiOP6qGfZuYMj2+VisEivKnpXEqWtNjjwRBsWwBKgQIv8LwwFdpDKrskBvhBYpm0alZBbau2pxeXhzRH5Rjv906XPlYpsWFnKgoBs6SQ76pTxWyXcE0zcN1+rbhtI551iEgeyMIWgYx0MYGzkdzUQlrJ0XQgOuvHjbyfKJ7aol+XAx2U1axu2QUhtxo+f9FEPgPoY/sFkzklDhPc9OFl2W+XjEgwGABqL1ZRd+QMGgARtqgI6OC8Qwam6KV31dajjSfp/0cIao/UgdvlQ5QqO23FfxC3pi4NrfSpP8CeoYEYybaEAJKIQjVazXCzCIHJHMQrJ5K1UNHqr2UbkhG9OZ3hDUHYGJ99tmt3/10Ih/mxyHAhr2NIeDf5BJIbyNFTkEMWB/nZyaBT49j+NAoZXl4Uak1remPk7pnwvf7i7Kskw6/IIg/ZTlU5uoLH/ZQ08OAumhfn8sj8Wa1LowHBJVSyfPhsKW3TrKu6I61Da/aoLIO1VvKzg9ijwnlJGzOKfWUNEXvIjoFOYLVXMS2m/mbgSr9J0v3ntKZrNZCxKwcZTWa+qPE1vBkZ2p23ZlY8Urua/vrN/jEbWco1TOdR41hLlxFClbDn8qrtS29FK+aX+0cxqpl3KRfy37Lv0KvISIwLUNILYw6QcHMmov0sOBQRg4rxxMAN6LPoIlxGDmVHtBKL+P2sZELBus6bBO1KbKlll7pDX+8OZ6PiJ0OzbR7smq7R/7aWrysSgYURkeMtxpfZc0G0u+fv8MUAyX7VNE8ZJ+tE+66h7jHFDB7jM9zgZr3pHKWKOJvv2YQpqBncXUi4GVijUyaqluS7EqHtKAhmql8GkitCND7/TMiJ7hfRIZgcNRX46Fv0o9YLv2+iXnFyk5hmDhCfjU5hvT1bVBkyup7uMeXSui4j+2Kk4hKHCxngdU7LqKr88X0GYZTORJCn12bdk6pfJgAauM5KSbi+qp2zxCsJFvv7gotxjHQ/NMYsCG5lz1vyYZZOOvqnysaOgfHNLFJ+PG7YelYCyfpnTKHGCrLXkV9soiR65+DbSvUPFnrCbppgQuAtgHnUQxs1NXDFXuaA65czYKC/+FStpNj9vzneXmX+qvmkdBYQx74XFOuX+ymxLLa1OWTyYU5dW8i1PcGZYMJ1HM7nvFPrf/u0iP2yctXFT5nJVd4Xj9W77KzpCubFfXOXuSHnYOnIStYph011WqpptM1Ni4J3iXLmqu2vwEI9lonzIS+DwDjjJmuey5an+UJnN+dVSVFgu7GruP06RV1B5Xi0tSJT/cs0eT6vFKd6csrGAn+IuiPFbhOoubJZuMtczB72qQb4S5tD6PT8eZErAyU9FlrjXQjBJ3GoTRQPS59Mxu/jdwSPbfMD9FYuQG+a9KWzGK5SH3ScFZsgnwRR7Ys3m8wPeP4HmoQ0WBepwmWluFzLjpP8fayq0aBECxIKuwGtqYC6K1ibhGXg/0735uyJpz7/bz768XuHwBu3W8bY/YpOXZIwoaGsOHhrS2/+dKqKqdVxZFMWucBo1M/NweLlnAtHdBNWlRNYRhKQJjvY7ZPz9PzJsoAQ0OomvsLLyEVugOCTR6fqetF0urTorKY3QtkU9DDCmmzOJdW5fu2yo/rubuLc2YGHFixgPrUq5xlQ+GvFUYv5+y3K+XiNL5ff0F/XssSb14If94RDtO36hhWcMCv4LSl0sXh9WlX+MbRNqpYPrCnaPwmnOYobUlvIkq4TEALWXHjX8l2dlEQ8pbSPya7HGKyLSIAgdOnMFzydA6F0crON2JsVM7sDrV2LgRPp111dQKtGFDP40hTMZ5mpEpcsoEjTSfnLcmELtEH95XMTMi8BXL3HZP1+2dGGxylLARg4+ZLvxXFvz1ZbhGW6BtNwvyfoq8kC0kmJ/W4HT+WpjghKOUaeRrgEyB3JyNqQ5EWSR27gplgNCoXlETraJMQH0udsvTx3V699c1osBLrL8sN+/H7w5of0l3ZM8CZHxT4jrbJ8wJ8OqW3gAupx2tiGHWeZrrtF2A9/PfupKjAzg66w338yxBjGZr5qG9PbPSyOIEoJ1o72LRWr7o0+WA87jNEfK1gEDD+HcoHjKSgBS39zruRzXGna6zUNmoLLjGgYasd8xCos2xvQyE2p6QzbyDO0CDVWKPO1ZxSgvZbQpv97uTYta053VmPAlOMXxJwdU3Ulpda64W6IbnGcqHEyUnFN7MW293lHTT9N4nIZ4bf8QjRaTtFHP5o0KGNJ1Ij/Apsj+YZJ0DkaXx2bJT2Az9lvXlEzWH0MlhBA1cJx15wis0n09caa5R58dY0Fv6NFiG0JfDxW75MaT+m7pRFwNkJX8Yk/kDzvBeMeRijs/Gx04et3/YwXZ3WLSvPb4Wfb7SPQGpx6Lw607lNy/Ez6AwLzveDKlz+b0iUWO/SR6j3yfKJ/E/V9aqmT1JLqtup10c962IAdYrJz7Wrn7n9iN+waDoJ28swxCk6jPpKqlYwwLO2l6E3I7Fwo4mO1BceSZ/c9FzH/gto+uvnxAg36FEXbMwWaZSMVFV90Y4VIznfZKDANIKQuSnsq3WmxSszWoFCIZQ6++sL9iQKbBKZlM/c2G9VNZFgljElr4tpfVme+T4rP7/ypgpux2WR2PGiM6nKrABycS01lHrxZspgERtUXogGkPUg0Zs3Gza4mvs0LkvDJsnIbUDckkX5mabQ6kSa0FQZKFMhSlh+w1Hyn71gJ72Qk6+75vmmiayiQ1tBET7eowzGCV01zUmZpqCZ453h3qmAmUrGNa9auCkXJ19IrbSkWpfrmAu35faCPkFEYU4YU5/jPyXQqVLo8hfSghxuijYuFFUq8a9qdtk9DTccVPiYDY5VFCwRuFceU+0t26VEGTFCq7RVjxHPePSLkGOwF0ehUd2E7MQ5mYkYYAmMVU1ly9KISZBSabvQERK+eEYRSkbPc0gfYBFb+L1v8zg/PCAhjkHAF7xPsAGlqivghNXfNhyLG0MhywiTiAKYUOtYGd/yiNDVGBOu6fr+dgj+kcGlyWzE4v5/ite3h7TKkmdBoRo9drvkYlEEDsxVjqYldSCKyvR8FT4J6lM/QDc2rrdAuEXrqvSPP2VDM5xFf3nEJEnW2DKf1PHd8cUbvqIZsb62nT1hnBw9LW7DdAVLLzh13P451AIHrGUi6nfRcJgqKZMw72iHo/FkKVdmLyKHn2p4y+JyVy9DLzo8Wsc+gTtZ3Kw6N2nO8R1NxRDtH8JqkqAVdvHM1ckl9zGbEoJjTP3V+ih9XHdMYlOlEilvXQstqv0su2G2oobm8uqNR02v5LYlEF0ngL7N7Hm+hCvF9TnPVi9IUJAGgDN16Q1ZF3+YsyQ3ay+GoG0XB5R0efKRTp30GO93Cupbt1Zjwn1vkQbkuKmQBp7enWyzvLvLG2OO7d03kjTUTqupHScGRYzvlOwOKwZDXLMSnJJS9g6KsFbB6CuVbuBPcMbQP4ZIbPp7tTsxAA==
  template:
    metadata:
      name: nats-auth-config
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: solaredge2mqtt-credentials
  namespace: nats

spec:
  encryptedData:
    secrets.yml: AgAgl11GwHO0Jw8Xtvzcgr8+Qy/Bmr4nnBYOczD2R9GH/C+1Pg3D1MfWVPST2JNKNi0KcC95+VtmuIQVjwEJnguEYZJG8D9VSh60aTUXTMsy6+p697ngrp0XclyMI+6GffDA8xh7JhhdXuJ0CoV0UNhsVmiXB9BqeRWYqbyCF7+3vJ0uWvSMg1OIwKOEpkwsdL7p3l3URQpj7o4Wu9lvbStedIejhlk+teQ23pYRwOMv4s2H3OH0qWTI4+Q8kUUJFbOw4x89O84qeewTIjqksAgQMHQWvGT62kH/dbF4sk/CluLMPHuWMbd4/AG2NYfuoo/SkaU2zCxBj7V0Etk5wfh/i07+ATW7mNZQ/HQY/90BgeIimTxJNpDK9gHAomPHhv347fMrgMNwtMzIl4X9mBBxcUzXIvo+JlvWeDKA0nJbjmv2BMEVjdzaR6bdRQSHIm+gBxGlc8+siUCXdS9Ti1rWPrRG9T1q/qYFGLg+m3JiwlPTexYq/GuzH21/A2fO+b22+y0FgJgUl8wrus8GesgGP+7hCN+dlbMO86eZjDmbJEKvOPPyAqsqKai17F7HptpFOGYeGVqujSvE9qVO3JkCatiaszKKc5dwv3SyPoTU5fT2fHATQQWQHgb7wJfOZnR8tNfQp/fNyw3NWooXxliqA9cl5UWUmcP+9ubZFhozizg9HbpvbIEar/UWSxEiAVyhvWCLGSuKIjMbxAEDtdAznNYOudQeO+iYc2CufiPb1y2QqbB6pvShcvOJJppcTonHyEnd/7i5wOYoO5+ht7IckAxB1eU/F6P+4/39LVw7RB/t
  template:
    metadata:
      name: solaredge2mqtt-credentials
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: redpanda-connect-credentials
  namespace: nats

spec:
  encryptedData:
    NATS_PASSWORD: AgBaEe5z3cSciX3n+r8t9CVi2ssMNQLKw5Fh0X7n9hFpiz+GNks4xoCKz/RYzyFkatL4v2jLmsXYDG/0OqbmvU3mEg6W4hd1nBa7mkHCc8nrv9T02WbE0b2gdahrOEmAHzRzGddesIY9n2a2EJmEXNVcHEVfDPWx5UCXBzJYa/o9gYjtdpy91C6dl8D6Afkpuj4QCP1hnxhKqUJIrMl5VkzwskfWGU8T6enfuBscPyZSjt6ZfhwAloYpho/rxd8T1KcGuNwq+pTbNmyhWKwkKtg4ed5lIE9HBbJpeFXHjUMXY35LSQOj5tdPoOdWcZgBq23j93RowJmLmqGm6eTYonxtiK3JmT1b17swa3Vl6vtvERXWHhrcva0XapOQrIU1epiqI4/GkTEYs9o+nZSLo2+H2vmPiYL3Ysx2AlhNnEW32hIdh6LU+FJ9CuTSfN/rvg01aco3JJ1lH37FY6IQtKKcUT74jjcUC5ynrmH4vUca39hZcMSqjIU/jtJbT6Lo03hua2jpB76GZuzlB4Sc974m9VNVocLIKwxrivYF6MTi3lmdAYpLEUVNNJDoql4BVCJ91EoHJGIiwrDoN7qxpGOEHOHqD1uf+XEslChfMvJ6AvCjJU7yLQxd7w2nmzEI8/lMajf7iooIAvI6ZSbAwpij89GoQ/YVWt3Y8j/G7SH7e3oX9L60XTlTsGXQLUZlYh50rMBfIE+945fnhpONzBS8BOCW77q//MQ3e4PE/iXNXpbWaySqLPLbBtzlRCcJCay5kGbPMJhdFq1Ou6SBsPi/
  template:
    metadata:
      name: redpanda-connect-credentials
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: knx-nats-bridge-credentials
  namespace: nats

spec:
  encryptedData:
    nkey-seed: AgAkL6kWAzNsEj+7NvRW+gOpHiUSX/rUXB4XEkcjWfVXymKlwmz9U1XMp1+dllJePJL1bG4spo90YM+SKydnwzg6n/ndqb/IaSq7R8/puh0fdV7ecjG7NZyPQod1UUivmgdyfntqa0holjOnuaDC+OF8GTsR1ZpE3BVkB499m02icUTbRDt9rc1tXBIEqXQNTc0ddSYDYIWtPDAXl3p2NfzKqnzqlJmmRVblqThUcTt43wGLHEiZHUCwddZvDXd2rr/0EAktotEErTa27iBW7tKna0whczCkYd2wr6x+yPTZBr0k7hO5n3tj+CqccYHtI45tq0UkzQcsgGm01oQzWzX76VBv3GxQw1rP9YzOcP92IZ2jnFvDgIGPHAdON6PmKAuO0w9ciTpqoaRfAeiQo6j9I6WfaldeTDygS27LgXnl7jAsks6QIxTD37bRk8P9fArZUjrPQZsDB5DJ1uSFLNftlWIELLi45C27m2ZYM1wOr29Fk/BHGiJjerFTH1ijUoEI9I8x7U77SuPu7QqFoEyh+mtDpxVBffpYXo8H+IQwWn/paWScwsgrJNaJUA+IXS58Fm35VQ9fBq/Jizvhlqwod1QxINo+gc5AjaQFvEKDtM7GLTbe1PomVOgbE1B5dUIqbYkupJkqT45yfNwf7kYtoBZc6BxeAGqiQ4Kmm8134qNmUtWnrPpASB3fiBLCf6a5/MqQP1phuAMbY5znMa6lTpJ6mCDEXtTwfBNW/kRIrg1k1Kv0ylAkm1v1g2c0yyP7WlhRxKVn/yIc
  template:
    metadata:
      name: knx-nats-bridge-credentials
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: dyson-nats-bridge-credentials
  namespace: nats

spec:
  encryptedData:
    nkey-seed: AgCWU1nWCcsKNNbLsBUT87ucrmaelV5/KES2Na/UIu01MXN4TO5UH2EWqMmR5O91yA0iD4Q1tU/9VfQz34PjPbghzpevDFXS+Dlty5R1jhqW+fm7UDvrP8/tTmAClYotr0sYACitdhVuefyyxc9YceKen+jb+oGO1DrwrkDAoIkFaTRV3xtSFAfi3oFOFfnnlOwvEZb4GQte2KWyzIpKNzDWLtcFoY6//Lr1aCJu37xUbNM/USprnoEj8eLEjhwhRNqIU8uGzOUo1xZ06Sma/rwnNeCg9myhB0nJ95ZKc/5iScgwor61BdvmrQB76qgrh/AfhahK5kxFk7x+JQHjgjRj8MMnxgvzbSBA5ljcmg8pE+U/9S8E/WrRl0tjNv9wX7id+Eg2/ALY3tp5uelnq2TUYPO2uVeXWj4S92+k9EUXp1Rn0UFSlO5SZi5eua3e0mvV1bR07TFTwvG9LC2CrPM6Z59906E/9oGWe2kWzC3dM45wswCOuxSbiN0jn4qFgNAvtd2qEdDoBizdVj7Hb6KsnwOybIzFHuIlG8/6CdzUNbnoOfVUIS3pE2v91velSahHeQlpv3O54N1ak3kYQ3aXJv50qQytCzAqXM9amiNtpEuyMUN5qJjp3QHbg4vi3y6OzUc/pRroGVRRDJrtJwGmwR/cDkOSmYRPsQ9eVdnW3JNSndnp89QEEUD9rW8nP0GmXFspZ2lVqfOfV4qqFtL6m1XFG4eJuJhszqwefKY0PUBOshYD7Exkr9gLDbBk1Vz+/QAtnEyCKPVQ
  template:
    metadata:
      name: dyson-nats-bridge-credentials
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: iot-mcp-bridge-credentials
  namespace: nats

spec:
  encryptedData:
    nkey-seed: AgBbwlMFjV0r7TpjmcRs83ElfZuCij1sPkn/S1zllDoD8sbTB83cM6KNz7mi91bda01DMBgEx8LxThAlpHt1oByUbConK7JnH4HYJjyfAxz9iHCdW4X5RjMbFELXTdeQ5lmah8uL348+YW0bzlu+9DPPsDiRf0azU3LA0LjDbZkABNVkresJuLxWOKS3rfUf/jplW1Uf2+O8sBwFekRHQ8N5dKgUFe+Ff+fXORVBavuHXNMN3vqbhv9unRAqoYTQ8EcsJS35O3CPSGa+eXTc93AiiUSAqEuMPX+mdzDMLrHByYl09P/N2vosiAHZYhmxpZH47MDZG+g9g0UW41x6BsDdLoe6nTu4Q6pCjnoH3PnxpE7WEB/Pn9EZkFmhTWIYGXmzn9zE3bcwV+r/yKDljb4AaDucWcY2qoC1K5vOsMD2VmRFa/t2mNa+nLnhgyZMmYJFbrz1UX1bLpgyCwUekkurB+RfzF3lpdwKBVWz79zciHr0Xbn23+S8gWO4ZZpEY+uj13ILQ8t16v/v/wDicHp8p+sg4GS9aCSAVchufDX2TIppY/p6V4P3cVytpDzONgg+EMx6y9VzKfenlTE+gbT6LRU0KPmj73zlbv4yi7sl+yPA9RJA/dWB1VDQ9aUMWmJVsQwjdOAJfkp9iHckDEn3AvBGYpIzm9A6ErFNvg2gYz9/KCVQGPPUQnNGuQL2TQfY907/62/O9DV1rHLCVQDrhuRvyFb0UM7OIR5KQ4bXbryjgD3ASlr5gUVKmqcC8Yh9DZhk6I8R/aPw
  template:
    metadata:
      name: iot-mcp-bridge-credentials
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: iot-mcp-bridge-nats-credentials
  namespace: nats

spec:
  encryptedData:
    nkey-seed: AgBO192h53jrOwTJcegEeo06x5A5lNg4FBSRHOTHBj9KLexeAncgLVpEHIzVjZTFknN4rCijLYCEMVVfxA1jDoLxUMxcQOwebaOr0A1hdcTQk/KSKhvvcg6aRXlnrONjOXaoosL4/YJ9iFQGQvjB07reR90qCRUo/C28IN7FFtqF82+z7i2Zj0Vi3K/5LYdAATeUN2mFw7U33NkmSZxpWxU6dRweR33Op4k/Pl4mdpZluMaTfaPc3b8yLOr4KpKe4FKljP+jv0IAnNNtKL9kJUB+BBZODNM2S3PFWzmyK8R3ny6nQNfbbaTVUbfsjFXT1DOC9WkxxA8I1IREwiZy3++1jQApcng8EjU9CTRcgsfIdCpJR/E4E73tHtw4gWqeNxe6NMzNtA/Ym33DvlT1xHqNyL0ZDNRU3uBkrVUnBbg5JHS714QeodXIAzKL8X7LBrTLKdRCdBQeL0uCngGGgy0Kq6lv34AQ5mM2/8Z9htXSPNI50Q3ZyV1uT1rWv1Ng/stBxWfgAoHe3NsJVSFwqCnXBR9g0esXXcUGKqcM+7/iYshAh1GTW8jiiUFOZFTu10izK6MbgTJpUCyhrjiKyk4J0y2ypyoOr4dGxemg+3SRABYhJxETs1EdPOY/UQhPbscinix4FH6E7Auv0gDNb5OzetXk7DIZbDpw5PzOA5lKzuC6vwC0pLk3gOwVEx/fvKktXvkM8rnlLA9L2p5Pr2ZqVTn2qXANOinMuToYGxCCySu99jSv+7xmLn+uuP2TKPjdd0y33FNZaGgg
  template:
    metadata:
      name: iot-mcp-bridge-nats-credentials
      namespace: nats
    type: Opaque
