apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: nats-auth-config
  namespace: nats

spec:
  encryptedData:
    auth.conf: AgCNdxArmyHgQVp2s8ucfL1VuIzfFmnxNs2AbVc/GfjgMcPZATC2nTxjmJE39roF9KkPR/RuZs45D7rAVztkdAvCWCag3z15OESVr4my+gXjB4qWtF+0YGN24H2Ut5MF4meaeyPGxgCIszPKg84E9LlsjLjNDGSfPGs2IXXN5zczBXaf17zaKu8B7I0O5/UTkON5C9RnBHMZpolTYUKb493hXd64lpD27h7ciK4U3nYaY6kPPalI6OP+qqSO/YPuiM4fXOV+oaQsHYsRpLw25tc/qMR9Votz68tqdRFGBB49SjatsolQcHm4g2kNI6zerQmJu52y75RiNkaPzAiKWj3tGRp0gq1CvzpXNG3EDgepYpfNiGRHq4U4IIqfFMjbdaPyV3lbxIVMA+UTLzxgwxPNJid8k5xpEuSVcZ4/kMKzjgbTlT1Q4HcMYcVPfUotMPYqn+z3kIv5TnYceE4Eh3ukYbOzw/R+9mdyNeRaoHCFeMHD6R2ZoFEv/De8mAJnkWkuIzUk3crf/xshzC6AAMjCLKDYa+aKcFXJhmJhki9O+LZVUj1bfK7Pmg4GJYV8w7S/8xOIc+3yQrfGxsX4NwtorMjhxETLI9ryEepDAEsQXOrQxIAuSwUvgpmIdplgaR/2aig+1Wekp3XV4UMMhk/ugoHj01AixELJdXGpRyZ+GqIoz3XYHaWSY6+xIU/f6lPf5/EmacaeKSkmeTULJM0Cl0nGJNA9PL/EiUuzWK60hYvC3Q/n0dSkzWi0doe/FYH1fvcYuDAUmhAMwCQf5mVhDwKAFik4X+QxPPhCiNMa8W6XXQUDoDFJgr0OzigDqYymwc+Kx9NkeEVNlcvSto7KniuuAUrzQ97rRZkVgndReU2PJyQ4IPiM3CbsmVOMRwsCKUcjQ9CP800toUiQxPT3uuattdFc7c3+DWlHmM/JwdezorqFlSGyHD3wg2qs8fluF2X/2OpQ4umLBCzFVHMUnfvwDUC97tHI4NcXa5aveojinjw5AL2pDrnW/udsYmIgt7C6U7cf3SKvwa2+vo7VJ2zjXlzKllSRr65xox8ArwZwRG3IsdUXDuJ9QyARjsls60boAVFdya5jfrF3qqOmfQjhkAzER6zaad5tRo8OSAvqWqUVDqR9tWo3ZRGtt2w+hz4+xWmSDBSqH3yNYqGJryvlQfvEUTx9udmQokfV/hTN260N4690cCW58JP7cc8eobkOcHnkpRkB86XzGxNdpqpCID2jJlh+uUTIc4+QS5NBKg0DJabc4YR5nxkPAxo8phIIwko5SRyqiNcR72+yJ6n46VoXz4wXWYSxHN3yXo9zvFTDVZM7kNteMAQiPENonsUppCLOp7EBTTk2kPV6Lzotq/b/k+1YkCzAkyccQ/AXJSM+J0fwaw7Nkh0vsasyhVnRx03PVqoX7QKjvXSobiPK4AEzhxOYWwXhol0LE8LE6m0vAhz9LJb7lk9ermZbat6bosbAQjzQnRAuNYLoLU2faTNH3laTAwGDX0VCDhSe89ycYa9zvMWo6zry9mzGZsDUDYku+uS8uAzeqEXi7+tZgiwp2vhdk7+IMWFHyKX2oEp7AkuYAD01IW0ygY4ZYCYvTCFTcA3VQDDeH+UrJ7sQWQPJ/Zyoy+qs+QS3wTZpxSatkOxJl+8ZdN4JWhv18LtAhvWLU2eWIcZcitHcxC4b2jA4W8y5SFHjiqq0WvTcbEAdT7m7t3u4ERkXX8iAUXAumXzLUq8I4nAmqTHsA8AOuRElV2Nzd1xk++uuuD53Tq7GQKVtgaiI0SP2cp+o91tpTn6LEaGXtXgcQncfM8Agfl7URvLMuNXetklLz2w0X927HSFvs0MvPl+pZjaPYUMqHClVVuM431nDzb/f+KIzv61GRNK+fs/8BNPdaCxHYcvy/jqBrE6AtsBqWC+YF3ISa1gE1ZxhDJ33ER0xoQdWTnIn1S1VNuiuKzdfRAZBW/Fr0OLXfA+YIO4jFEdOxgwmIPX6zPyjuj3qahfU/4V4b+8raTAR9wKUXcOfpwjsJfBqMTmnXGDuA7sIOxki5txxZM8C7PkvbuAeIpsxllzdNIhIdeQl11AX9f6fmQ4s1jZZl3Btfgb6be8v0x7VA7+wwtrFUL2RuQjauIbImKrxaj6GdV0ecPzIV1Up8520t6bLcPkDwaPvOgIHknU8uKPrXr+XkXm/VEcifysMo6CJdDDsxsFOLQhnQSJSkjVoNCXtSn/fTsbmLjQ4LXFPtfkWtneeUNhDG26BKukn/sF9z3gJM8wVB0yIKwApilz6K9o6Xb8GdvKvDKOXw6jsdG1X0tD+W49afFGp2kLHwGV8ry0R9dkvAUBtLSL+kL9F+P8DisuLBw7vC3D8jgpytcU6EGqQJ58YlYiAqd6uniDkBLFXug2C0pJF1PX6NwlEs0FG6xEtNz8sYGggBjWOHIo2lt3sJCEwo3RAZBui01zgvnheRrJeVkQ2bp3rgGRTkKaoqNySeh+F0xTDtCTQ4WVcTY0RdPwUEMqLgZuScyfyaY2+vdQRVQneTjCZEwJP9lco8pBqmDBNnAiJsfj0z95e/kgEthOPD5FObzZZhumlohlzEYB3PJm35g1xO6jIuK8NAFicH1nACUdP4mkl6ghIM1u478dGHN5WzxaTKbFyO51RFx/gUXuUWcLh1FNzHX/hx0GbOy1uozK6qUSZ6tW75QzrAP/wEdb4A/Xm+NITdPY+864mdxM4c9+mGQOd+0jbzRx/SFnEWEjwYMOrGSJKOYbREG60K4qJqKLrWVx2v6y6TElVrV58O0OuRDQ+mXizX6n9SoVXO9bb7cN9YnhcGgAR+th84zAq1oiqyc3KXjtPgMOiaKt7rqRpSCH/ZZGGOozTl2SSEXtqAdC00LtCHN3+E2B/RnxxkswpXZpMHA3f2hGD6Nusd21QRc/CopdFBjvbyAJW+VFPD95MPseBzcUwb4mg1xKzdX/J+aDpPxF+D1F8zlGZbMUC78T/jTOI9z7xo5qzHsYcWeh9F2I+LRHuHmLopIcptePyhgvjOdI2TEeA400hGHGOXDNlMz5SGtSgGbVXKOD4X04KAkuKHA08z4yf6stcXSSiV0KCXMbzyWnpLOHJYgLqpwWwy6DWhn6U4gH3FknPWwh2JTGCQMis/iSNO5fzymxuLTOctcjM7GY2kaz4FXng3GsGLiAZ7yhTxaAsFgEK5K7V7z6IMtseaLQLJSC2z48UxBvyLRMprPVUCMk1VPmXxXVEi/MjE77MgQyPceRXgfa/fDAsv+sZZ7Cf4dq2It0OwT+fDeJzRbkre12gwECrp7Bo79JxmaHXQU2Fz7YeFvQ375g7WICsy9a9hMg/f3UU6nEARlacYDqV9g+faLVdxRkqQD0n/eRNJWnX4n1UHvNEz9h1TN/SvsyTxIAEUVRYsiBrVyOGFGU8iogyIlWakJxpg30jV6Yw/w8/5QV/80F9NIgPRpUoqdbDtQfsBXis3I4SGJHXSLiyuCcZRhXj45+ExTG3NAEWriTK1nt8JBnF1b72uB4B6UsbDas3RizRfgAL+qMsDBfM4/CGSlmmppuy/dWGXa2Y99RKwLz1ISJ/xZ6MTQMGMNUfqrQVETEdFY7bdiPa7F24ss11WhVCH1KdD9/VadD7IZcAeHTahHxq5Sz85I+49dTTXt1NOYmINx+Hygwf/4oymTUvB+7duVCNXbhCGzPM168YJH7V0OuCPPDM4F0wNjbFRPpGionTCNkiroDET/+oqqsxRTwV2QCMc9kUW9UA+1K5QSBNfBqmNr8NiGK6kHliGrnIJTOz1W2+6rsLhyIma3f6aRiB/BfTUAblxL2syWPNlBZA4goNWVdER7D51JYJUV7J6GQ6EA+e53laEsrZRNySD6GzjPgU5+IichRKLNbOp9wZ8odTB/3Y/ClmctCP7bOZLWwQrNQLLKBOtR8Fzu62O8kqn9THHQpEigCxPRzki62sLPdHLU/C2aL8EWMD1wQBIYs27J7Iw/PibnCZk1SRLIPFv55fn20IA7JzqK/t2ZqQevbqBngh3o3QYaSLZGYwRn7AbYtTStTYZCqATpvWKPM49vRlrFauENRz0Om1ZJa270eKT0FJ0wsK/hZ5N7GgZAc9fRXfrRiYMGC1rIIM0n2V6dVn5AtDLMGhFPb4SFjVTYnN+Utizk9bp6tKYaRCqWy7HDsnzYJdmjsonBN3gTMWW3rFBLo0ZTpz/kiBPyhv1p2e6SVa+rNBNvu6/mc/jSKdcFJNq9P3RumaxZdTwh7dXtg0Vak6ayam37RqYfPNFuSm30IIph6OSX3MFGU6gV2CEiAXG9bX94jd61AvDk1Fu048GRcwOEPvf7CjvR718Qz9lQy7CtUeN07l+k5GJ5L89WRud3+kyW3d0B3pykBp4Smj+9N5k0nBU8oztm3IJwW3ZxW8XT8AkcOXsl854vQd4XoMyJ86eErEn+TcsLjZFsB9JXlcSeuXt/EzCWILE47BI/DOQv5hvYU7v0XwSrNXHtQ4HQV7cKdO9wvXDrxVPgoKrrVVJb+C+mHhmk0DuSDNbZMfRgG92QL7aIRaQoP9bhP80GgySlgbSmYup8GmIXhfGK8EmedtCd+0k2B6WkWftjfOqi3Tw44nGSRLG7q8QfXypjUa6KNbNeHMhFrdKs83kUeEyBbOegn78EDQNcGk5qz9EZzQD1ZMDh72WKXpoNduWsxZiNWPPMaGYnR+S6dTU7ymtgRBIhepzViib+MsXutczQnKOwgRWoT/zrDI9yBN11FokrriAZa9PXu29Mr3uCMR1ZfNc37xcuY0K4sdTqPeqdI2giFh6SF9tMR8HMaNHzXm0bQZw9iEpna2Whlzx1zBgIAmhL2lOTHgLEUgY6deDBKScH/m64AoTC+sht/UMsPpkNAxjXCE8qA4sy2ZCzjs3bPS9rM4JGmqxmeA75tX05OnFn9xIOOPHONclHOlzFnzz///Q9DrL1EIe93caETfjoEBR4Lr+Rmb9N49pkfOzXbvpGVqzAwt80R8Ea+DJCaFoqFFspQYmdjsbf5wyckKm4tw6DNwo15AIdJjtUjQURDtqCJHa3xPFkk9ztrklzsmdZPvLhQAGXTpsyJwTPzlQzQohse586FMH3MehFCaaMIMD+AoTi88hsHL2N/W1Kux9unIetmWLaf+7ntF88KoMPGzLG5U5l4uO7A2JbcVpsmNeZoDwHaQ7RBweULTRxKLax78+clAVLBgNGLygiIUJAENu961OBl7/Eny2bbIK9d/HFwfagIbslGtVoTZ6xTOWg4FYDX7YxWvGlYuVd+sbBn2rs3x1mgAYY2GPNhrvh0UPUln8rYmaJGfOp7OnngA4iacuWQSKo1JSKMe++gftvEAKKNB4MQARyY7OAfD+XQJZE6RXqd1Zjevf6QRa1cAtxh8x5IggxpnBnchjE3Qx+cH8Uvzi/zp85lt3e6OF+RNkmiLWs/F/wAaNiv6ok+NxzevCY8lE31rZ0X2QTPjbGx7pGAblftAiytM4iucLklcauw5SkYeBDNL/E4/aA72NSYczkWvrWFapNTvXMFI71nI3PTL4acnpSo5fSGwhf7OHukwiYr1hmnjLNtYZ2WoclIJrYgMu+1hjqR/N4VqL7GCwg3KrdSp3NsTDMso1vYlGh2lCjRbIB71x+YJ5Qooccg3DYZdogEx/vfvY/9jmwnaYEEFIyPZl3VJhGAuH5qQLXgprlMAHS53QpUbe/8mtrQFM0zLPK/zGouOZOLUkGlrtDI1i7XVABvYj6XPeMxnDp3Rbv4pa7WtAEoHEuxNy+FpUvabrLh69HeHl0sNRg8CPF9NzKWquHgcocilqnfrVIeQtIF870GVK2XWsrXgV9fqcPkp2Q2rXWGENQMLt3XKpInS3tO9sIS46O1Rww+9XaTZGwEDHZlDz8m5maL02Y0UABxFahpw6L0Pal2/y2hMVojaS5tUnKrbO3js+0HNagx+zMO0DYYKa7ne8REJpKQclPH7KHsYSpxKOEm9breK18wQr6KJMA6vfghKwOoJ7zLAZgfPXF9WhEIv9UKDqHDsiCHNwni3CIPQmZ/ugr2bMfNUYWZFp+H5HGbL0ipRIj6QbtlxHiA6IbofuBeb3wEk0qahzf6Imqvjtb0kmQfgCGw6oaiML7Xv6qNWL+4d9g8nLGSMNbrWkmN3IdB5x2y/wObcnDl2DztfI9A+9d6ZadwOxU+lBXgfSMO3wIHldaCka1wi+q1nvfwtmq7zqg+Hnu4axR8x2VdYaF0Ux7hiuJbg4jMiOkgzPVd3PFGfw/xWEMApMZosDB1IPHCO9mssf04S+QcPAVIWMJvOeU0zmnqg1S+6kgMzk5Ijrd0WusWfmKmHl96xJNEoReHiEhSZq4qAJXYIf+oAKgJ7vI110TCLAtpEyaRQ4qjA2dTyjG14KEjFsBuagebCf7FBwjjMys2iVQcA3e/rdfWUspys1PxLqFs9gX8Xt45dn/NODWMXPhoYD41nQBeVcKdQFspS
  template:
    metadata:
      name: nats-auth-config
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: solaredge2mqtt-credentials
  namespace: nats

spec:
  encryptedData:
    secrets.yml: AgCBikujyAp9w4cDr46ECnb4MMgDSOSjw7N0KaY1dz+CWehyycjfiIGCbv69vc0sAELioVTQjGvtdJ9GRg3CH7hYYG4hUCC8J+IoNlxV95gALNabHA3VfLf6VKJTA8q5J9AEirQD1mh3RN6kTHBRhdJQmZqjjrLSDDy86XYMI+KkS7yV+cmtINeizMcZN69w3k31jRf/hsPfegStScs8vai43h8FcKZHrGfvsliaZi9VQBau8cjaxrdH/Cwzo07YK3hH6m/JXA2usrgRQg7P2U3QT8PvF18+s6DQXRoaew5odYcV0D8WhW3z2/LzFOlQSoA9AE7Ne27ME5iegGW+in2YJS3gXcu7LgVT0efFT+9Rz6zfvITzgRXNf0Ett6mND+Y1HAxKyWORlt9HGDI5SHgjyontpRx8LAb4He2FPmU5GLAMepm1BcY+AcWmwXF854kKYU325vEPF3Mq9AQLI2wHZWEjPjN6g5T2aV2uUaQ6BvyKd1FV4ugDzJPfcy66HLFCrBUunylsS3mwI4z+az05d6rrF4/duIy4wxA31Dgq9yUWOsUBiWdFb5UUhSazBkhHsWr/irj1rBhKDHyfRATFY4f//HR8jcDwf19UFTLGfRbMPCyE08XvIIIcKBgUkNWakk5HPOARgFh5MEvxe6XPyMffJFkeUrYbUkspszQFrpxEcx8a4ee1kDImOW1V36uLEt6Csp2hfdPD/pGhJMcJfqx+L1xq+UqoEiAdTpfXM2Gp/52U4Tlqbyk01cKiE/vEeHJ7BqDo1VcBgkuuNtRf2BzXxKtkeOSHc73wRxJiBIii
  template:
    metadata:
      name: solaredge2mqtt-credentials
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: redpanda-connect-credentials
  namespace: nats

spec:
  encryptedData:
    NATS_PASSWORD: AgBy19Cwh9BmPBh7On02CACNUH1uDI5KSZO71QFP5GF6zI++jGWeeyu9T+ZKTGA+DqKPGMNg8tRvvLnfUitMx1cGNaGs9M1XfS05GCMgBxHERP4JtbaPbox+W8gfp0uqcRPcjScbwdUVLkXgKkOgprW73kETJ8Ms6df7bgqnvZgEN4ttUi9uTR4zt342MdApX6rGiiAa95jFXs8tlh73KenzvymQvorRXpCGOXH+O2BLr+LGvRW/wEgb5CJxT1xB9a/SbwDWLJM9mihwJrf4Guo7OhPnTPoJM2/i1F7rWx9ENdLB1b2t5ReiIDLmDyTLZX6XTrdSp7Ne0FpjK4JZ2vBlkx+ctj60xP0MLy/qiioAO7DPig9nqf4cw/dYEWzUXTJi9QlRwiNvWctAsym+EdowFA9cYVD0n+Tgkaau/BTDcj7jx3ZtQCJIyDlSKCa0rlCnxUgMAK8LL9q7r4iq1BKudYQOZ8V4eGxNN0wofyKntHxB1bFXWRCZtzMnZRdPJeNYWQfzyyPmxug0JWg30x/RNzh9wiguPrglKqjPKns2GtWLvYNQvF/GQmxJ5XZZMwf+6HzLQWABYDH7pgyuM9v95workG7dGwnimlmTaysVvL7uO9RgfU5ee7PJGh3t4xX7U8/5LpjKL88f7oZ4m1HBWEpRJCfw6cr9rDbpySwpw3Iojtvwbt2AreILQkdlE25mFhV/nMz2eUhQM9SW4DqNfsHXE2z9x1JTCFt3ZiYuulzEz3qD5sSrMbAJtWpMo/vHZtMqqaPfIUe/v5VmAEpo
  template:
    metadata:
      name: redpanda-connect-credentials
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: knx-nats-bridge-credentials
  namespace: nats

spec:
  encryptedData:
    nkey-seed: AgBY5jPasNQNMKN5qi0J8HLO8friqIssdrmB20+GSxXmS1OgYS6grSVK60L21RVlC4BGYX7JBzL81PI9jCj/apkP+ij9kIRL2qeoKRAzmyL7C2zK2Z6TrcR8qJjBUGNnHu1vd2/OsnPAQNIINEjLHsZ4bAeuNo5VUWI8DMbh+yqKwrrarthXUKKvGm/1VgtBXz62kzMylGhKI63l51FyagffJbE+CsfSrmVNB+GmYsmb2pbQYRql6xt7rebUWYDoB/nl5ZTkxcm30gBGGKdgPszmbvS3ibtUPZVoBWewS1rLm415ZFBGZ/zxmfN36DdP62+gKAi/QBlSUz6XJlj6X0X2eEiJH0AMMqxwqe6KcBucSAmjiiJr6vnX3YtYEsxIzKYGBSrSt2kcX90/EJZoNuBcnOX19N8UT6V9ahHZS7t3REopdG+TvaIbvvYYz8Evx4eJ1610Y3QzP9WQATxKt/HnD1UZ7oYibfNarVXUP+16XQNPBJvq5inYpfRy757pdLWy7IacEx37qAcPQcYEepWJzBVdD16Js33CqmiFTouCSoJAo2mGzu4gVbXhoSrmC0RkJ4HHtp5/ZBLPoda9PfhDTHP2OXlZjohYQM2J3gvJ+QDBdpUEpisCZTpgCUTs7ySlmjg39e1v126PsO3xNKUwY95QNL0f9b3qbu/lLfxwoEg9/HYoshaJtSMF2HqB/C2iHtMqQCOAuBHH7tlq4c5ZVnaqYQF1y+NBbsbuwqcGUIMopkw6ERETOuNv1bz8XKARXJGW9IfljylX
  template:
    metadata:
      name: knx-nats-bridge-credentials
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: dyson-nats-bridge-credentials
  namespace: nats

spec:
  encryptedData:
    nkey-seed: AgCM7jtjops53W9trgqaYH8C6p/JCJioNrShaMZ9VQ+RV/Kuku+IVPbKI3DrjKcUNcQK53W1/6LhTEF6zxS/fH7+HkNBuygW3+cgVTlRzRWRJKeK0tBNku1y/ixF85KXBzPQ0e73TG3pnPOXtsri23EW9k9Jr1gOfnZ4MaocJqzsdUj7gnBgn8lWaTmn6MylOQUYrr0GN0kZNbiXoKGgkD7O3IhlsnucfK79nVX+XPBRJRnuKqbcpv2n5icnqr7G2D4Et1ZR3nGhkOONR6GgxGgr51LQXcO13sCLB/CU7souwhTaPzWyh45QMEnycDNLfT1C/drtc1oLgVO2w5TuDSN9QexaftRQAaXJlPsGs9CBBQP2yHp1o8cQgHthU3VAEVHlB/B8b9f7V/un8UjLDZllkAGMzkjfiYAY73+2iNLB9kAQ/R83nJI9KmkIOK++yh3lnFhkfX3GUGzXhs04Xlv6rVY2OgznTglWRxhwQwpNje8otUG9whBwHBAYgjKewGDURzyGOu68Po6FQsAJ+xiw1fBhwsuzfgjfNz7yry7pBvWFzWmktaZaJ5iZXHoT6AnBYKogLqgncTAYyLlC3BLME70CnddcChhsVRXEn8Tu2LEyyeJ8kGoBAVcqn8h8Xi/gmCgKDgoHDbR4WWMzPem38SH8qxP6wJdOvHOcNqB2kjkwJqceSEzqTI5On/nA1k1Jq32ROroVZBglJsTInEfGp3kBx1iAjNauZea7xjrYqefZ+HaNDSKDqNNvmyrDpejBVaOiNjg96XE/
  template:
    metadata:
      name: dyson-nats-bridge-credentials
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: midea-nats-bridge-credentials
  namespace: nats

spec:
  encryptedData:
    nkey-seed: AgBi2SF6zq73A5nRhEd7zv5cEq3uhHKZYejNoUeID3xDrp7yqX0rKvYU9omf2x4oCnCz+z6IjZl2zgQGA9yWgTw5eEvVH0cRO1Hsf4984BFB85DmJFglxCkDXxAZqmyzIVuoIntoKGCoFBR6bafAyfeI4tMKneu1k0FAAkhk0jDV0l3PKw/KDn3CZdf4Wb92RWtQVkq69S7SSbvnfOxMKqirnRTemjmxLRo4GIJEFQ5feZ7vZxymT47hik/cQpw+H9uEXDRK/I77WLzbpBk7ZW8G916mvlPjYpa6Neuu6X31YxeziWwk6QY4eA1z5p3K6L9mHcVeZDqZHZhomSTL2I5h0/lDydmpEhhzYlY3oZ6HOy7tpMSXOEEHl+DJT0236NWhBQFFyD5NS9a/VwtEddxJpepmtTJQiyr6rtVJMgoXHwBfLj1PfFvhLMZl/H78COjdnipx9OL32DvhXDBUGKFp3LV15rqNdk/Y2RGNLrNNAOezLV2nr3FBH7O6z++10ccJn6vHY+lD3e+cuDpZOVtewWgLF6edhYSd+80gyZOp6qRdFooUk+iul6AyYgYr/3wwRmiEqpjrOM7Los/GIODQy2noWGg1pUn8+24jySwjAAdY2LK1RdvzENRS6SzI1MczyLKHbrgVtvMwMEJsu7sQOXNlfAqDkLslETBcbzoYJuH9m9T2HxaXqjNJGsgMJJUBchmSigoOHEigWLXv47pmdlEHZtspy/rAfCEg0Y+W71lqSn7I3pa6oKM7PenhByPzYEPEVh2rLoPm
  template:
    metadata:
      name: midea-nats-bridge-credentials
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: miele-nats-bridge-credentials
  namespace: nats

spec:
  encryptedData:
    nkey-seed: AgCZkIg1Z1rOgNmReWi83rtLIP/n28FvmR7xjmahOz3Sn+b6oAfYvFL0ncw/o/W/qQhHA8/LQm3s5kYccr6aSuvq4GhjHaZnJc+DCTeAEuiaGf5QXDAoF4stbkjzQ3BRu1DjL6JqPS+UBGJFitHcOjX5CV9wFOcjOI3YSmDRZDuNPb9GQ8caciVlGFmFa3AdXPAcLlgPvQw4gepybD6z+SAsCXDKroJySfMh9EzAYS/aqJQ+l17yK0bXvm6Uafl2yI+lpVvfl7HnW4Za8di2VLBZ3TdF+a51mYPOES9fcAao7rr9IocdlsOxDKAnReqgdiUeFwUJDy5t5n1o7/6z/Thc2Cnwobyuy19oODSwj3b2kz4kQZnCZ435QS1/4FTPVlBfTlxjQdHeqnJqhA/mdgim3JVENZ6FV1tF8BnwLDMFLyhAAjdpGDDvGX4T1XI9JrPB198nMZzusdEvvogEYAQyBLpyuwdtZufl14vZ6ntVqysDbqvD2TiQ8QpMOMpNxNNNFaK3FMQ5MkUElTaHDWE4y7hPi3dXYXXyfjIUjuSBWIJyB7zQ0GuZQBfnRiCtfL6CZCFuJfu4E3w+WNbGyF0VVsKx6J0Rx0M8JvA6klHCSheV0JjeO9fiY6xORFxD0ybXqF1+Ix4YO0N8YALPmtSv9pmpABY/c40MJ/kAOYvJG5hnLdZmbTWUqAkGGfFS958Zm0Dp06Kafk7jWbdhN+JJ947GQGrN1kQp2HEsAoGwBi5fUC3ta8NP+6QWgQ+uPP+/3lv4KByg3Ghs
  template:
    metadata:
      name: miele-nats-bridge-credentials
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: iot-mcp-bridge-credentials
  namespace: nats

spec:
  encryptedData:
    nkey-seed: AgAtCINv8PEDqEA4iQ4fdAxgQLU7oJl93QemsfMjoON6xkHEV34AGKga/uWSNFv68y052DPWK1of0G8Hx5s+rHAlQorhX/3TtoPv0NyQWIrc/NKLA/DfVHJzJmg/eDFNyCwDL+WaTB/PlIa4Y/ECWcsxstdmduJVhOnR9ME5gfyhVnqdtD2oRPNex1VVmD/6xNxBTPbWZ2pDiCSiltarErcWKZQPk2HUgym3bOGLTqnJAYETBvcz4UgGRbZdNDZwDqfkXo1pkFh6BgvHdBWAyKG0Zr0lw5zTUbqIS7zTVZUemZPt9k0kAUW4KS+4PxWM6l1eQsAHPOyYw3C3iefGiSizAk2x+bn8P14TtvuT65XDn8rmuyxfbVpZP8gHbV/NddeoQKsnESzZZ2y1KvymIX9LsuyHFZzFglFwXS2mAWhwnec9wYaUsn55b0e0P2pJceWH8Jk3chYMoJGwlZk+LSSr0o/OGI4cgVY0W8WosDfAEW5QLUkNMXPQ0qOKayj4Em0jBz06eKeYQof7ddcNxFfSzXqJLzu55Hh22lZYlpRYNaNiEChHl6/U1iSeavNd2bFpTiQECxBEY3t0fovhqRROOs6kYlScx4K2J6lVf7os3z67gTYLqFx7l4wP0qxeU87yl3KxjR8zybROX6c26uChp7OxPjOCuVnS4UzR3rPNeA68rHHMpGGTUkw61RlsNJCZVbM3BC5r11leBseMkNHbjhZROFer7gPGREBXCg+nVrsN9tgMj7Ue17lIQduqa2LhUWcdxBLV63FO
  template:
    metadata:
      name: iot-mcp-bridge-credentials
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: iot-mcp-bridge-nats-credentials
  namespace: nats

spec:
  encryptedData:
    nkey-seed: AgAKxE0dcxg2g+PyoeI7cfnr775PcuyL18upilTmprZZuOdmS91bt+pWh/2alVMh0vozio8Ow9FcDZc9C9SdYCQL5B1jB3Knqovb2E4Ml3iA6/pCpYk5fliBZn998WhH8FG1C7Yb5q13n5NeTinJH4SeyLRusEoBvQdhY93VG6fVD4suIQbItbTdt4Iap5Qf3YEpIx5X4mvF05/js785du423KJPpreRKOsoI5M4j9TFIPeBv7OeO6cctwgzWoTdtR0wacVwEhvGRyUVCxLSrA8aKlSSRnAGY1L2GslQ8jNld5wNjHJiRMJJo4lNyP2RJjuB8oLRdlj7wpb9O/jiuB3eQEtC2PhuMzfAVOAVkSV9vueLXDLg6uLp3Qw6AnEun0l11PD3694etdAIusaU09tkzPZC+NuU5I3ZbgGvMtnbquAFpuh3G3dJCpGTdHK6OIf1eVcouzD6FusNO+i+Sl6by7AU9qIfef0dQDwJwWMFuyRHBFqZ4uxjyGCpLlYj7H6SFJw7IDwa4b5Mqt8fXIVM/q6idQwfheG2rz1wSZIKrrubIfHdeEEdUhX3743ounyA32PoJ6iZzASWpLHYlWhmSaDaRcpxxSfxxgG5UVpRwrpQyJN2LDjUOl5/MfDfjx3fnJ2TsvfXfYHpfMCBOzvTxrhy1Fbc6uuE4sPVn0Q+5wfO570KPTXRZmafPSRyUuorPDsqFAPBHP0OAFl7WX2nk14TlwhNtnHUdYHVPUvkRQxJ9yIVsIEP8BMxZ90RxhVADkrcYarVWD1+
  template:
    metadata:
      name: iot-mcp-bridge-nats-credentials
      namespace: nats
    type: Opaque
