apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: nats-auth-config
  namespace: nats

spec:
  encryptedData:
    auth.conf: AgAdzMY6uOAJdrTqTtlxkUJGzduDcKgg6BLI5yYPn6Vd5pIhfFD0u9KD2118KvELAOiv7H1LLihmDp1SWZqIRrcKUwiYZIkLxOLUEYJ+mN3xxqm3Sbv4vOB5FiuumQgzg1m3KFeWDFT8vycmbeKtdxvw45HkCJIzlZI9jU9bAV6KNjEr7JNOdMrTxqdhJf8+8L9mughGqAElfaTYSWUE0dQ5LCRuPSxeegExVQ8R3wrlq9JHi9PwUK6JrjjJS1rqgCLMXL9yFIlEv7VGUtOW9aWMomZOUBn0P5k9F9HgEvp9YlVFYpjTEF/gYO93FY3Lygc2XSW2PGhhsP/ByuQYLZOlsXkBVCCJuDb2VYbjUncFlKFd3d/TVRdTU60qfSkhyhusakYT1P9lpaxH42HJAt4pDzkHNmd885BaiHXGcjwwxR9BtEP/d7H3uAi4P+klrjIAZGaGKq3K8km6Rt7O+vyHhH2DPftStEgh6BfHvRJPTTfEf+1zuWCtQLEvpf9uCSgAnBFhl9kvZRCmU5Ck0pQ9Z8pgQAplkmWSUuG7kp9hXUlt94FvMqMYA/Au4wior53H6YxIx0oVZG9GoLApaIMRbT4mCMm74QMeTXVGaLPCPguG3s8WFK7gvt2tCK5Trsb9R7LX7k5xUum6u7CCAOapsuHDRO+30zPGuaIRwlKYKtr+VqcGFoi7LynLdz+pXzcBiPR8zcmodVMINsbOOwVmogxx9ttRnDxnaF0lbI8jz+yCEk03+KP8BhhVwJFBnkqczf2TKRwS2T5Pngk5+SgRsB0mZBNgJxRm+B8MsAP27pJWpIRLHHy2tQ++rIqEV8ezo0Kkr5CDtRPyY8GmqyZlbaf8OZDouRxtMqAz08P/+uEX3cAOAZx9wWOORwHbCod9z57s92fJAxwIcph7Vegw8bMvQe/9qAzm5oWs5F34elCHjC5q4Fwln0hYUtR8jHebF3g85aGIdBExYSRZshyZf7CnOZ1PSK0ngqsw/SfaT8uDVRbTA4WHdyb28Wq6oZrRVlNxD5oAmDPr+7XAz74j2xjEiNSzxH18fqFuVxRFZ/b6IkKvVrgOkvmt+pvH6pNyswZhW/E7rzhqteut194QmBcy1s/kgCKQW35n4I4ozLu4Aar4Y7i3/n+e7r5WGkp4zRRA+EuSpVyGqMnyakjJV9AuFDcVf/8MnoB3qxJm6QuKr94PJug+L0SBjLWxfSSteNQfksqDds45Tr+nTfDgKCHiiGBQ+x6xaT43uSvJWpJfk/xlVVbDdB+Ohqfm71buPIRNoTx4ZYdU6wa9rYwML246c/LEZ+rWITKsdBP8Sqjw+td8sLsST5l7FVpfxnVexmsH+xRIUgmlPj1bgx3gNmASIx+sSqRtrxH3Ona4cNP44GRZ0sLSY9OAOd7C1OoFaOUsxAaPIg62yl4yUlZCxB3ewQYyDPmcFL3O3twLfOHOeyoWqK06hq62gFMXTH9J8AuU3X5/+sTxjF3qZwi23AfTB/fTbrXBmnW0xuD5N+S+WzjNidxt5bygvwU7vsZ3xrblZRC+cZmd7VPwWjHlkdyn+2XKzh7LMJbMVxDV/PpwLTdtHMYgmjM41XJC1IqWPYjYJq5z8uiD/vcEMbn2UriAt8P0k4nW28gcrddm+lT0oQR7S5q2IHHulN7v0TbZI1ZvVdlk4Xf0TIJ84UKVq54aSXBG9CsHtzD03ub0vx4PsZ1WSArmANnIiIuu5crbJSb7wL35Vt7JNlECv1Aa5d+Xe4+qjcoTHCLc88X2IQh/N4y87ZURqF3VuqUBrQ4jDYtzwtc/iVRKnhtMixmYLM+MbuWfx7HMVbL3TqjA/XFRTdzlANVSbiYpA3tYo/bDiPMPN+kTd6jWr8S5pkJwhw5st2Zvv9bcw0xlkKqml+oZKr/g1oO3fC6LTWPmV0A1R5ghSTS4dzggW5syJQuzmseVVRrVeUMnKZGe8EaiyXPgmVj4El5JmWSGgh0O92shcsor6G+UrsiDdlve6taSKmCxW30Fyin6S5Wv1+d02w00rX5u6f/XYhhuR/DyQOLLqja+1qz/JBeXKf2nj3/1KdQPD5S3A1jtGsMmtpGFy+vxZ9F23W/meo/wECgw9cF81l9obCEGDakhTjQlAwv2/iCmIUCM7Hi7DB/yzko+upjOrtCJRMuCSm93NmSo8KULBPDg6SE/ds+0fWc53xQ9bgmY9ZjLXFcYAVzJRUAKM43oMPUzpimCmxfTfkBwwkhVeNR3phYu0jTBxl05iuB3djWt7eydHi3rzgF4/HUce5dIFuOyFLbcWnPKa9nzNgdXYkCjP80G9m2E8jVvV5u/zw1WFxhjcgrkWqDstonQ5XFXao+mccEHbnMc6H4xvs1G4r71BCTS75SPlX5vsNe89IDYtFz0y9qMS0A9sJmFcddzGMNU8bEIAw8Jvqrqfdqx491cWoYuAJsJ0sSEwxMK9Gn743yBHH+zLUpfvxi+QuevtyO/kzX+hgBi6nAPax3cOxsMgnyY7SqoAhk4LvYqWfhvCU84K9uIZl/85g5c2lrJ6d7U7aUF+wrBaY4eH1dB7u+Y94N2+BkqZ8Rq5gybdGLAOZXPSnvel4VJ0d0fF7s1GV7/+omP+6U8qzXK50xY6bDim46ypvhaaK8z1Fa9c46LwjDExMzsxGXmVEGM+cskmSkEANqwOgxQfGC9iMCYVjz8jt87Bo3bhiPBRMXGBYU/KYeywHyDoA0SO7n/TpySojPo6Rv6LQFBipyunAxFYARHsVsEJSxURwqurFacSSSPqeVyl0YULnlRCTBfwfpvjDMF8VbE0u4GIol9R7yVr3ny+bhADbHPBsITX2Rh/VphD6UIRE5zwpSE9bpNwkmUBdyA94O7NwsZCMEyFVNpdxzj1JCg0ZMniGqc4MlLxAZIk+l/H6WPUEzRxq8e9yTKUSZPrPJPY5oBTN6xchmpdWPfhG63vU9k6rCbP6jFvwaocwMT4vyhP43SP5tYnXUq6rX6GTBks78Wn0wFehs6G4Q8gz+bglYRccEKBD8hcnkmDIt+bVBCgGqT1OowNak9BBdiEzQ8tijtq/GHTZMS7vuh16bKSEfqopmOrKUnLnM2EQsooojrwd/zaZcJ8ja4AvJ9DskvCTtP8ugFDJ9kM9O+H+iA0TnJZLEFUGX3PHR5+VA/hcWBpK8fLbDbBxrXtHHmXPNculQvJtp4KTmjA9YMwuZxivy9NBYxil0vfp9dS9b0qL1ii4jc2wrR62/XKGukdmYS2+81OBZ9GIBsorNUoQ6TuYQTu3tC5UU79s65Q0ma7RN/htc2MD4KkohvVjxddabC9eOFoY708Vt/rgiuEJsdXcobImr9nm9DcAfo6yS3HWoUH0x/EqTCiBnSfzYRMM1R9P2orxZA2XCWXeFKbzt4Ft/1aK1t3SLXhyXwlGwjRAUVuQ+g0mLZf8FbKkQGvCVPNQPhlLP3sWD5LHf/2G47BQ46oiii34W3nAhNNuWZ2xQE0hBysTbqH8SzujDoiCzDpThCnKMQeWBWNrVSiEvO6AiTF8QdxgWEMvx9EE1REVs8B+jCfMYwUBYrB/lUje0mEDToKaCBPNtLu6aSAjhjAmRE+mnUdSRYv3V8di+BK6d05ZGTXWC5ErunLunsJBHux6BMTSq+1rk7GgKl8IvsShwAPjU+FttUlCgm96d6HsE8lQJfBkPjaKyt/N91Vu3QwUmoYTWv43H4BO09YMSZT0zB4Q1oCM0FanitF4vRIFFBerBI0But5B8Cjdvt+LeMG+XbclnGnFmQfYeDNb1OC4+ZGD+fZj+ZcWfgiuRuDRQDRqpJgEAmN9swnblVmKbkOYKZaqO9z5oi42lLCpNpvTt4C+kn2Ne3ZK2A5/rAzXQEIywNOfivZJMAS+hRj8woidDijXXu1aNsRwqo0uU=
  template:
    metadata:
      name: nats-auth-config
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: solaredge2mqtt-credentials
  namespace: nats

spec:
  encryptedData:
    secrets.yml: AgAj0+neAF56UYRfjGkQBLHoQGLJG2bQ/Xt6ppK0EoLuxp6J5amAOmQTjxhBZZUQQ58PTBPBlm0aFco7ollk3RtoXw5Rc3RAovFHh6LrmLMdWFJpGFySQkLvP5b5K88AzOXJ+CkkjYOo88YURoUZUQOkiOvAFl3n+iAx/HU1WLkyDXZk2kL83mzJarxdPvjuGIRXIS9Bz5lLRO4UyLNBWJt3louTYq0BNfVQZvbG9Wu+Fan5gYL5QO5qos/o0E9h2ps6FVf4R0hfUWTBbzyumE08W+dQp919WHyJsNZLb1hKG1/LQS4JvdzCge38PL7S49wrG3EWB1DB5BBQaF3EmUeWKSdlOFxFqJWZeVxwS2LWj6UnnxqYL1DJ2STwUiiQ/DnEXnclqsMtVkWwdFX8+kG5lSy8JFfSTlPdAqFj1l58kAUNUJ6P42V4ZpUstD8FY85Eim5NhWso5iLqal82Gd4HTFH37zJF/noe1wrx5rtabbuJgmdAKdq7X/nr4W9+wIgK/FKWLEtwnw85SG7uJ0Rr2DMdBZRReLx1M9H0xeTN+ahE5E5Y6JjDyQewlfxXvKJrk51bXZ5AEKt0Lk9IqVOLbixFUl0TG4zKZKxP7H6VH9YYB4pPeSxbHnrle3AMwG8UE17DrlNLp2wHMrahyT0hZ0kd4hTGSpC4MDAROrwDea324P8e2OILAmi9SnHI1UxkiZhrOeyCt/tOVNesvnSrL7E9mVFrhdB6nH9DX3r7zazO8WbpMaeRXXcGoXkFkFexBzu1e5IKBllEaEHKbmNQkvPsF5ZFO27iP81WJqfhSbJa
  template:
    metadata:
      name: solaredge2mqtt-credentials
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: redpanda-connect-credentials
  namespace: nats

spec:
  encryptedData:
    NATS_PASSWORD: AgBbmqOzGnq8pfPTJCd/Rv7emFUrbsG+m6o0VJZn+slu9eSllwh+qUaw6v7e6VxHK6QAKkdPG0246usELXynSiGTQ9xLX+OnpZFl3jbEpQMmOo9vgYfwialmfp8eKLhtG8CXFGMAPcLtgWf75yYoYGQrO3U+WUJkZTxStX7VpkMo4m2B4oR6dNY58sra1xJLMeYx7NN84Shn9CHzgjiDJ76sCGjJB1qo0MTN49bV6kTSL4SbvZNRtbCYknvGqnV/L6h2x0DxSeikyEnWVZaADDIQsb7mfMm1WYOTa+WFo9LVVMjvq+FkH+ojnobvd4QrvjCpr10JjpODSdN0Ek6xVm85qmOehqPnUlw+mWBj1bTC16hJeh9+6Av8TTf3HB6zW1vo3SohxF5np6zlFjr52/dA+VAItHV0VW2vLkbT7+YDVxEe91VLYeg8hmSpNMA9UdQx3sdYd87iNPt2NMfAsv+Wl86K6vcvfgw1+FgwAvEEiXXs2GkxWZNfPBAk2aWygp+RNrExGoMU3ZKjJwqdA8pNfHtByDLnvJTDgC3KU7SgzTxtuuWECLsIYiHZS/4aMgISKLAFJ9JrO07atpCAuhCptPq1PYR4cQ+kg8QMHVlVELOAiAJpjrtK6tbjK61ieA0HpllSGk8SiHA5Twx5tHj3rl4vjqz1I/dZFemKUKw2Z07KTDJ9Y2UuDQZcrKhAtLWKBCAbpVD+V88ztXPyaVsJNa0S4QVrYHG6mcIjQAnu7Wi2gFieDQjsbpEz/6//DW5QHUkLm20CMI4r0qIBLVGe
  template:
    metadata:
      name: redpanda-connect-credentials
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: knx-nats-bridge-credentials
  namespace: nats

spec:
  encryptedData:
    nkey-seed: AgBhk+fpmJcouN8AB3ibcP5FDQ8vSMsyRjFQfzVv7nKzyOg6QRgTe+B47T3Dx0bns4x45ueoIoqzYfHjp58gCqrE268bLUrR4kur4i67a7htx2Uaovi90rccm9Z2ZLkvbSvCNnX8jcsTOY+8lE2KlqpVHQCCU2zLuTdjskgbE7XYOSXXvp+CKeCdYLqqDIXHPmyCBJJz47iconfTITEyp6Ld9m9R6/RdetYsDdsihBxBvRBzcN7E3g5SCj7IL39B4hs0mCn8e8f257TsMlroABEDu5Wjla/ZdooiSa2/oEFhRfEtXRcinuqLpRsBVjED768TToj6rWKUzmYhXBHDiLN+juoA+MMmB4oqtZwo3Zjoo6FASUiHVKHoiicx/o+Nw9wUt/NOEgw9KYBt7CdgSh5UFo/saStn8guIO5k5qGVpypLsbzDJx/D5AV4X8/FEASNoiJ+W6bUyqi43SLxVsIhPOfLRWRZdFjpfBGJGqbAFWbog3xKPlPJu/+HYISmgmCF1RPIrRfaGSzmwYSi8ELFDWbCpYp8PsqMpWaAogIEStbJzE7WUmh4HuTM9BW6t9SRJ2c45P5NAO3WZsjZxnlSt7ko0HhHUXSVxcHYnTEPdy/98l4j2y/C8uj28+FooYZolod9xsOok3CY8dGGVOZpb7jHq0QFl5jMGZmO1NW01Ht0DEts0bWADUwOxA9AYfnfEm9/DO3u/JNl/FG2oTFSIqk9nB8f1eWGmxZYWKBf3efX+S7R8To8cqHfb/HGTLZCuQxoOrNOU39X/
  template:
    metadata:
      name: knx-nats-bridge-credentials
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: iot-mcp-bridge-credentials
  namespace: nats

spec:
  encryptedData:
    nkey-seed: AgAqPsxt1wbmP7CSStjKh46kgI0fHvI7p/KqqGoZmk6MYUtxCKpNXJdj4OSft7j+Xb/FXdZUfxEazyaaTKxUjhjjIrA2K01AY89afKGRXkp6bTXAlPLpE+xwrY7uBWt4xHS8TtQi+x83xvFD1dGbonhvigoHDcv230c8jK8DHkClS6hPB4KRPzjUM/6Ft5xi8IJ9/fsOVq3byicaDB9J0KVra8oZGpJ4JjqYY6lBWS6r32zyPSBsoFD4C3XxYcUtsSVbejRuvyG5jjQdkPj17BlYSp/N/56KFCD+m+IWWmoGUsa+s6JO9u9Kgw0gyDBlWpQ79ibgND87vsBVJ175vjwcCWgZ65/P6hmfY1RSN4a5tgT0bejNxr+o9uPhmtf52f5H4GTHx6lMEKH5LPyGTHlYneCxJPCydo6mjIODlf9zieEp+v5QqAzrH9y701QbhTH6z4U8KIDaa7MkxnUkVTdPABc5gLMMIOthdg/rdolKWd1Ojw34GGU6/M/A5tRuuI3MP643xnUq2TvN7zEO4725E2lpqh0iiCuojS+dsVNyx65WT/wFJBuVaMaZlmqNyYpvVQA4an8acOWIelcGP0kT5bcQ7fACeIWHnap6VYlY7oY7H/OCPA3pcpSNAm7p2jReM3EKG+/14V4SwT8pfseuXz/b+cbuKtdWKvf7x2JLcuUFAgLytWDTRuIzVaH6bRDcFN5uoF6CheZ4YUZUpMBKS7CXLnAbd++E5fD2gqsBe00JqlRy+8sA0+5OYuMWM2lSi3OyJqNuWb9v
  template:
    metadata:
      name: iot-mcp-bridge-credentials
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: iot-mcp-bridge-nats-credentials
  namespace: nats

spec:
  encryptedData:
    nkey-seed: AgCPyJ8E0OexohNccR43gT7aHjyNmYG7BYSXxQK9+7fZXGwY3tTJUJGnHdLxb4oTODB4olwGhLzMAIa1B2DLok/rLDgF5+qOL124ET8qJB5k6YeH1Z7dXydAWiDiJsdRTImM3HP6SgqPyv0QX1q/NuwjVJd3KDxKLLM1emQOEn++FvTgbFuEDBPOURkRDY8VkJqvMJJlshyziv/e/fsEIjSjybU5jHEX3opSu+8iPJP7XCoOuq09jDwX3f82UGmyT+4VPeNaLaNLws4F1BktXiy30Kq2mfTklFMqKvOIyjvYYv+T3ZPgy6I2MUtTa82vUut3HELMbRU1sfmIa761/paUTH8lRYpoEDJSvc1Kdd2ipM3MgO4d4ECwMEPWWImPQ2E8BoHCtLdkAyQLAkcTsIEA38anzKTzWtWw7oiULG/A/kfQhcTfrpNdZCOsMCgOSM97wwELB73OAIbX7aBNaQjDtqcUx/AB9p/wq9X7X+N0IPzk1kQbw42uevGp67UqYjZjQVZ45OgAMCh49sJMezWZcCqwwo6D4Kzes+tBf6C6ZeJ7BHVwWOQFl5ycyvxXHqyr2nXtgJWU0y/6Eb+E030yLddVrlH+M9apzN9m4c6wlFRp/GOEy14aKY9JxJ2MJJy4TpgO6nVn7kBTC9eXkv/2bD3ycYVruhXN5m99AKUUeQ+Hz+qTA2Ja8Tp4GX46jZ/9F7KMmEAlMqQ9wFOWzKl+AQMQDo8y7ePtkGLAcD94C7zx+Yc0IH7aTNlBkptdI8cE/wy7fs10Dma1
  template:
    metadata:
      name: iot-mcp-bridge-nats-credentials
      namespace: nats
    type: Opaque
