apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik
resources:
  - ./namespace.yaml
  - ./database.yaml
  - ./ingress-route.yaml
  - ./certificate.yaml
  - ./sealed-secret.yaml

helmCharts:
  - name: authentik
    repo: oci://ghcr.io/goauthentik/helm-charts
    releaseName: authentik
    version: 2026.5.6
    valuesFile: values.yaml
    namespace: authentik
    apiVersions:
      - monitoring.coreos.com/v1

configMapGenerator:
  - name: authentik-blueprint-sources
    files:
      - blueprints/sources.yaml
  - name: authentik-blueprint-groups
    files:
      - blueprints/groups.yaml
  - name: authentik-blueprint-forward-auth
    files:
      - blueprints/forward-auth.yaml
  - name: authentik-blueprint-argocd
    files:
      - blueprints/argocd.yaml
  - name: authentik-blueprint-homepage
    files:
      - blueprints/homepage.yaml
  - name: authentik-blueprint-grafana
    files:
      - blueprints/grafana.yaml
  - name: authentik-blueprint-node-red
    files:
      - blueprints/node-red.yaml
  - name: authentik-blueprint-wikijs
    files:
      - blueprints/wikijs.yaml
  - name: authentik-blueprint-iot-mcp-bridge
    files:
      - blueprints/iot-mcp-bridge.yaml
  - name: authentik-blueprint-rustfs
    files:
      - blueprints/rustfs.yaml

labels:
  - includeSelectors: false
    pairs:
      homelab.app: authentik

commonAnnotations:
  argocd.argoproj.io/sync-wave: "3"
