apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: authentik-credentials
  namespace: authentik

spec:
  encryptedData:
    AUTHENTIK_BOOTSTRAP_PASSWORD: AgCTRKPoBRkg8esi0ufwikKNsY5qSrvvRrIquPHyIUGL/Xtujk5pin5xrpFKhNR7OPwKPtdbuAUK9PGcxo2Tp3dpYneF0V+tHuR1Um6b2A+l4Scz99dT9mstUnQq3+hZutCfTm+ZnUJGHNCShMeuQMWFgXt+axwOrW0VIBL9Jk/Ra34o93lUjW+pLxcWizc8j6xUnSRu4GT59lps7GGTHrhMUa4toIFKGg3Fc21r6ZRv9veqQBisFD3Wk+EGUBYAw525Ep2De21d2/r0+xZKaQAMQwFsyZay/Uksj8HUz1K6eprZuIb7f5zwSQjkTkkPR9QcCpFsrvxazVPeBNaaI/m9H4A1ucO/yaqGRTYWy1FOBrMRu8zCWuvP7/oNXeSHe9J49CnQIoKzuwHbxwTFAkpV20lRBjv/YnIVTCoZi1dUsDjnQkd1WVRl+VpGGn0WgyU7uAS8R3UWKaDBZhwB7uhSptEpd5bW8+YgAvR5HcQ7W0pPGyS+HgFhIPWC3AJE93EtJwmXEecOT2J3V5XDA8I2WpcmSl6wwhWkFWIhB5FXNNg7vz3ygxb+8JtBqy3Mc6taQ1VRI82Hk70s7jP7j1nVnkdfnJgcyiGADCEsX/w1+OrumPKJAumgynCf+aXi80Qwc5WdoTI+1+ydxnc/KW9XvkCun3EC/2NAEcX1V1gmtuNyp8yVkmUw7f7F767wpBrcEphAPgL67vKOjZ9KKRc6n2yzkFYUWBQL6YONR+xgPgZyrYhRS+rYCyfbR2jkLsc=
    AUTHENTIK_SECRET_KEY: AgAG76di9mgfZbl9k3X5fbl6YSg0oHFH4ngO9zr5/RYSkWZr5/iZqt+YpCSp0KSG2mAYlp1L0jSzIgjCZUyd2ZVi4KfWbwjSy5Ze2QThVpHeYD5BPSIrQPqBj1aCef9xk3q+YU5Jlyv3GlXTvn6shs94SfV+5Xb55Jo6eN8FdF4Lys4my3yRlb/0/ShfBf5+uOdTgLjoW+BvXRBk782Sv7sdfsTtCeARD65TF1S6f+K582Ijz88Rxhq/s6o9UNolOOiprSNvH1JKSyrThyWiy6JIPaCITMN/mgN8uxWdEyD0EvrKI78bA95200WDO0yyokVZ6qPVKE8K5putILpWabj/u+ymOSUgo2kWBZcnwBSL7OI9t50opKqHZv9OzPcGV4fvqIlIBvSXR5mq93ALt2Zw/vV1My0Wnn7vgVW4o2fjK6kQ9hl5PWXlICL0CTeET19VCjWGrnPulTq4DG/BFJ1RhXt1inUiEK3k5lgEEAja3w0PzEibSNg4nQ+LH91QNWs4bsmCMnEYu7Ran56lXx+U/woKd6LuhjSRqVY9YGVwQZd5OFQNtHJdQnlyn/ET5DFsA6Sl1tOer226/ZHLevh+i1nTi8hi1+ngYqaFL0dS9Kin9pGFBCKJrMbTOhLwheu1MpFWVEexmgHnCPHfXKxoThBSHkK9S1jQQCWoAD1Mp16JNtX2izDLWquPp3bpcW7p1aEA1AUgSm0g8PHbEEAwlpKUj8W227YSrFMpi936sATciLCwHCbfyYr9Tx3pWsk=
  template:
    metadata:
      name: authentik-credentials
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: authentik-homepage-token
  namespace: authentik

spec:
  encryptedData:
    AUTHENTIK_HOMEPAGE_API_TOKEN: AgBjbhaevvEHKwp2UflA6fSlr8GYl6mw1YUUylo07wfbSM7gAKjHgZDiCrHF7Nsermg5moUbblWs980URr3OxU2wQEnJutCSJr9FodPelLmXXKHvzHVq2nNsXBcvnLNNo0twXcQZLk3LYbV2DlXVG8lk4pgeJ4CgBL/omM3NGQw/Ty1vE6SMNt6pIWv64LyUernUBHkax1BJ1a4s0I8adjGMCSAJ7cN2ro6lzitjfinvGB3O6KQcFNzMt3Ds/dVBz6e7nlACyBdBY2dCH52WAG1J4nZ0ZGoTOvDCoxhuuuyVS/CszMu85p289F2l2hr9gMjqO2i9du1Ykfr74LuEvAlz2PQGZnnck5F9DiREF9LZDPrjRUK6nxuII2T+Xkss1yqsFG2qV62Hc81cQJDZhmGrRIUD2AsUD7qJ67fGkL/sUabeIlGlJQxRG10VLGLZGpSnYlC2FSyBJ+sRyvD/3cm5HsOD80V8QGZ9wekM/YpU5kKvfY7zHzBqHNdwscXO2KIw+XrtqIeRpvPbDhjzX0yTsX10MFeQOnq1qseM74gG4f1d8hHnBORhaqct4CUxfNSdaKm47e2XuoSdyChK8gfQ1pjBNvt+LfqHiFU2Zcvn2MKmnHjKVZY0sXNbrJeEx3Vos351+bhyZHUqYMSDpu1HvkMSDcqhzZKDhQr+Xt8PgEZ7/ZlMD3DkBkDLqXYK2EABERtUI3/ujGka58UIGH9J+lupxo7e6HOOmPMPznAnxkT33Zr7KdGbfFdcU1QYUoFwNlEyYTATO5yBhAThmcNu
  template:
    metadata:
      name: authentik-homepage-token
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: argocd-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    oidc.authentik.clientSecret: AgB7gKchQvMErynMJfycoowBDJxTsBuw9HCmY9w3EEPNOOBh3qO2zl0WSdb+3dKLQU9N5IlP1ytef/G17PD41mdHKOcPYLB8RAZmz2yUnTbB4hTCcUkUSA7iSuoNwzrjPAxs8/G9uMn+CnGIg2L4P7Yt1UtVDYKxcWuz85TxdUeVRO+v3MON07zlhTZRdzRGCYfvgx6J1LI+iplNuPIo7lsra12yIDG86mbYIul/r0vRBJf94mhGRXeQ4cZqW9shvbreU3njgN5B3Z+Pe6YcN4xvR9t1f3Tsl1aGkU0s1/4z5d9kAT8V1RRvWpUZrNXellSnXFOdp+EDhpWcnMIeY64A8+EAlJbfai2YwH4sju5rJUOAkRpAqwFd6um4kxPKAyMLOpvNhw40arR5z7BRbH08Qtp0wJrL2hqEXxjo4z1KiwNZGt5jpXOgAT31yEUSv2jSCORMGWi6dGfpw7ZDWwfVCpL2MPZNZW3P9rl/0zD5Wcs08TC/qp165gSx3msOpW+GhRMSaznC7BtfC1+cTfTwL1i+1rvAxF5hv78Wp++TYJOYqGswCzqb0fUT4IXjfmgd6l0TW307jhPrVNYN/wyzjhDJ1Hg8glv+z8C8FqX5tG32No7u259CLFdOa5GcHF+ytYm98NXvaeJY2M7Ht1xBY+Ef3hFrsGZ917b/r7smc5BVAjAT+94jOekKlogKBlMvURXkRoMtdKqLRdrF6T+O4TAnU4jX8ygeE1P6VGJ2tEM46dI=
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: grafana-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    GRAFANA_OIDC_CLIENT_SECRET: AgCHIV+tYiJ4wcP0bm/L20Dg8qwtzfPPaYh0JAdr8DMlD0pJwLw4zHDdHJ7TaJiA9qyWzEsU+lFN6VHcyX+GhHrq3eEaHB5U9pV2YQ7XlB8KuQvAN4Hi02+cuvsZuqlwSExd2jZwauz8mkkSfQzmWPg0NEvzn1bAdfHdpb8S/AgijBocWB5gB5Wm6vDUFN2MeW66Nj0yRU5D+Yy4tbqS/4DslawiM8D1DMl4EpPG0MD6WOKJ9H+lcxZdsPKoGSgVgV5QPDUc69Vv6pyM5nNMIQH39CJ/zXZQ03c09iMOgY73E+xIAUWS4BwpinLt3PRZzISKZbTTdma95025wKsg+EJlzU6V3DiYIN03cgilcZBY8wW91gs1K9ci0nrDNb4Z3uWrZasUatimNYHa/sHDK4YLr/bNK+O2NYD/U9TYemA6JQJd75tjzVOozgxUoT27MdJY62IlicW6H3SyArxnQSwzK0INnrjYFEhXkm3ZYOzEfU3Shu2EZYOnp39FWP+NguNEfJrD9xrFKnwxJ9EKUgKZ45MHDwThbd9rW5XLMF7XzYqADA6UDSqdTld98gZp6fXnq5yZMGgTaAJsDYBS5nu4VX58JZdMKWl2NEr3DRNmXQNTX8KvRGB60HPAUxBY2NZXCiOSn63LOEWPeeoMlApri5m3itkBou86vyWKJ25b0RQq7YB0URNpsBG/Yrdi/BtGsoXXhhS+AoHOehAWCh6waYVLyn/n3AUXh5HbmPsZfnt9iiAAE9iM99qJEOoIp13i9M8nnEjJaYrir+HhsH7b
  template:
    metadata:
      name: grafana-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: node-red-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    NODE_RED_OIDC_CLIENT_SECRET: AgARtTTBjl7fQQA4AAj0jJKP+4LSXPd9Fn9ckieN3BelRPhb0KESHaawcSX9jqhEkD9yyFwcHFg9PjtcjMHCFtX49qmI3PQ97r6AO6Gp0VVtBPh22vo94m9MySWmjQoA0ihYTUYh9kzAXd/cpUMvJyf6zw/Y7pmnxFbUBdiwp178olYInE+4+FWmGn3KpWX3XZA2fJk6iLN9B8tFrURtLhAFDBt5NWem8TPrYoQvtu4i+0B+ZqOrgpzHJkt1iJL3l0H5LA9h6pAMvGWi1QtlkOHZdPvnwJopDevv/q6Nlt/kCW1buWx+DSPlqJWXUjpU48Itl8Dgo18Cac4iJ8SOxJG639+dPfxbHcyRD7Z6Q9IlO1jQqhIZ+on+5WYVHRCSOZnKzTcqeSWI7tzGRCzbeNAOnOfcUlIffQEG5l/zNiDSuU+Y7xiVKrbUNl1pHN31nwsNL8PtTLX4t7L9AasmdP1kCEHvXrfGJCipv0kGQ5imK1zAG7iIlZgCjoXi1F4Wk2c/N5JdMAtQlaeLoiXLiw3QS6ed4LoFQZlZrWh5K2kKAi4FWbN2Z9lI1HFV/TyD31de9Apxgi4e+zrCexa2XatKrAGYE6oNtNIRmulz+0VdGPb3G08kIXGV49cS0IwiCC/LmBqDwN577SS2+jfInMtJIDkiwjoO16wZCQ+EDXs/nyKL4BO3bU4Cvcwal2w3oa/x6s2hhSYiLrguzGro5LSBp1jVKtaCPWbJF0cRcIn6WbXMsWt+FQANHn2F6OrczeTsBn2qAG1vd0cZDdR6T+8o
  template:
    metadata:
      name: node-red-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: wikijs-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    WIKIJS_OIDC_CLIENT_SECRET: AgAjvynQeIgOxKLYAxKHM3XLhQoj+6OW/ubWw+MxFO3iFqt8b1gcPlQK7EX4okmWPhh1/LUUWHE+1ih+UxGHNw5Yp22DxiBJiAHk8jzRN/Q+s8r6jVAoHrelMGO7rkkmYfvG4LM4yDs2gSEpZrPXUIv2ibnvY2mEFGP60Yp4xr8ri3EDTgQuHFgVrPhXEg+InNA16Ql59fJN6J6yPtitxxLwF4NLhEZpFDnaRNk/jseb7yVomXELmJRzeEwenEcjboL6xvUhtNpq1XEg3GULWkTeYL0F7jinmDZZAlqJ1c+7peBRZrSocbCMiocGfowNWpoc1CpNgmQ5/w78R4KzpUYx6vDW7YC0UVv9dnjN3kLVwXJb3SBdZJe7N4urqdymwoHiOw5sY32H4qFe9xXuf7HUPZX3GLpFtSJidHSx5CSbZyM6898/y/OtsbUyTakCuDEWcSYKi3fWKS2uFX9MFtnmN8mKl5f3Z1ae10YTnrNRi8xBPUz6ZNNl5m8EDK4zCDMmKHqPVP5drvorTwVS0ID0RbOMGMwwivnaNk+i3OB72YBgMt03VOYKEn3Ddwm8uOmf+qUv9sxy5fhPAQL8aIG+FK223V/wtwMNeAVc2ry/mwJnH8UCz+qi/QrA4p2WoaPLzGu7h6jIoIBKZsVY6tsATotZcjMc1fpYx2I/nilqGPx68u5SxM6bmfU+pOsa6P9E7omNffhhXxi9zd0AhOC1RmmI9ITx9dbJwjq633Jt98I41fWTPJ+64Oq19xyaZiA7OWCaef1Fy+1ug52N2YBE
  template:
    metadata:
      name: wikijs-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: iot-mcp-bridge-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    IOT_MCP_BRIDGE_OIDC_CLIENT_SECRET: AgCG4AZvnfIHUDTHpfJbGrua+8jT5M+tzwFHRIFvrJGZagkcRzXE36twuecqZ0+RBnFKc9YJEcIio8h6BpIoXz1Jc8GHUtsM3buGKGk7c1paf4IvynYklEJBd7WcPzW+43yWWsKQAJ+c/YLA7eQ7W4YiF3Sd8ck7haSoQhoX02WtjMY5UU/spSX/YFjW/Qr/zeqfqMzDTJu9GuAeSgkR07RPovORdFoXfmWxXoNmxOXrlBfNTxgqyFebx7QAYRPP0+WYKURFuETO0cZGzzJXVfYOuGF5SgBiu9BWUh//QQKVf+hq91kUHvD7CGo56ZWOtJIkVVAAAsbq0X00tFaGnBIqFKb1ycFJ/lzU4TGlWXsujFm4w8x8cQIQrYC/u3JjJ7/60t7nbmMaBRTKFYXMIa7lv9XZfF630FnZAJJzOpMr8tZ1G0TL7O4cSZ31UNHLlUDjaNrwRj+pTrzyrpGzf2SqHuRqCXhY0CbTB18WQ5NNoSdtjKVihXe4ZKC7OT2oAs7t1Xc8KssnXIlLLwK3T5CHhOEfigNnOcX5Wujg7RkUyIa147GUUPi7sCqYStElSshd6YGio5Z8rgqb6IrEUGMbhBBM7fJgXyP8TkkcCBNYARXzHlFEIAV2W+dA6FoAvauk3olRVOiKaMB5xKeiqQbXE+A564TxM0pfx0M58tqBJarXPaSz4+7NyxUEgsf9x5fSnHz+Qe75T7DdLiqPWPYesMPZ4Vuu+C8q+xVN5R0KGxb9BErt4T1ClMhCvbFwfnzJ2gqSGar6TIxLs2lQ8S9l
  template:
    metadata:
      name: iot-mcp-bridge-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: rustfs-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    RUSTFS_OIDC_CLIENT_SECRET: AgAz7h8I3VVUgQDX1S0mi3fJtM5Nq6jBfcFVT7ZYmh7bjK7UOyJk5urtmD+4evberPj8RIlptVmuLCDq+e8QYjwhUqUZi91G7KcSQ8WS5pMOQ0Krs8ARgDqPz9IELgZ0AmGoSovlsamynulTPlUGQY/wvm5HomcmNFKaNpLWgrAXUWTuPgMxI6mYG5wQAqmY/MW4OUHO8mDepAJcaEwxKNhx+cNHA2prbL2Gifnp6/QoJrMrl4WMP4X3GvZAX/3LE9wZ7yOLNFudmVLQV/K8h3QVTdyKkcYCIDnfxcwRvXGgMYXhAbHajuGKOa4qIzgkh3mdH8g/KBY0ZU5FDb3rFJ6i3B08HCDqkj7xC20Nc/LGFanYH9LzChJmwlZcNGRXqlUePqRvVfNEzBNDLW8+8XjBx+G5OOWKXxGP/cCVgpdrrf+3xUu0t7TaWZac1TbqXbp0Bd6pLOXcz13GJ7ppRIFXHQQBzIFIxFKskhS/zwP00ps7R3Rn0VgIFQM/AAF6E3MYwoQpRRNUGA726VfiM/1xhZFHaRclN4YmDso5DmH8WlVzrt/SHTfbE3LBtDpvyi4bW2/ygH8PgSom0qZMiG8Pc/hBUBURflIxmdVL4M7wGulub6cuCJqJFE5w/fYhWl3oH4yZMwE4deoYsMihIW7c13TxaySPBqXTNKO0gbJBbgmA6p+T+/oAaur28aat47xqpgnUqmOOajo/Tr10aq7JfK2C0BpbCLFahp0DL4xC00b9QZqi2Rs8qYvaAZ+VvGFG0n5esgxqudOExUygrI/x
  template:
    metadata:
      name: rustfs-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: proxmox-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    PROXMOX_OIDC_CLIENT_SECRET: AgCLBMc1ciZdvx06C/2qHPrR59egGFMPAOzhMVCJT1V3qUfztdR4XgwtJ0/Y9GKsjOqywfHYoxzI9xYodVGCm4VVUKXnV6/Yq7Ch4Qg63Kfnx6/9z6Fmj4605adG76NQkxU7PtSpHIY/CXtyVwRn0VWDZLxgbKuCiyPJyFeyj3PVqGa2SFCpzBhNZx9e8y1A9AaivevZlgYCclfFlqNwOFsOpT3PMdJT1pRCzbjjc5V3nQZ5k/5MPtgJWCYi6Y1KKEoT0kMHeWbd6OO11fPXCQDiQCPqGPFJnhtoIWxYSxK83hrRb5Fr/+rdJfJy4MIzbVtZAHwzcP8UTGLwrGhWr3Unw1f+/IIFvNvP01gMfBPMe7F6ZaX/mamxcTDPk+be2RZT6+2yto1/ACzkSEtrJ/sq2NsrYRa+TGhzU1Js87sN9MwfSrgqvsFYdKhlwvilYut6udHk22SPsnqQTAkYFSijYsOkiqin2NN9Jbda09y+UVaUrt1XQDKeL63OSgWLM4vAlsMkW/5bZfRM/GLwLt5E2ZhZ6boZoxgwe6VswUELnkmGe3PCBFNy0ZiOwY53HUjT2BjYvESFztiqi9XYOva1Z94phXXn5eyt8mZHb1gUVN53+pHsbmBhu0yO0MZs1YLa06xckxLVT1Hmt5R9vStqVvN1r0IhFFpHRs2i9u55h8wgD3TQGrlzI0ynBA3SvYraIXVYElgejyYoPhDZutDDxA7NolLrt7d6m8ygyZ/7T2KNLjkIz09TFksMMhDqa2yI+QvGCB/xNkojhGP/zl3f
  template:
    metadata:
      name: proxmox-oidc-secret
      namespace: authentik
    type: Opaque
