apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: authentik-credentials
  namespace: authentik

spec:
  encryptedData:
    AUTHENTIK_BOOTSTRAP_PASSWORD: AgBiMv3Bo8kBpHKTNaQ2mtdf6upgZzv1Zu/IrXkgDdfpnE0sseFTdq+fC8DgajhI1W8SYd/e29Vf+MvrDCToOA1bNwzLpY5QjkPVpqKi9eeUroT9ZKX++nxgQEwf6cTpb2UE05BTay4NSBpNi0UABFC9uwEYhup+JKwIqQ3VVPhoQPgDg0MKH9rJEmRNOshCTyWGGYRyaRmLb7JKX3cyLc7tdMrNJacT0YxwsyWyNVi8RyPiJ/3+fYoqRE3UIUdZ6cKb4cYMb9yJv0guhMeUiOEaOoQU/0ZdoezfzY8yJi7tXSGMlxVSKttzBdcKXz3dcAfFsmmdlelRyJWoMGlWHyDH2Htg886XWKGJfmadfK9s7g9IQutcnZQpjbz29xfX0WBLOlDc/X/C2mok1PHAGiDPe8TmX0ZQHpxPsQZ9zxvkVehNHbUk90jnKvsGUACrT46Am6ZX6HMSSjaGTvzIaokK7Dpwr3QtNmyjXGeIIw7s6mIC9ypZ3HgwUsLArndJzTDmcwmjFDv9W9Tc6AwNmSAJaEsRJB+eA92Lwnnwc1lF0xc47DJ7qXYMJQw8PGIjkp62uhDd21g8ppiX4xJDQtVJ0PH9oHxjNKGJ15lwx8RtOE109+JPYKrqq7Uk1RJqNxpVR+9NlEV5M/3+U4yqzTdC54NdMEovTqvCU5svN//EMlteoitd+wLKlb8xdHMez3P3uD6s1sp4ugwKTRBhUqcw2lV73ax0q3V9tCCLRtmi3Y1XgrrnSLQZklTB2Lud1SI=
    AUTHENTIK_SECRET_KEY: AgBukGYXPL2roXSWTlbr3FJTdlBMzKjvEXRmOH4hR+FqGWfV6NQzXGPpLpVe20Y8B3KMFHLPNZ2faIdUomZmeC5VW+zq3k93epIZycnunY0/g9L8c8XRFcSIe73cbT6mqgZbrSEnChtbZJSN33slEOjvZCH3mVKg8Y3w87/cljlLVTL67ox94vjbbpuOtedU6Jm5kl1JBaV0vnrXcgB+Bo8sib1Vz+tbLbmbBqXbGJcIvxHUsu7Kib2ytK4EkWvHM9kr0gUVDlIEMLOgryQQP2S8MEm+dv5OrgB1lVo1qhHxBgH6QD2bZDS7LnyVSIGw6FSnHyaxBRD2NPfruCMqp5VzHO4CFYzNKF1CNgVhttH8/6rzdo3ZdyDsYesLAiqZxFAFSAb3O8hzry8JqjFlFuMHL5HTRX6VRUiAT5Bu13Tdr9mEx0Y3C/3K6UhzyKDNI787Y74az/q8DjyvzrXddx3SsnJpgVaCGlkrdU13z/Sk7edm3Z7PC1VdJdnI+zktSt9hD3kxlvxyswFX8wG4SPfaBOQUqvpLxd92oX2p77uoYssnb44O+Z0gmE68VYyAmQQOTrdX+PEJwZAlg686Mi6ATEZOmgxnvB95zZWyy66MxQnBLJEEGB/L9tWfFnVhOmmbWhLg57dESMWr429CwxgyBcIsHN1+9D+V0YVzEbRc3Z71Hy7hbGqi9D+rVvBMt7ZdG+Hhr6gGjYq+3A9Db1lOQgJFHPRsRz85pxDp16wlCYG2BlknrPGm2SuOfm8Q0L8=
  template:
    metadata:
      name: authentik-credentials
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: authentik-homepage-token
  namespace: authentik

spec:
  encryptedData:
    AUTHENTIK_HOMEPAGE_API_TOKEN: AgBTr04Bqs4/YVbvIj4YWoVoIM+UVQJFUuzK/7JCX1fVYudiqPRjDuMlGiBGQLDt2IgBwxGmpY2elamJmVFt9FT7nel/J1fSuhikfxrxFSvtk2YfX+Hp9y57XMqBz88E8mqRRYSncdlktqDys/qeQ07Zde8c0TxA/5EKjPlq5+VBH6y8JF/DrC1pvTzKM5wL+JQ250EHGXCH2tJRQZARXaC3t9TieQrdCh33ETZsnKT/mVf6w9JFHJD2ovQbr23OhsistteJJqaNMpDvqBqOc5KBQu82OD+GL/h1cFs39TXtfhraOc5KxYtD/gT2d80XTm4w/hpnguOCim/moYkGRnTriclnSz/88mwFrwX4MOotJdy6zJpH0oJkUzH54UEeIpX+N/qYZ17b0SyApK1GiZZioE3iYK9No/6uSiyjp7j8K/q9N7Wwzx1fy7ERe8DQQGQf2mcCJG/rWJz4A82zS1YiFaIM7hXxWdWA4QZkPor3okltvmIaonBJI4kHq33ijr28QlNFjnNmCPX3rGJeNdsBQo0gajDqGBiAF7Ffn55y6RfxBeEVp2pIdWYmL3UbU0/weAoudu3wMJs60zfXfgYzWCxZP6F+s4tapx5wd+1h8wJBRu2oYfuJGDL8NBJ1Mi3Zj7dT4c+pZFHJDeoZfgnHQFTZEfbIBa58UEngjDAiWxJXjlfi0Fo4wiYQ6ZEkmHHSEOcQH30spt/hEsJ8Za3V4bNeq8pmKj49InBoaDrabOiLNWDhkEsD4U3OpGUxJnOw5rFdjxG2zisVe1RJuWEg
  template:
    metadata:
      name: authentik-homepage-token
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: argocd-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    oidc.authentik.clientSecret: AgCTzbfYsYss+MAMhJx0EFyDsnQT5ECQOjpt4xURAJhM7zkxhRiPm2FTemSURS9EN9qoP8n6WnM6PfPC3VmnlZXshsmLT5EmhmFHFKe5L1AU0MxbyWpxP2eTq8dI7X7+L6zak1hkkVTH7Lew2C22bbZQlJGWH3nITwyj3K4PF4Rl1xKzNHgKq3Aet1JJYtBt71cgOVhHjghVZ4XSK2/yT2zsPFl9W3xhqCCib0olgQqdRn7YxDVVuDcpYLJW2+wpR517mI5GELqAa31YE45C9tebRWTO29OxajRd6x6+dMX/TYk7ICNry0P9xxRFO0H9AWbcxGeL2S/7m1splVbt64J62OwXPgRQ2/ICZYhVVe7HKIL2ZZyQszt0bjWVxbKpU6sZCTfVRTpbWwn7SGoyKSZM+xzU7hLDEtHJ7RELMTXnRkFFT2/8l952hR528vO560qwBqtRv1NZmRfbJr4qD0v1VeqIyMWGQhuRMD6DG/gBnBDWmYhgW/rzMkYYCNxRM1IZJe0hC2zQd4eNUth1B4pYIrgbdggdCm4HScudHbPJgD4Jhmkl4olndfyVItYvERLbn4Om9zBuxUZlF1Yuy86tUPkLQln27KCGE6I3lvkmhoiEY0U3w9rHq3LSKat/7ZY+aB+5cxrtaQPVwUyL0jVLZn5s+nq9fAlAFFvD1fh7WH/VzHgypKXu/3PB/uRQ9SCuV1AePqsiOZiiYBu06bPZS1boLCULYidc+NeM5BJIf7B9xEo=
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: grafana-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    GRAFANA_OIDC_CLIENT_SECRET: AgCH+KSNz4k1wc2tlMNqaGrBBAIgeWfSokBQr+/EdUlDBq3PQwt59c/rL7DgfVS61jABdUeYwDOQuixfA+pEzn+2X+N6Npx8rhAVpgclSsTx2aJxTXGEFrchfA+oKKgILy+52nqxYHEJRcAolUmJLPx2rTbQk9IoIIfHdq3AEV6J422Fbxa5N2V9vsUduNB8MHfUVvvA09HBHN9go4fsPzzUXPL/213YKs0xG6oQeGQ5LumfW4PH39Y/JBtyn0fkJ65jyxiCebV3q9pr4vAAbde18dAtDbU4bYWG9NXLkLPJ4xUDleux5l8j2Fs5b/sx7np7fDi9fop+7vfEIgWqWA3mgklDbfBOUZrj8N0Rquc4uuczO60vMVHEQbBBVmoGHaVp8Yk613aL+GOmO/iqxZINjFTFMpzu/QsVAOEqMIYEVu26MVBDsO15V1VNEh2PjlmFng2+UcIXjl7TJoeRt/US/yJqFmqyIfnookZ+i3k1kEF4abjLyjRUc+v9SUNR5e7l47gweumjRg9wDuzclQ9X0EZuiyRCxXgAW7nPA1/Ie8fHG+L1R+fsT5kdzj8ZA7s9EGT9xDf/iqCNvxMedZ4vvk19EySAnHJOIo9FUgisMSBwAbLvfv/B+X80jb/csYr0SdIacY2YXf+vOecstx/fhR8SqlDNJUJ6v4UN4s3cmjw8uXXiM1wAofjXKh6fSqJ1V2Suf1BIDqxMqqbTwschAg1l3NAqDgIXFCeu+hTlqEkIozHiiwkk2y710E6Vrp4JD6wpGHBzCenDKrKt7GV9
  template:
    metadata:
      name: grafana-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: node-red-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    NODE_RED_OIDC_CLIENT_SECRET: AgApm1VOwytkbfvzfef5LPlK7ZvMOYFmd5xqyv3s8PVOU8cvJjwfDnl9yZ9d1NdVr/KruaG3WcsowPC3EnOpoSyUJJpl2NQsevgKilbuGf5FDXN+JCRIpn5zJbshDdC3qxklXiBKFaqRRULRlpRNRn6AuFGfyGgUxjEHjyw8QCrxcIRz7frYHTjfuofVXUxltp+PhJUnerJPyYb73BtIRTMzv2U8ltof4KGLdZhb02qjce6oum5Y5Z2+A16i8PUX9vs9p2M0vLM6Y0jDgyB93/fMd1YIjzy3HAhtCVzaQ1oj7vJgJcVat+jEzubhSrVBkIXo6XAgb1oWk30fsbMzkVPlHTEgu655EbO+xWHCC66verWfixr+c9+s8pu97ApOkLo70TViHuNkjxdAWMy3GjK/KY/VKZFOVb56/RuPKAUrAumzgXpYEHeHQTOkXjejLnDP49fO+D3LCIO8XrVAX8wJGae+KIxuonGzEo9XSNyZTy9y7CB2tLKsHrPcp3zGdAJ09G7TK8jgmer2PsjgyYc/JpvFhFftHxSn8s00mYOXLRGhgF9NVeFj9xRo9bSId8QG9DA/+STx77M4r3K3UFJ7Dy6AIMGUbgt0AaLWCn+uXry7UxQjDSr3s4aoADbX9c7W4DGebotSheR4/AjlirXZivLwZH3piAa+bnXHjohSbdGGYYo/xUpTPm7jPJkS8/sMxK6Hfc8PcajxCFPU9+/tMeivFMjD/MAgFum+HZklEJwljO8XKH/kom9iCPVfN7UNvxRmtR23qhIzMUEl0Lea
  template:
    metadata:
      name: node-red-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: wikijs-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    WIKIJS_OIDC_CLIENT_SECRET: AgBRxRjDV7ZxIklRraJW7m5Ieu//l0wNt33MOOxN+M29mdh7U1TPKGmGmhsesiRBVzP4MMBerj0q/93L11uWXdjNobDI+awn4zRZSM0m08PD8RCFDylqtGRr1MaUpoUKVtGPFggRj6bYSqu9RqWtzx1kKieBE2MykXbdqPpMo1LXhXxV4Y2wKwgcxy1WA+0SP8Wp5olbZT0ExIjoUuVh2AZXUCAgQ3EAAq+Cm92OIeMPkeaQaFNxVMQ0285ys43NSUgFGhFjQf30Rh3V5bR2VIF4dRE81HnOnPbFzJr5emjnSa6fC4RE2SXoJnVmKFboE29ALRNTICKflKVRAh8ZMUZEpIK8xAAuNMgCzky+ICiKOq2rMIsQZHb+g7K0e45+5244FP1fSRl+JVlOHe1DVD7XawIqKzGeqN6Z8gn3JSFtM/MWjpa8k/QaPImD+WlX2VupdVbjJWxENIzVvMFBMo6Uy9iqNy9E35M2Jpvghsd3KK3NRc2Lj7ZJUkLASf8DstWTU4Z5zxzqV+nxWx5LCRRHRIf53C4NVlIXR6nsB5qOYJDv1LuFfmT0yMqF03egVTfFTAN6pT6UHkwcsxkTLLQwOCQVv7EYyozRWR2QeAB0iJALYwbyngJwNB2ECEiOiEcf7J4zCqcENE4P61M+vijKHkDsbebdvrvFT0rn1VWRd4MaCOVruSWIbU4RekRkQ29pXa7QVYb5KUmbE6wTZCbIVGgVhXMqJs9LVlnSPcJai511xyVmw7FLzGFkKGPYSzQtSZ1MSWkTgtR/iHfVQr2G
  template:
    metadata:
      name: wikijs-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: iot-mcp-bridge-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    IOT_MCP_BRIDGE_OIDC_CLIENT_SECRET: AgALcWjvJ7RNPVqLIVua3uQ/4PBUB6AzjD2O2rnurHfLzFObxpPxgrVepQOTr5RPHuPT9Im4dGnn9OVp+AhNSFMBqLwAhEokQqWy7hvW8KrFBa/r0hhKDgQKrA1ppsO1jPyLkVwTau7R6NjFUHTvqDKWwuMFrmSn9N/MEw54psd8VMy9UD8EuPe8qoLp8Z61hbH0S/d9HU8Z6DkuyfBfE15DPc4wvG+R7KrUyA7yE+Yn6hAU+mIZLCWqNDFnU+NWNyvrKcSMAGIQSnJhHtX8Qms0E+EI8tlehaMmgJhZJlncU7MFZa1ojS9WIx2XoXlbepfcnWO87j+42UGi64e41zqx8tAvUU8h5n92C3muQ08Ez6hEZhIKD6QxbUmNN9VovNy/IDUTwqyjm+EHQhRXx1P35m+cdeIOvwkpb6RVpXK5jiAizVXrWxKu1B6R6jkIghGUCk9G4fvAHtG2TkqpoKxzPm1ba7jK7PPY3vKKahzpD2qHZ0hZJgTdKJ1OnI0rMmfya2YFHu7KAf01irPIoaK+zvSsY8sR5uQ7UoBJGMdH4ecTLRHgmmrfS3yNC7Xp5dhUKkm6VWfv+kiJv2S7Us7zvgIiwxwdNWfY7lA1rxNb7vpeW4VF3MXACXUskMIGDdt3aUlP/ts24yRZ9x4IW5pxqzRdHjRGT50txODyX5x1t3PRIViIO3d4fGEYeTBOYpE752+1A5za++0vZwHu6YQCPurEXO4fg5Ilx0ypv9qJ8d0JYKx3/6ZDxA51/fjpImhMTn1zGh/bPm0gJ9Preybw
  template:
    metadata:
      name: iot-mcp-bridge-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: rustfs-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    RUSTFS_OIDC_CLIENT_SECRET: AgB+jVby1Cra+fEuEPnVwoos+p6nTTfefGNyVFn77vhWHy3D4us2pN/8ImT22qzz2F7qgA2fmVLUyFpB7WquD7/XLmX2Fl/PmwfNN+BWOO0rPaSv1DZqg0zNl+o/LdtHZEznhHZtfaPRot6CDb7HjTkB3a+TdgHlU7KWzRF++wDtjmFNBM8QromWpxIo+8Ct1LkM/p5w6ZxzhNMmKVTRXNbYKUJCBL+JBxV9GhOA4Z0QfS/vYXQGaZh6KEOfz917v9KcHn6K+jxJ6wuMl4S9avcVCqZlcBRhbesmBoXR69zVn5FcgKXZPSqmNoOSCIFSLkSi27+xBZdbOeocu13H41VoPU21oOGq5L5vdBtCybbS1qYbCIcI3Iy2BRr675pjVl/hg4kk2Dwtshp3bIYOxC19OKI/qkpBIPLX4mARqLIF8YuEMlE4h5Zt207GnaSaMqF3KcaInl5LIVXv7xdVxXeA0oY1RC5OgLlzcmLNXJU3elv6ikk1pk8otKhnBb2y5Zkga8JISMuPcNPFr7IpQP6RYVieknSRWTrnQAfnrf36qxKq994faAIrYGzLZbeRpL6PC8uPTYQxNhmn6+nv4hiYVv0HPe+KHgHhX8mOJbJAPn5BcidsTT3/gzHiKSbqeS+YP3tO2QILXynyjehPFiXSfiontWQXFw0Zf7Nr8GDLOyZrvdnL6hvue3TmYokqXFngOTl8m5yC+3VmNR60b3zqytaayYpLCmMmgM6RA+rXrpx4PfwcMBeekfMCp4aw6JNMt47dtBAT6DDf3q4cWJFM
  template:
    metadata:
      name: rustfs-oidc-secret
      namespace: authentik
    type: Opaque
