apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: authentik-credentials
  namespace: authentik

spec:
  encryptedData:
    AUTHENTIK_BOOTSTRAP_PASSWORD: AgApQ+i6YZQqE0UXvYpSf+OsZKMRz5hdODnSFBOOUx4xkkYagxWEDoTbFmEhOv5XVk9HMKIyWC85hHkHV/imgDIhHREz5bCQfd1dE+Jq4N6BTHtMivYW10vYylPDrs7ePEA9xljYs01NLFIZHWrmMfGYLsjePxB2PBP7khK5u/GXbD+ObSITNo0PnqaQKQ/NtsPpVwwXIgvbzCDa4aBKeU7b/+NtzbFnZF00spExZDqGuN2JFRd3jxUrOdqLYQjhF8VFCBzVEC0sROA5+ECO/lo8Fzvfdf+WYj2imwLvO2Y3Ccg/abUyh8BqJRp2PwUUwkZfOOKXMHSmFgG/93b3GeO9TfpIN2Z36Lw8TnmvfKEGlbrJodAIZdFVSsIA/S8fZ3TsRHUAQEFrb8CsTNYSH68PikvRXoJ3vQCbkbE+T5QBwhjvUfyR+ITbuQ6fDrpS7pM8hPiVjB7AdF0nbQnjMatgjBhpUwL9dIvoN8ql/tpdBQDm+rKD7T/ROHpAZxS7qjFu52Vi4JyT4vsEQdRWTfKQpUa97hTLarsJI9XbAGxZHek2da1HNB1tJUJuxWZKgMBZra/0zYwTGgbHANdDXWj3cs0qnOYjhZPnfbWLIXa0376PkI9guC5/Vmct4oJyUOOJhozz8evcFECRYWQBrVIez1k79DNfovPSrPMyCfWC7qCLgMEk0zSByyrriRec9ATFz4iulb3JOv5cEXMEEsIn+dHCFmv+55quoJmzN+LtDBF8m01g31KN5bID7mVEhmY=
    AUTHENTIK_SECRET_KEY: AgAfO7mRF6QPJO5uIrt4Myk2N7DEMQ/iZCfzMu4aCe8QAMOv/TPJNL5ajZ4gnERq6ab3PMtvzE6HR0g+r1dQ2YS7IiwIlYBNZ9+ImYkioQ5IR6SQrcEFPc2qnFUixLFGLhJLjurm2GrkIV/66itRAK2OmXW3J2Jf5rbJ1QNVjEzHTQpntKXS2mBhpxJw+UaRswq1rhsWu1TJMsgnSmuzN5c0m1Mdr+Dq8k2YQoMIwDtjhfjANHFClJTYpZ6FPGIA8Fw22JCfiqIVrAsgs/07zJ2fF+2BSBRdrsj+yWhR5EFS0s0FxfFqwok0I3DRwC65xi+HUL6OaBLxA4xn7tUfIL30sz1OGap4FSxXwXeUABjI5bfZWUsnDkVkoW+bIiBCCVi3+dRb5gRD7GBpIVb+k2FeL7ftK3eWrPIL+2ILhiX+cpWE/nBo1XbXnZXUSwAPCeH9h0TJRKQm4UuhO7/boa7m1o1R1H3M11fJ6mJnW8JRtO2AESUy4DXbsPKZyL67uJNkyUi6BooC8PcFrfg+0q/Ez+1Bvn9MNicysjV7oTy3HDFYkAH1fx3E4mKQlCBzaFN3jeWM4sjaxBzH5Qvj3F5sHvKz+8hdLUsmAgPmYAXLGwgkVxkZ+DJz5IsWhxK9Wyo6j3UxIszovYlRb+Tzs5ejyoPsvSLargc8v+6G8+ReZ1DyRcShlJu7OhkI9LBDuPQp/vMcMT6fD7JXWNWfw6mbJqHPIMeatoyDK8TXKcNQY2vmBMQ+CHIgFPKTX+XnV0M=
  template:
    metadata:
      name: authentik-credentials
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: authentik-homepage-token
  namespace: authentik

spec:
  encryptedData:
    AUTHENTIK_HOMEPAGE_API_TOKEN: AgBGUDfquNl8/GUoSF4Do7FaP5LP+z3+Zn4NxtHgPmRXWb5yu6vaBcNtGVbopeXTA1woKPtCssqQrOpNTDTl1s1vjeoiGHdrcE5vfjHzwGMo3Qj7qDjNg2Pk2VtvZuHbjoeQUsRseUHBVJObc4LvkmrssqYzbVhqsck3lGJr5vPSJ0IWyUNrL8y46XUv5xf80bFbLn9ZkaPR5S9Wwzybs56l+IVF/IKOJQS6nEV5nI3vyaW57Ls8p2uw3vtVXFclYv31l3NDhmqT5Ptxo8sBHAxG3vTR/heEquvUpcb4W0OMYnn/sYn4lU5Gh8mQoLcOU2THPZPnIsCzp9YiL4E+sQKgTWLyvlFMBJHK823Xi0qw7N2taNHGN56fyW7XjTJWabTt+PZshNhQnQU6Siyua6PAr73qXlYMsV2aq0ltxKyrbCgOUz8muF8ZazJSA6t2jhjm+f2UHDMMAmd3oXmve5s7ANiDdAeoXmrHqnkRRfZKg6nJ4w5Ge7eRALIY59qxV71n03nGBZFLiOE6oes+ELjDCqdDqH3HO633zct54PNotOJBAOfyrTMRiRy+sTe8beviZz1ynAlxBLMQ5c/uggXR3gp71tQcOWPsNO9mahQtchJFl4f/hfT8b1g66X0CrmAu6YAh2W+T0WNQz/hJS7dCrJ2+Gki6Hga7ZsiLvGgKBgcK14Tg8hUfH1o4C8ShDKdaaro25Rp2v7Us4sLapgyQI32qBXtxXpOXRmByIdQ9HkabRM+eO1X6/zycXEWUebHGxQv8HhAHcQePrDfEbtLG
  template:
    metadata:
      name: authentik-homepage-token
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: argocd-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    oidc.authentik.clientSecret: AgCLdoPGo0XiVsIci4S5+9dqMClO1u6Ndjo7+O4q3lcEg39LFSRxcEIWGTbQ8qxvuF2hMFyEa7FtRkRP6kMwDzPollen+DmlkVJT4La3D29f91f/cTEtX33cBjzAi0N2LPzWqvVYuI6wAIas/JCtW/PM6ulJue7dWg4YbXwAm6uFmvZxiDAHdtcQLutobZnn7sk2cnR1JJxNRNvJAf88MNsVtkqAhGIDErVTK+a6XGGESj3a7DBLUZC+GFOU4/Lo2Kfe6f99F+nFeBEIwtC9coJ8AqU1DTpvKeeG8eRbLFs2maMA8qM0D7sJq3Uz8cgHh159mrJ+Iu5EAHQH/g/EkJiOjjfkH0LV7Xz4IAR3ycLShFCk1HfvNLTignhrwOYRbbHLGfKy5Du6cMr/RrjJcIoPC0njjdUNYWd7mq4UTkeexK9QRoBaaNKadVxsrSn2rPa00t2yE9P7xqFPfkHRY2rpLSlA1ikcPmAwT9tfCa2tBM21Mn6cKhGl5+7plmvgJSTpsG0TjD5iMR63nyOvtR+vIHiMv78y+aAgcOabKElD4XPUyUyqYUikB2KPgYoCc65/ADM1PrsF2iDsNSFYnF/7HqJPsiih392kCor+VbOCch2CSqKmNFqCZw29t3EzUfWqxcdr7PcnkGfcpcxSivv2VENFqEfo45W0047xNB30u2eU/iQ9hPR4yPn86OcJp8mtmoIjKQAZlslujg8GAYhM2jQHNaYhxnWc9v0BM/ZgAJyMl1s=
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: grafana-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    GRAFANA_OIDC_CLIENT_SECRET: AgBD85SWhtfAR/TZb9HpvpLfEHYoli6+NQRkw2vNTmUDUcuJbDpL0X2ix5ur0aOhNLlMebBOPcmIZNnuIC4eRxXzFwzcO8Lv8kOEApDPBGAfS2hi1ABIRt9lbIMvNtys/Re6WjM6tfcAf/YGdwdil1xFRCQ+ukYrXtXiWCDYZZ9XCaGiqBbeUVhspPAuXyJ9CkUjWvArIQ3U0GeDY4UeNn+LiLKOrctoimgQtYCWLK+fnKOtzOGnQh5SA8Hyn+YlxfnLW13NaLiHvmplBF0l0Rk5JaqsrCXZ/wRV/UydSNE9W/9qZal0IKaVfrzU7ZlTEuK/7vUaVQiQ0zY9Wcu2eAbAjVOJUfWHwriW2S8osq5ljxE8PRuFqf05BdlVMYMyBfSkxKq+7LN3hKou7wZLI9wYTpj2Bh++fiL6dO+Z53pAZaN5BzR5fojxvp7t+M5QEsUxkx4ltS0Fi8pRll6IBPNnkYngE3WCDuk3cqELB/O9V1NPuBAuegJER2SywlIYMRKkrddiYXiUMavgmfWQ0SE0X+SuwHGr6yxFT3tpPpBxnhghsaLStcJM7iQA8w7BdmYozvzSKx9K3s3YIIV5fLFq3ziIbPtgjk0B53chxf7lowxVl5LQR+9ofOTHhfdthpkQsqfOHbArppf/pYVpwVI/cQRPaS6YaKSwK0ldJB0s8LPFg3d+OioORj0ZhghwuMmLKDRbvJ8zPEjWh0/C7yocLOCh2kGcZFBy55rmsG/QQqrcdHX1dwPgIt2ClA+7JxeWaO9qFAp1EUp++sLSWGmp
  template:
    metadata:
      name: grafana-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: node-red-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    NODE_RED_OIDC_CLIENT_SECRET: AgCK4NXE25DY5iG32XOMdAvlxcn4GOg+MPN1Xi4NQA60CLS1otpgwojTmEjF5or12Xz75rIO5OhvZWyoO1eOUTIsxcE4TnNraUw698+dTTky2n5I6+wdEjO4hYvpypiVmsYI4q3pFMyPAfBARQN2pdFT0bBF4Z7A+0sCEKyg8wN6Ffgv+O9YhZeGsv8zl8Rz4HAXMnod6beCyTu07IbzoaMvxki+Ynu++3ixDutCls6c8N0T+og1WxucNKzsPTJtqlAPKA4XHDhRiohXMPFDOK3JOqdXtsdco2D2dlldKbkmNXkGoa4fuOIG8tD1tYAseD1fYqL1XThv7zOvUmsWPNqoIP4SD4ZY9jJpPz43xip/7UuczIa5PuS4a2egJAJFD/HNP4YrjnrYXKMrQj14Af7CjoZLGp+SAQusQ2K8NLw1XK/YWdiy13vE2c7v7zwjaKsI/IhzZvy3Yla6rfnIE01y7FSfmCKuQC+fHy800UdDgpojYK9JQhdijBxPgXSQWpJR0U7mE6pkfujb4S4lK3JAx5QJOJ74+YBXaF0+Sd324W+Qjl3lCZp/a7P9m1HO5k1Hgy9QFaqdpmYsCTiNyxLzE5KRFz2Z8gnGswrYybrUOEDhWS+/rQ/c/YVDfJ96omQrALd2xGsYUS/rwxeKtV3pQ/pvF3kzEkLW8UTDCkaElfwG4qj5u0OrvAsFLfHS6EurR/t/hVbM7VpI72vfr7giyAU2JYcMbygLrbVkZO5SfqxR7SANhDxppAhCGAL+jVfrP3E4WcwTJyxrunBzx6kY
  template:
    metadata:
      name: node-red-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: wikijs-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    WIKIJS_OIDC_CLIENT_SECRET: AgBRR8CjjrzYMaOgynwPzm+xV92XfaiGgbw43L/XMc/YcYonmj5KeUdDDjGzOaYbuv7Q2oQIugKMF/Vf64nJDgwC/gyRoqRxKwXjAQY5L4e1qMtaScwehjJceJkRFxDHCGVvgIw/9j38fSwMjFs9UX4S8uGh+o8coJN2GcobPtce+NniU3VJNeQaiSPnuvRhQD6w+8kLBqsx9E5dFNzy9Ho5VAR3TNzvpvUzQ4sCG8glFjymQV+wvqvGq4xjawGNYeTYBFSkxa+Fk8FCGvmIq50hYeLWcqCLtT89uHjrhnFF8J9M3kAVy68WtW81DTZx+KBX7ZYt3iV3n6Vwf0WwfxmesAxFkgxaV8+pBYWdz+5EjhuDiNdVmt3wjTDtxgN1hEDVICuHr4t5bnoj6cWOlzSsojn2t6VVSCpue3R9ZE2R2F1F7+wpWTPHRXSupIav4SU8HuoIQBUyxMhkl2sUPZ6iXPjvdlHt2OUlb3CJ8kl2cLIa9jrCLtO0PVvadeYHsZ8XQqV4ZXpM5dVMcaeLJP2dfRWcH4P7U56hFtsvX7GGWYmVLqgTFq3Qp5JoV2ODjRAnKIp9bEVTxXBd1r1MaHSzOy6Db5O/aZw5gZJ7RzVzK8mQUBBSkfU58iVBITR0kRfQVZ8Qa+7onw4/Z8+eFagOSwma84/gZzdSa9EkmDM64JvrFsmzT84kB25wktDD/ODcfKqqPHBKsf5aJxD4NmsGviRwrTUL1J7iwcvUGQViyzoP+/QWgcDerlhXIGdcz+L+v8dHyETbHk4ibBxRc1YZ
  template:
    metadata:
      name: wikijs-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: iot-mcp-bridge-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    IOT_MCP_BRIDGE_OIDC_CLIENT_SECRET: AgCFPI6kAehtju90JMUfsByORR9NKAWK4KFPjRkvJBlk7mafNe9SXUpefeddl1+zFOvTW1Qwqtqw+kKs7uXqpprwSPJd+IktEJApxnrhHByEmXk8bnOQpa09tdrlnHH2sdIfjnda8cFE2FH3Uhib0DcWoBjDBPhqNkALjlwh2Uda+5fDvCGxxTTFzgE8NiK9g8jP0UdyyfVfBUvrlAPm1Uti+d+ZsxZqbkcVx3SZS+D872rOO9AtI2bk6Uv5V7nhlc7Fm3CjiRvWspEs3rszFRpPTKBqv6WQxSx01/4AZ3tcjAeD0Mugmh7ukL/Ync7+yTPNF2nUEOfAu//9cH9Yntn/Y9BhBGeDWzD61C+9KQ8o28UtmMJlLIXfWKsGFBXvAOx855p2p1LyNaCtwYeLZZgEnbgSGuVd/L2dHEKUfIVcrVHSseCKzAD0xe1pMRcdwRc9KDnlkpIbEiZpFkFdaI7RJyEnPx4qV0+Pi7TBN5THJilNet3zg0yxV7TkI/qJGGjJGWorPveYDU3Cev99PXxgYj8NiYFuwQwXTRgW6Jw4EjktuaFrvWLhguD520jJ3cbNa5ot7Aqdxw0cQ+pHVjb5YwBBSH8VAFhvkN3eKlSdFJhIqDWpo09GcVDMO4Ae5djUY1G1z2hYMvzUikNoRIRYYbNb2V+osEeMA+7XajOu3aYHRqYihSXZ+LrU3iQU2XgalJ+9Wmjw+2tRcAnhcdma9/7x1iT1zj85oruK+CqS3/Zy0jJWyGncWSdI8TYJOaMVe+6TZZ8u0ShUlsK30M7A
  template:
    metadata:
      name: iot-mcp-bridge-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: rustfs-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    RUSTFS_OIDC_CLIENT_SECRET: AgBqR8wFzESwia5dR4+AQfi/b7g2DlhTwuBv7WtPFmHx4H1I41bPMVT47Wr906nIHxQA/XznEoe6WXl+9kX3XFP1AY6CJF4TICFh+xad/L/QYpnYBCKynQJdPiRiSK/GmKnzJmGG+2FqHxyYzgJulTnZwNhMK2BfYhjs7L58xyYx8amaxGmLw0TUAEOzRqRQ3b4MZdfK7zxTjWPtjot3vcGUyzp8agoMX9R1cnNyPgiqw9fbHCYuQljmLX7f9vZXNZ2BNgQrdBD4N/fxcYUDcsO7xjNjiWZ21WDolKjSuhLb0cs3pJ+1lBC9QqSgZpeJWk9gHxLlYeCH4RbYdIAJBqhq1de0KLfqCfPlvwUmKQpsLb3ZEgj1fktJlfzMFs7sNh9RkkVAjxitPgIYLEPJQD62qtStO0wlTsniSUK6IVhaXqzIyxn8kEbax6n59U34IUlsG1FxbiVSvQrervx9LXNsLTOxePdvBnNea071ltYXAhV4egmnfGpwnDgzy6yz5+ioz/atdOqfEGSkmYc03NVoIMydqmk3WyEuRWToOUbUaZnPy1ANPpnh9bViA6IpTuTVsrsoteaoE70wkeaONELFY4kpWF89eu4NTHFQmbL2gl+iIrcgR2JrSmsNKxlWGCqW65SNoUQNvCFwZ/HIJBlpJaxz5DraRRCV/GCHc+l8ajK7idTjc22fA1XdwpgSF8qc2HUFGV5VdVx5qBn7qD9BtVm47YeK/ZuDkCEMPH2yI65hnXOyJNSHKzFAbCrPHRBnt23tMWVMUsuH/wgTRe9i
  template:
    metadata:
      name: rustfs-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: proxmox-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    PROXMOX_OIDC_CLIENT_SECRET: AgAU0cCXpWD1kzGa4nBZB8rMOWPe8i3At1DEw33fFOjpqr5P0ufL67A1ODPampP4gZWSJSMDcb2FRGRG83pvq1Adem+Lbqai7agp+z6rd5mFdw5XWqRAxkFP0hrcKLRoWDNK0cy2N5qHYZSv257xHhYha4IIeOEkG3x7Vf6c2tpVYeBkI5btYp3dkm5qFXMWV7M1vgS90kjIXz5tZGXhIhIEwroca5AbPvHjvJQRyNVG3FY5bhn+HcuO5VBbSawOz+/mM3GndT1HDGhn3+W9ue8vwg9iv0hIdPKBx4Lk96LV8EvHGiK66DfckAgvl1CsdFTw8pz8D6pRq30xPx/L28P0HlBpvyn7I0TNizL68sC3gL6UqzOotp7wfWxd9R6dFRmMUGMlqi8yZDph/+UDvAfrvQIcbBtzOHBTWY/G1/LBfvm4XG6YqmK9AlLAVheQxHd+ZxDPoJgzF7YhS8foER964i7ZsP/KXOqnYXqKrfOM3MBjbEA5mvAzliC7ZTfI0haQZsqcqIB88TvoloK87FvFd5IbS7+9wFtsD2qHz/Bkvoibv33bWeMPPhFPiV/Bnoe7F0ocpNFctd521QVxDOPKznI8f1Amu9vpD76T2IfG38LFnzpC8t5EfjqG0Fr7ueSlFdM5GECseFiPgDK7cHcyOZyMf141Odz9+bDm3wI3/42on02iJ48wZIUKxsV6AAiLz69hxQoXSOSMsJhYM/lADQIZa5Iew134s4/VmHYA7vAbKN1tt/NqmXVscmTHDAMVbORABrgiYZAOyXg1ruBb
  template:
    metadata:
      name: proxmox-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: proxmox-backup-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    PROXMOX_BACKUP_OIDC_CLIENT_SECRET: AgBQ9eVC7LYVBWy5/RpEeTYeMAZTNyy3c58kH/Uo0NMiCt9KVJI7xbWf/YdKa/a1nLfZbDiZfuXSLUHg0bT73rI1P/6fZDIz2X16cIdeKAj7120lpi3peZwxdd+cHVp5DqTmsugP07b+219osneLRhytLkc8AEKpbWfWJ/1cCqMdKTrDQzl58Dz6ULyrXHc4d04GdjUK8/zzQM19n3DO+N+mF4AqL6zAFBCOW5iW757irWoem8QYDQjgbIPcXNQeBLiHWKmnMUn+bj/EwlyyoTNfSy1gYy1kunCqquAkrk8pbST2WaMEdRvbBMKJMXg3Ybm1XSyoLPvfdEMUrBj88kdwRW0NWkrtnLWFCym7tJVQU4DCMEPsuZTNNOQTbd/j3MeFOr7IWa0YP+qXp9Ibm1RSflpQ+7yKJ+vQTxSJmAv51CNbULDU2CDZlcMfE2zD19h4UhPGxy39ArB1ftzE48REkLRBZodxyrd1dHbP66/jsyHFArGmNTzONmaLJyGjMY/0rLBMebG4pGpD5bgv7EIHxfx95bmhE7uyLVfIcFOPpgtObaEeJpxo+otmLnkw3skTHZBfFg7Csbhqlx2nHA8ZpZtBZtdcqKzpv6Tfj68165wgbXY5YwrIxCN/9jZKBk2tBVbRasCXIQYcsQTX3b4c11KtL8kQdH2WHfwz9uerhJL0vAXnW84lbcUpQgph5rp0EfUFMidJPciqjUYbV6UYfjhEzGE7hn4dji/IT2FqZZRtBj39wZPdsWaXb4+Ilvuoee3EqTSvAxkXlARXCCMW
  template:
    metadata:
      name: proxmox-backup-oidc-secret
      namespace: authentik
    type: Opaque
