apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tempo
resources:
  - ./namespace.yaml

helmCharts:
  - name: tempo
    repo: oci://ghcr.io/grafana-community/helm-charts
    releaseName: tempo
    version: 3.0.0
    valuesFile: values.yaml
    namespace: tempo

labels:
  - includeSelectors: false
    pairs:
      homelab.app: tempo

commonAnnotations:
  argocd.argoproj.io/sync-wave: "4"
