apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: rustfs-admin-credentials
  namespace: rustfs

spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgCR4MYxtmmUE1Ehza47XdF/bhcCS4BoQcLnH+es/yyc0CDSDK1/N0mmSaF+B4WiOotukVOtwgBnnUV9qDgtEZu1hK3xDcqKSyVN5xFYG/s/NMruwbSVvN3FQ6W/aHK9bk0W0ids/4Ffiu3PWm/ph6LKyh3N0+AW9RZK2dNrnm8TEUvK0mnZyUjWFuVRKfgazwrptPMPKlllKmVxaU3TMHxhcu1/Qks+06ql34ahkJW9kk0AwdeM56dDR9oK3csYd9xufLr3QOpZz56B9MiRSj67VJoiu9q2IqCirBV600Kaqk61lSYhiYN/RPMv1Z+AYmWeEH0J55AwEZ9PID8uH0eey5033yrYAat3IbsJ9djVFE9mETKTssih+hP5KNuDoNPGvYK8SpThJAcCYi7/F0od5Liv5g7lFHi62CVh21G/IBAtcxNdXNxf3SkoFQD0ATUhrDpg2WrblwspJP99CUHf3s4a6E05r3kGxDg7u7nnzlpkbrUrcPrornPZJSNJzVQSsvPQXy4B0w3IJJVVPTvaknx+hMmPftfqQ3YmYIA+jfTHa4ihlJ6LgVhazrzLQXPPrNzL0ulGNqYYJfluJhEO75K9sIDEK8lMyEv4uvPJ1BNR4PvdJAW2TnL0WK16XIsnvrE2s7QMB6W2ysimyVkkx8yeinoLCFCU0J7sijhVLQ3AW1lzfOEyfwtFxLqjrs+Z6WuarsNcdTpY+A==
    RUSTFS_SECRET_KEY: AgBT83+d74IbXauiYfhANJuKxvp0q0kTE6Z9gBe/1KJnw0VWBRn5LIpCpfPFelGgbb9CEGkG8anfVFfWujoh1ZRS4hzCvnWjjyB8N+jMK9j81LqlOYHf/tdDMKpUs8iiJp+kt49uwRCgZyBMfSdgSGm4iSmGJ8bKcm46Dw8iziX82HBHy+ISp+A9NHrtGE1eYU4wzyMEpCAhr0UduEyZ5jk25HhIeTzzWgz5bOleeiab1nm1zinBRWCznRI74HCQJJ4S6gzb3vlnGIe5V/mLPBApiG8mLGH2q6SF3wmfjcIdh7EChc5i6iXMSqVPMVjO8IrdVv/nm7PsVUMCR08AeKQ/lxZanbWzaBuL1YKwEC3YKGXj4ud4020UrTY+y0ejHJQWVX2jUb6Ypq0VzoR8GhgtuZzzPeA9usjz+/jFBEeL17gyxvlDxnCj8G6GUGxcTU9nAE+70DtTR7tfQx0oI7ZpTnAIjpzdbBxGwPu4POMyDQZ/MyC/juMQdjVR+vdCQQdcQsarhAOjeK1wK22WOF59M87Jp3rM/goLWhEmmG2tV85aqX/meN7XwNS5lbiqwwGLf61uypi7fPHQEdTN7yKc7ct0HY3ZDKtV/1T0psUSiZh70Jfrxr68M0aSkbV+Ueiq/UN5krK1935QLL5nmvS+n3KeYEVhDjIN1zdIOPynhdxq8kZq9+kOXw9Ln8t8U3NJKRCPAmD/hAHaQpmxObP8gAsO52h6m7fOn0HeTJ+V5Cid
  template:
    metadata:
      name: rustfs-admin-credentials
      namespace: rustfs
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: rustfs-authentik-credentials
  namespace: rustfs

spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgBR0BsvjeDMhisP/q1RnvA6huGFXXu5a63Qu7IakWexlk4M2V14ndA1LKL1tCHMqB5jyX7lq5GXF9Qvl4lO5VJytVs81+Yx7jKIvZfeOqhcULvwbjtT5id/nK5270EFIrYvPMnjA73zPRpmvL9eLtQ6s4Sk4ik28gbKcwOdKXew1EQ5N1zmNr+3VVR7gXqF0HQKIoqqCcSLcGvImL4JQSeXyaX2Qnn5CHhB5dUwBK8k+/9mJssba3d6BJWVP9YrNDUhGQ4TwY2w40C08ys5DHmxM75Moob7XZ0iAQhWDQrOkgDGe2x5nWXIHmBuLgdeoPE8JsWRydBVMvbfoHlDh55VGVgsj2cr8IGWI7iv61H7lmpTHrI531e+9BRFheVt+P32HfV2X9NnZRdL9ngG0kx+9zNFzIktls3HyOgADdwsmjS3x0dO9tJseQKcRbtzdiL4Rab4Qklw8LAJMF4qy4e2hDzYmyW8voxIilOsMJV4SA7Rx2U1z+yWkPdxdBvmuOxr3UUiRFGWVIC+PxKkYpG2rkRpkKYg1edLzvft08YYSciwuQ2iLeXpVLtABfiBbJV4MbWHBn8l2Z1a4UcWqp5XJcgG+FUq/nXL9DMniVODLBahcC0gMBYDnJYygmWUwN2/3//us+2IAccqL8aiJf+89Hf1LJH+wi2iteHkKxJAi9i7OuRnIq8OF2fiJ1CSCrpsN/EL/x3C9mI=
    RUSTFS_SECRET_KEY: AgBT+8WLtv4yB/ZgYgMy3Jo7jxTa/HxlP9JnEqmqlYuQ/5CYGmJLlf7VitEzf5ttUZ7N+oHJOs+OMJTesEN56/fdJzWe8xjLrwn85hXpciwW3f+IihxF04SpakJU3PvBRfhi1jHtNKzkNmw9VbubY2Q0FmeF40thmdyLBCHP+9nUGzMpDWZ+DfNoG3NsSv9p+rddzOcomlnCTvXCIIEWXem23R3WBW3nJqmo9gC2Sz553wsL9xnwovwVAljMEVqufQZWogAn896jlViChPu4d861sjNITYAOti9idLFrt0cOS1diUSbq+hGCVgDqYKQNf/4zXRz4lKClxJm5aXDwh+WLc25FwcCNU1BxOqkPtZIVMJRVnGYnyYKa9KKBGN2aOpb2E1uXEvVebQuSuXh7KnyTfihB42VrQEtP3VI9hjM1QSWzzK80Sw/7j4xCY9UclJ0U1CGmAJFD2WmF3ZuM8jEqk/4sZuhRgY1bhg0Y90EmIXFqo5iCkuQRR2g4pjtwrPwmqEEGBDKB0j6s1HDNYGSNWrPO4nUZyiybNC3iHUw73VE6L7LTlWtWR0qHLBvKowDuS/Yu50FjH9Z0D9acQqDXC8v1FSStu3Z4Ju4fV3MuEcP9fHEACKPU0JIxu7oswtBFHwmDOmRuwmNF/tfgxM2xVg9wE3lQzZHTZW0zQF9e+G0mSkJy5SLSU/qIiRHFrKFJ1hCMomquKC5M5Q6eJu4Tvl145UuBHzB1EJVVo+vF+zfXQhSVz1SkaRUJ31qzrYg=
  template:
    metadata:
      name: rustfs-authentik-credentials
      namespace: rustfs
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: rustfs-wiki-js-credentials
  namespace: rustfs

spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgBqfYJP6n73/XFzT5pga20ztvfZZvuZ+b+kGD5nP5KZIafDhuUzm7W1ZZdlFk/rYWRPAsksBrpm2/xSCwoSumSUdmKTvYDGOnTOUpRLkF0QAdRMoQBJz5vtTZ1ze0gLrzLcDMIPmtgFsHIfm73M/1Fb3b41flL9vzOj6+ULFyawZBfc0/DmhyM2wzlRHLBDDGLOKDXpFWbXvfx6ouZrA7MA8SI7uOPFbBukTzyScU4Bk+XA6D/P81HawMTch1qL7wIjQjPe3QbRi6FxCiI8T0yIoaF0pW7UMFkXKW4p0+8Vcq/Up2X3J5gp3gu9ppJzsmoK40PWg0SJpPoxsldYwU9LhYimRk9a05WKQnidKVsDFLsr7tUdSZ1WYxPy6+UMQ0VgfLPoE6wbaNMc36EMlBHZfnfSO2c9S0um+qPux+ekD038ZlwU+QFOqigQ5MWwsOs5o+ihg6nwD7tkQlugRiXJmtwgmJBJoQVhSgPkztxm1v+/Ah19BMFs8lxA2uxCSmhmJpl4D+sHjWWhYr0THMdT1bHWdl2DZp1F/7+jNS3KMwrfdsRt6opRK8xBIxXRib1tFp3bZOW2Ez5FI72c4t2CLklL93Qs9CdQrnqf30OgXZqYZ1WWsc6jaChJTT4R0NUZqdHodmySSA79vPTfP368alAuMU+W9V3iAUNo5/7gMoYs/+Z315Q0UtWKRbbTa5zZ2jR17CRB
    RUSTFS_SECRET_KEY: AgCPUO5FwmR8080xl0HWIWo0Xyk7HDJCtb6X8epJM1ZaoFnZoFlHbtrimjokiohSaYWuSuq7J80VisePvcHPsjJcg/tuikvpeB4jk9jZgZ2SSd3/MiaqJwmPKdivMws5kSLykYhAiJgIIBFB8udDTXYcmaEizFUZtiiBAPlv5xikJDnoMiPLubSXGGe1EvEz6uD4NFl0Kf6YMBkKbSsKCx0B09wAHWUWd6QvmDngNZeuudTtQVRVr46g6A209KoRc+kft3rFmKDkD97jsDd5bvTgV7XjcoBu7l0Aa6I2lyb/1wy0PaAWG6u/fxFlJsrIj301QXqUsFC48pfNkX13wLxTXqZT/E+VYw3vB9ucW8wkIlDZsI76qL5jOJxXrdxfrP6P3pGq9YiBH9pA9QKLMmUhETNfj5JY3JZmPLr+ysVS/oolsecV3CD9uY6gu+NP0bxZfooWtErxfuZAK9bb5BsxELTvo4gJ+nwom25pMfxQ2bNkjeku4P8vcpkgR+N5nrLWWJEXeLJrPqJpbJ4dLrzO+DMqY3oTJUt+rVSctJpo5uu+XX9EDh43FjAaaXp0MGVRDOTEuai5hlWFszMWY12FaBncAipjTIKyme8fiILtvK8wwtTzZiCEem0qDHyJo7wPW6rLO0cWpEBJZ5czzeTSzinf3nU9mh/effVU3F8hGapo8GjHpch5ncbzCeYAibRtKhnbDS7eWvyou4sgC1klhXLaVA7tYkx3rhL8aslH/iGuS19ME3mSwX+SiMazmmE=
  template:
    metadata:
      name: rustfs-wiki-js-credentials
      namespace: rustfs
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: rustfs-timescaledb-credentials
  namespace: rustfs

spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgBO/iiopYxisRwjrDJUCrWa76f5/QwZl3vfDoTWrW3lqRR4KVCWS9fwV9WBOWvx0iKFCUL40iqRAymTV9E/FmiLVbP229HijrgfrZvmBc2e/nCSPgNOTq449ykluYpjixbgJcsq9pIjk6VD3OcXzLFitaSui1K173bZ7BSBF/+zPtRuKMDUWAgRAKgUyhf+YaeiN25o86Hk8HGDxFMPEOi0MdhkF1b4IiSrDQlbXmW0V6fCUnriuSN4e11Jtl4vHeFOHSRodu+rfH7vYoyxm2GbMy14HXFjmUtYNCUZYoCNIi2FaaKNsM3UH38ELIh22rUSe/OGtyuSSlHbROg1ZG+9DmS+zeTKkEhQwrneA/kT51aJhm9V9BMRHK8OZXEjTyJ5JX5vDAMYR6i8MObsy1ujaajqJGRV+E+zGtPyvA5mKfRt7n/YHqw59hqFkxphS8J39YjOx6I4TkAacoVPj/HUNR4iNEd0KYA7gglqYsrwlROVdGU4V4+/ChJbEzdELtaXAKliovuH4qTjEKb+gKOAkQMJzxUAPK6B+mx2fVA1AHHl8I3MnyJk0Ayn3JQqzBRwQMMVEKBUu/S+gtgE2ycFU72/x36kwLujPhOuPINu0FcWjePSk9jW/JmTFkgN4ileq4nC+6LTL5ztDUimYUJKqofsUBCjRlZeK2vp51VZoUSeFzGzf6HtXpvwntZdPVbX2ozupJrh6PIBaQ==
    RUSTFS_SECRET_KEY: AgCJvDytLCh/OtmqR1TPi6+QvOZquerwwgUyI+5i1dlHG+fEICnc7+PXzISPP0G9YNX0GMDRNY/9bo2OoykPMEGJ9bsfoW8HABvoz+k2GJNEq/HKUDZQAwvLFHNF1NBOm9i5X+F9j4Z4k8fVF6+ZjT6QoDgVsmAzl8lKqy518elmQ123778z4fPl9GH+3pvuL3FH1OGDPeKjvPK3JiCPhQkRW/oHkT5TOjYHR/Q/gUHjXOOF+iy1nF634fkAefhT6Hz9gsbs+/Uh9rhisZ3mYPNrY4tQL2TQCmzWJHJrD98qI2T1HPEpef9Y5pwHaxy6L85iSSWzX9ydCV4swowaZUMxdqKM8jZvIeXPWQlplUBNu5mj6rGb8aG6d+kQsfttKm2RucpyfZ8laAydmnLPyAD9JnIP/TQXW72WMZs+fLPQHcy+ARjhveOUcw23Zdd7/i7WpAIt2SIruSH67xP9yZAC03fjo8ZkA8btusIQUC1xgjraapcgTEKt/XmcsoZiY3RKIBmB4pch8ff6EsGlsR111EyXBAXgQl0+KXOn1ZM0yuTUBo8M++3IInZYna5NVfhmwseRZzLcoDbLnR8iSxNyX8YR8AMwthjvNN5mg84uuGeqUH+hFiVHwVoQwknDMqqPqu0f4mRovi23txm+1igMwlsZ8V4o+IV1xxL2yNiK5gqy/pG/4LE+OCr8fonmyytpY2WUxhO8gS1QtWAoDxnriD0knMQ0UuKeCVXjn69p4iJiN4qnBXhJzCGfb+gPapg=
  template:
    metadata:
      name: rustfs-timescaledb-credentials
      namespace: rustfs
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: rustfs-redpanda-connect-credentials
  namespace: rustfs

spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgBQL3lp7yKYVdLO1XLuOVL4ND1VE/PMl7pY3gCu4/nqZQ9fJNFweJXrSx0PG66ukq01enEeHoL1j0S7vVh5IasMmTNI+erXyCBiUqIpVQshJP4lIkhqU2k49sY1jVazMef2FQsA/dAdmtB/vX3Uc7kDz3UqbIMh50WWOSGxyfDLHtKWQpF7/Q7yXo/4zQw6Nl72pP0M8kh4BsWryLl9l8WN2BCC4t7T4ws0OjG00xX3d0y81HxEwewiUU0QSLkZM/EhLwtZyMtMp4lrvgGRTaaIISe1FTFiNLVcG+58He/1V+xhAAUWzbYFbtCECIyVVoeoIX0wdbhkuYxnTNneREiOx3R/jAZD4uFWnk5/dV94pn4nIsu/uEbElzfVyQl5YqkfR6Rj5ri1UbltOyEUsaZAyoyQfpsq6aY/BkuJxpaQpwyBrN1cyqTdHzr3Ocbf/z9kwrH3fN9cSoZt0lH6MR99pnYx8X592QZcrfH2SFVPveLGDBNodY1Gdmfxj9+5M0iaf18T49hey7B61WWyeVew3hl9yTPzrzwSrjs7t2+pnyGmRuNDpeU2esmAd6d1pZOtkED3TqfK8vkQoed33T9P6XuDoVPnoZHvr6FbkpE4wFYFket7+HzFsyGeqSQDe8zRuI1BQ9n/w9KoelpNbzHDab/oYwYryjUURPkbZ398O70gN3E9AMmJwwykUPFAoN/sUQ5NpF1I2X67N+4/KaiV
    RUSTFS_SECRET_KEY: AgB2WQCyYnUmEqEEntnCq6qC7qIOflBhAVjFg22yBMwmzs0neQxXZOF9Oh5LvOmId4Ra1ei/57kKfik8vaxXd0V9LMwd/UywfGpiYS2F5z2fojyVpFCUxGwB1iBhXu2zEbLTwLxna+26xJjRoQBYTlnWCJyO+3xrZPfzXryPPXYyaoB5o8GPduQoQFnobKQLCri3eRvJePN3PDYc0VkAlmHiGTsrPeXllHqUG7aLCWni/SBrSqFZfBFWGVShkXI02pnZR2/9j48ZP+LwBNs+6KEyrr5ml07hnK1Za1ybBpVO8XwuI+wu+PSyo1IvBTUH3+F8oY+KrmqTaQ+s8UcE2QFl9IOhuwn1851v0AGmM45Rngrw0LZg1JCcEmwAqmPkLr0FD+1hRE3Qh7YUYiiO0d1/+UOcD+0PijNLPUmaXiHsRakJTGPpXXrpqZKY72vd/oer8+itCufFFe4UKMc8PQs30GdVkbswgF/MJsJ8kh68bkn2pE72W6Hv55efb1cYt7bRzISKEy6TtlRvNU9Ta+HlaLYmgratO3rK6rMf8GzB/aOdRCgBGnL7Na6+9PG3NnVLNXQs4vFho0YDu8tjJXELZzetX3XANTOZ+hEWvvsfXeu3ZBj+3YaLu9ZWL2fLFsqkM5ju8BKP4jtEsROOmF+uO1Vj51WrpFVdK0QAvHedHgdtHPjD/1R5f5AzFBD+4IRv5NTp1s8u2ZxhOrxjGzdysmKA0Y3svkZLGsNnU0fxD1gYyJTOAIG8RgntLIoAgCE=
  template:
    metadata:
      name: rustfs-redpanda-connect-credentials
      namespace: rustfs
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: rustfs-iot-insights-engine-credentials
  namespace: rustfs

spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgBLnO3emf7XWw9an1QJjPDtOiKcpo1fa/owlJoCH17hW4IWhkzHGy114fUip1PoKBtdqhHQYxHBGyz6c6fb4bFOnUQLEAAfQXNYFrDoeSRwHi5m0hdDdLbeGIoorXR1NgXyJHde6JMc3rOVtHSQeNdJdP8t8v3AOhesKJtJfFrYvCgV8P7naR4lz1qJjfcFjEARsQOpwIFlu/1cQxYVOlI4BZDka82KygG0j+rgjjOqbR2jOxWnADfRo9xXOU3t3I5iPvLeq0KdjHtuKuitazA19py6PsVhmibbuDl/SEtPf7llIaeiTBDTwMraZTUICRyRrZidVJ+eLwI3EeIv4nppTVdOKOSmj0yhmGVf5IZ62d5yBRXDP13S/r4Csl2uS42GZQejWpjwoz8QZlppiMmEyP9JOA6e4LeT4R/5bbMpNgAIyCcK06GbY6GkVeG7K0oglsRAmocdhJm+4gGj0UPNBE6uaiPJB2jdXUkuI8KvbfaoYg/G/OvBtNdt19eqGOJlsva7V+vOEyVo2yQuM13FMylLozQsW1bwoDgz2tPUwW0PBN3n3+7f0kYJycgu2N7crwsugB5OVrp+WSfkM8bUPwlkNH6ieJ3aHq1ES6h/9jyS655+WvmIeUFTqehfkzN23ubEfNCNF+dMczoz+TOeevJRhl3fISZXgRKRFMu/uirN6ElqLEGWmfPQqryMHT8bjsBmWsLKk4LOqj+Nr66Nsgci
    RUSTFS_SECRET_KEY: AgCVJ34VmDKzHu/utmIHT6FTzw00SMzIcy2Cnyc78rgf+dhtKMR/u5xlOQ579KvolKrmXS9Jc73y/3166V+LcjmEm07AG4qdHXgTZEu7Hakus7bbo7bgs5vZ7iSYCdPsqzZ178+dTCPaKRTntzLt3ZwV+TMzdAX05d3Dy1V3FjwPy4glnXBs1Cz5FtUR4Ff5j/SKh4TNrTykz3SwPso7F98twCUD1wWmsa/IiO8tuOhHgrEDadT9V+wKs5EJc/2OBq5ZV/R/N1mm/mkVAY1LvSqBkZvNAoz4KAEhuVHcGq4KxDF07iY8m90eLkzJJo7Gbk1QLeXBz0lbSRWWjYpfvcjGvemWvdgvjr27OLrsgvlvj96+qhEW/r8hN3Tsql6wZGwRdnxEcQA55xYHQ45IYb8qvHi/XgrmS/6fl/A4zn4+qLwucUUK7/rg/KOLGbjxUwxbojtrI7vO0POX1n6/y1T5OnqtgptGvshcKO/Up6a6mDk8W9H2+k1gB2hD06i9z/87gcwLysbqJ7y9P+wLY/p/26TfZp4MXP+E0zukvw8ekt+hqgbg/Lvqb1B3xYTMOyZ+uKMwUhXLdDoliZJr0isaTIEQVwu9P29ppGx0d6Kc1DimFodB76ZGbphEvGI3j4QxacFEweBhMcjGeBInkhTQirwb7BtX+j9fsBHR7zkNocBQGhwJ96T0eKDe/y3VS7c6d5V6bWHt7kj2WKMnWI4lxW54oKyd7EtVaVltXVAWgp7G2p2tAnwUqcJLEOT7H/M=
  template:
    metadata:
      name: rustfs-iot-insights-engine-credentials
      namespace: rustfs
    type: Opaque
