fleet_vm:
  ## Cluster management VM (Omni)
  cluster_mgmt_01:
    template_id: vm_ubuntu_noble_cluster_mgmt
    vm_id: 1002
    disks:
      - disk_interface: scsi1
        disk_size: 16
      - disk_interface: scsi2
        disk_size: 8

  ## Proxmox backup VM (PBS)
  backup_server_01:
    template_id: vm_debian_trixie_proxmox_backup
    vm_id: 1003
    disks:
      - disk_interface: scsi1
        disk_size: 128
      - disk_interface: scsi2
        disk_size: 8

  ## UPS Monitor VM (apcupsd)
  ups_monitor_01:
    template_id: vm_ubuntu_noble_ups_monitor
    vm_id: 1004
    usb_devices:
      - mapping: "ups-apc"

  ## Windows VM fleets
  windows_01:
    template_id: vm_windows_11_25h2
    vm_id: 1100
    wait_for_agent: false
