apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: unpoller-unifi-credentials
  namespace: unifi-poller

spec:
  encryptedData:
    unifi-api-key: AgBx1lR2fHolUhnYz1BfwdWJotIY02k7trOAcM67AGJGRAeSMw3ZHIW0KpM9tuPfJk/SKZKTVasg8AOehJqYeziASMiLXEsPychFa01kk9GZHn1LBZ4G2vp8MJS6S9LzdLz8ia8KxAMaCM5KL/f5lNqnShu7K0oniTVVRFFkHi7ZuRqjYJn31NrbM6iELO1uc5M/GOQNO5jKdxGr+cWcoLSeSkJI8cxjrwvJSncRqjOvfDM9PL2C7twHP8ZkF/1teEg2eNu3+2aZjfaEHkNnMvh9Iqi8OkLX7XSdMG/+vU4gf8KCdSGl1Cp/MQ3wSTCRjDP3xjOiXPqvN561gVWmwD1jYdJxUpd0CsjeZvF696wd+bMTp9EzZsLtbbvFez7Vzql4AMYeIChCl92cPcqY/Qtpxtd+gzlLc0gNtg7CUEEmEmq9mSsVwdD+NYViQtVI5n13rlMinrJF26gzSNCR/Rw2gXqge94/D41LDJYYsSNVC1c1fJPIiLmumycvS3tlW5x+AuJ4ZEbv1fr+EVK11jyz4QUPd4aZaDmJVI0/MZ8T89kyxWSQx3OfG5n+XT7s0vhdb503F5aSA62xwm8+Cdlp4CiS5RNiLCjtJvNho+F/bRXNL8SNcPOR0QQc/ZYvTB5cCdZhNZ1txP1scb9ShzcUOf78cHW5Wq4M6PkXB+NLxMVsqcf8RtO0kw2hnpMiTEZcRvIERSyR8XrLqH9nk0HpICGxYTdO62lHfUYnKZVjzw==
  template:
    metadata:
      name: unpoller-unifi-credentials
      namespace: unifi-poller
    type: Opaque
