apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: admission-controller
resources:
  - ./namespace.yaml
  - ./clusterpolicy-secrets.yaml
  - ./rbac.yaml

helmCharts:
  - name: kyverno
    repo: oci://ghcr.io/kyverno/charts
    releaseName: kyverno
    version: 3.9.0
    valuesFile: values.yaml
    namespace: admission-controller
    includeCRDs: true

labels:
  - includeSelectors: false
    pairs:
      homelab.component: admission-controller

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-4"
  argocd.argoproj.io/compare-options: ServerSideDiff=true
  argocd.argoproj.io/sync-options: ServerSideApply=true
