template_vm:
  ## Standard Linux VM templates
  vm_debian_trixie:
    vm_id: 10000
    image_id: vm_debian_trixie
    os_type: l26
    ## Resources
    memory: 1024
    cores: 1
    disk_size: 8
    vnic_bridge: vmbr0
    ## Cloud-init
    ci_user_config: std_linux
    ci_vendor_config: std_linux
    ci_network_config: std_linux
    ci_meta_config: std_linux

  vm_ubuntu_noble:
    vm_id: 10001
    image_id: vm_ubuntu_noble
    os_type: l26
    ## Resources
    memory: 4096
    cores: 4
    disk_size: 32
    vnic_bridge: vmbr0
    ## Cloud-init
    ci_user_config: std_linux
    ci_vendor_config: std_linux
    ci_network_config: std_linux
    ci_meta_config: std_linux

  ## Cluster management VM (Omni)
  vm_ubuntu_noble_cluster_mgmt:
    vm_id: 10005
    image_id: vm_ubuntu_noble
    os_type: l26
    ## Resources
    memory: 4096
    cores: 4
    disk_size: 16
    vnic_bridge: vmbr0
    ## Cloud-init
    ci_user_config: cluster_mgmt
    ci_vendor_config: cluster_mgmt
    ci_network_config: cluster_mgmt
    ci_meta_config: cluster_mgmt

  ## Proxmox Backup Server template
  vm_debian_trixie_proxmox_backup:
    vm_id: 10006
    image_id: vm_debian_trixie
    os_type: l26
    ## Resources
    memory: 4096
    cores: 4
    disk_size: 32
    vnic_bridge: vmbr0
    ## Cloud-init
    ci_user_config: proxmox_backup
    ci_vendor_config: proxmox_backup
    ci_network_config: proxmox_backup
    ci_meta_config: proxmox_backup

  ## UPS Monitor template
  vm_ubuntu_noble_ups_monitor:
    vm_id: 10007
    image_id: vm_ubuntu_noble
    os_type: l26
    ## Resources
    memory: 512
    cores: 1
    disk_size: 4
    vnic_bridge: vmbr0
    ## Cloud-init
    ci_user_config: ups_monitor
    ci_vendor_config: ups_monitor
    ci_network_config: ups_monitor
    ci_meta_config: ups_monitor

  ## Windows templates
  vm_windows_11_25h2:
    vm_id: 10004
    image_id: vm_windows_11_25h2
    os_type: win11
    ## Resources
    memory: 16384
    cores: 8
    disk_size: 64
    vnic_bridge: vmbr0
    ## Bios and hardware variables
    bios: ovmf
    machine_type: q35
    ## Security and UEFI configuration
    enable_tpm: true
    secure_boot: true
