apiVersion: longhorn.io/v1beta2
kind: RecurringJob

metadata:
  name: backup-daily
  namespace: csi-block-storage-controller

spec:
  cron: "0 4 * * *" # Every day at 4am
  task: backup
  groups:
    - default
  retain: 7
  concurrency: 2

---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: trim-weekly
  namespace: csi-block-storage-controller

spec:
  cron: "0 1 * * 0" # Every Sunday at 1am
  task: filesystem-trim
  groups:
    - default
  retain: 0
  concurrency: 2

---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-cleanup
  namespace: csi-block-storage-controller

spec:
  cron: "0 5 * * *" # Every day at 5am, after backup-daily (04:00)
  task: snapshot-cleanup
  groups:
    - default
  retain: 0
  concurrency: 2
