apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solaredge2mqtt

resources:
  - ./namespace.yaml

helmCharts:
  - name: application
    repo: https://stakater.github.io/stakater-charts
    releaseName: solaredge2mqtt-1
    version: 9.3.1
    valuesFile: values.yaml
    namespace: solaredge2mqtt
    valuesInline:
      applicationName: solaredge2mqtt-1
      deployment:
        volumes:
          config-volume:
            configMap:
              name: solaredge2mqtt-1-config

  - name: application
    repo: https://stakater.github.io/stakater-charts
    releaseName: solaredge2mqtt-2
    version: 9.3.1
    valuesFile: values.yaml
    namespace: solaredge2mqtt
    valuesInline:
      applicationName: solaredge2mqtt-2
      deployment:
        volumes:
          config-volume:
            configMap:
              name: solaredge2mqtt-2-config

configMapGenerator:
  - name: solaredge2mqtt-1-config
    files:
      - configuration.yml=config/solaredge-1.yaml
  - name: solaredge2mqtt-2-config
    files:
      - configuration.yml=config/solaredge-2.yaml

labels:
  - includeSelectors: false
    pairs:
      homelab.app: solaredge2mqtt

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"
