apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: midea-nats-bridge
    patch: |-
      - op: test
        path: /spec/template/spec/containers/0/name
        value: midea-nats-bridge
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
