apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: timescaledb-db-connect-secret
  namespace: timescaledb

spec:
  encryptedData:
    password: AgCSPjOK9EeXYsF40om0kaWlxkpwkz7x0hbaC96yRjHAZ+CFj0Q+oPH1CUmaLiYEu28UdHb/7T4SjkSGjDfD9YZYae8X979yzA6OC0251aZuJn6prd7G9Flf5tqMczaOd1D1lqEFICZFm7hJ93X/KYmyni96BkR43cSX3yq14L+ijHMeXoXmknTVPJ6Q4JarBOm4ipFsSKQwA+SoAdKq8Qt9mTyGzm3MZzFO2yzXypPmTtThf+dtot4LFVXQzzOcG76YLiMJJKY8brX6pqfLdJFiiUl7iPuVES5euvlHisR2HdtjkZHBXfclBgGzi3SeZRH9c9Rg5k2LpB3dLBI4dnds6RnWaPmUZ4HXtME3DScUHtiybZDq725O7SlQjZXB3kG1pvKDaHw+f0QjJD6SoloPEy4UHOXfOydJTCilOd4dG6lQN+Oo2qI0Q2gBlGGR+Lr7KQ/JE+ymFi7QqgiR1EDTPVNpemqV9KHDEGltFpqpTOfz7+CPatnh5kCneciVDOTrx3t6minfLc5d2Cnk+mXVXiEpcgr6h9FeAnvR/z9m9KiliRctlcTtoIl2kS6enVREO498aD/BgIz+YCKZXc0DYNm/6Vyrr1Jv4OWJJ9Wiwkhd8rZZ2su5QCZopIv5RNvzoVyvKHzoWGe3AKlKWUx+uspNVhataPo9+z0aGmXd0YZT/XZcMiQMHlE6BcJ/2gKJsg7AXj00dwE72yQPD6VEr01nHydXzMnzJH5MgOs4ug==
    username: AgBrCx0WKFvwsOETREy2JqqT5wf48ilnFLnBrqUNY8kHFAo5mlDQMoyzs/I3gpu7UOgmJIP71qDXKgyDezKwN+Z92gLvJ4nlIDIO/H84p0SVH/UQmMSDKq8z+QQ3I3o3lXH2hFisfmyjmn9W8DVCT/eVnazJwkCnETZQfDcYJs1lVDIIy7rRyYYYioIiALd2FdQ81UdQzLPYfm5aMwPgrOfAwy075Xxl7In7ZfZ27Ojwgv9+HntUzaZXV7iFvIaaTvCIsRGQAYqqkk5ZLVG9YSBfPJU6wHheERJhGevepNPnGIMMGQkwZw8W8t7ztFLDec0Da2CXsWaiygs+KoaGqZTwK+FEqD0mazRw3gJRgRtdYGwhHUE9ekSoGhKAkAFYfIwY8wfy4Din25Jl6ov/3n8mJ9i6vqYN9naSMiznj+sSe9P+I3O/L7+PQ9rVwLjR56O+FZOZPdpQn6ecaGlNhpjTSCX5abMcBEcbyjTd+tqyniCO6JJdBoy+ByRv7RIHUO9dWcBIyV5NXfD4YGCfnUuyZDzF7ZUVJfRzg5sFI2PadNt+O7JQUVb8xw5bbj1dw/5o2mshsM0dtGR5KtyoDoNNxPWS5Z8B4xi65ddJYHLXV5tLX72OGoM8bmWcZcbz5SsUtVg9roZf9nMBNMyjjSZ5rtl6FJ3VQhmJI9qtHLrTXBRX/T/FBkKiNas1kokgWExN1awL6GFJ
  template:
    metadata:
      name: timescaledb-db-connect-secret
      namespace: timescaledb
    type: kubernetes.io/basic-auth

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: timescaledb-db-iot-mcp-bridge-ro-secret
  namespace: timescaledb

spec:
  encryptedData:
    password: AgCFh57NPU/8rK5DgrrZyvhvAVDATg641LbDfBtZ2+RxWsRZDgZ+Dzayjwf30hSQ/RTeZ3okmh8Pwe3nnWfSjsp99DRZXlrGY2l1QLByUH2DhzI0CmhISfaNdooZXhThllUvfnBlozr7FaeMFoluaLkXPjElREKeSfYLRh+HbaTUIVc/6IDKY2K9+aR1pzsIV/XXQUHL+R6Cdn3IzmVIbTUrbBtby1BOvnndWp6Y+vxnz/q2l092JRTS6Axqr4rzvUV8ucztMkCiAGIyEaZ6fNnIW6pNexoifLTkgfwr1KCHLhhqiyeYxYugzu83IKFQEFkFGLErWwxTGfR69WT1xw4wqN3JtdicNeHCMlhV46gD0a9ROpSSYMonRLGAYChMVfPmsOfSmnCKKaIal/zq70MTBMKL0CHFY/tdjG9ds6K5V6ZC/ruosLhtI0FCPm5coxmxU1uJ0YACSyBZqi2KTxDOjFGr7qBQUugvk4E0y8Y2eDBatTQdIhsCvzRuRDun3bUzGqWJJAHe2u0Se3hcUC0lW8jl6qkvNfD+Rvy8vH2QAItVb64fYy5Q4tEm+uss/LAq/okdCNYIpkNLX2HDki/GFzGDpkBuuFD6yf0c2yHSymyLz3JHivs/KjE6hJgtjOvbXKovH4zzyi7OSxNAAyIBHu7d/wzIW/OekPThAQ8GoQWJYhtPKZsTSq7ZD/g3IJIeemQn7DjDvvgJQQMG3sAs/mu5R7DWM3NlTxVPYutWeg==
    username: AgAH84mAe5hUcbLzAyAQbHItZutuCmdXDeUna7er3Nf2IP1hOZKC6N2G9Eoytv5YZbTQ+qPXfD7U/dm3a9SDlSTw4OGLDqjtk0g5mrUyN6fZ1MRWPghgZS6ZpxDFkt28FvtqmbX/Mlf2QuQcxIdDIUM6m9PWgg5t6zlz+F22lb11sKwN+Iggzzoy2aaOOnzzyuDosbORjAcJ5LUW1Jr1Rj97IVkXblbclG7Qr6NFAbFbivBZl+5vBF2s1Q8CmujscbCGxCBEGvExfXwH+6VL42OppXVjHXzDwdVcfNvBzdneeSVBqGQMb7Jj8/Ta7AH4wE9hmn0sKkeIQPDML5/vbmsRTxq1n4K3ePdLB2EwRCopNlT9WJWrykpOqilG13YD47DBWKRJc9k8A95Rbabrh58z6Qb40zpGK2JM/2IMAhV4iYFlhOg++cwEMAKOYxttfVvdz11ZXJ8maRflnPS1PCUy9bWcSmeZSupjW7ACUWsDpGqUXdMCXE4Bv30fV2Y5ia1GOPHHx8Tj0mIS7NvJQ3ajWs50JzoTzkqvW31JzatTarw+ayx+b6nL0/UkEzMLegEAdHTbX5nKyf+A2r9iuFdz7H3fr4a4znMgzI01YR8DC5dMWzviYWAM3HSXqIx34hK2KEiRcteTKZ70gHacsuLCUGhhw/SLnqOU7ogQk/5aW7UqzN/lc+rbpll/kh7j8ScoMmOwJ9+MseVH205kM0Gj3w==
  template:
    metadata:
      name: timescaledb-db-iot-mcp-bridge-ro-secret
      namespace: timescaledb
    type: kubernetes.io/basic-auth

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: timescaledb-db-grafana-ro-secret
  namespace: timescaledb

spec:
  encryptedData:
    password: AgBXoH5juT2ty4K1gaehPrEW18KdXKlZLhyXWtLLbr/cFyertTaszJ/tQ2nLwVItilasLlt/t1a3P104Km8c1NZ3N4AJbwkNYlZvq0vkvqIIN3sYLFwr05BXtZWna0J5GY7dldU1eTSMwRZbeNJH8vSXIE5F7mYpv0T/iI7bg83ZPOcosKm2MxAsUBatzcb760pWCOv9OxXkjIT1OsVIf0KVmM8P1dDi3ad/dsYdui57uiGcSQDDIgt9mdZVGT/6x4lnZlyzCD0aIcHkApYLpVYfDOjHGBijLkzQjETpetxGvtRmJj1uTzNd97TK/5q6QkwUWfEb22amFn+l6WCTjwCt4QVYpB8btUkq2N5a6xWyGATxPiMWCr8ZmPmFNKTn1BxyEItcbPsHndbG1kAl5/uv2Xgn9ACgA7d34K6W5Wnuz3s1Uw9VtzzhsDzNsp61rENA2D/302nX32rypfINNpicOc9hXK7A4QRVFb2uRTumdefJ3JW8GdoamQ0Gk70lrXkxT+JRGds4t4eT+PpuxKqDDOSoj8IRFB53E6/skonxsyT9dFjmQjMjujtPfUN5KGPJREpJjGDw04hoiyydP6DWOqXW2e9wnaIXvNlt0Tugln0Xiwsm4pZVPj9h7etZAv/gxYhKeVOAo80+FzSaxSheCBIGGK8eRykHf4HEqHzdKYDI3aNL3e/gy6tGkJMBR0kXyBxfTl/g3qrQTiQhhlmUkXnZpetEcDbqWl1aUHWf
    username: AgBEIh416jA8TfCyfHRwZP/+OucvP9NKW5VksgKMAlnKJuNPsyw2IycM1xgWrZe9m0wivFlXWx7WY54mZGCRnenZ0adyMl9dDpOwGakF/6uVjKHiNVwVTl9rlJb8ZJH78F8na0aeMOKoBP4/dgPWG+z1b55Ajn96SRRGHPRDRI+wCsQfm2E41wHrfXl+OyzWiHulUksKkHbXwFrS9wwqjhohwOP9y4ON00W68APgXUNlTA36KYDUbpnLzkXmpHDegkTMPvLI6JVCf/JqGFVw1NBNoifBUxLIW+LIKGV++ZD7Pxc8IZF/Wgo+vHhgnqlSpltHlTY5IGGmHRMW3Wi9sJTDYDGDHWqz9UD+ML8Xuvofplq2GxNvev6kfimGA6ufnZgCb96RnxZ4gzjcZyVcs19456O9r4saLZlNmyHXOWQC2uWnNbBZUrs77Car5Cue50Fvb0CRM2ke3EXLRJ/iiioZMyShkeifkRvehVqovdExisRhXH4l+v3TP1qBZFCuipn1WPBimfQDcWWNPTTzUpbm7mJtSQc7lypqQTU46TATJM8X6kI20J0LCCEofC0tFm+NNJYs/WO2snMo6/Y1qS6BTfkRA3CDnWAS9P4QRWGPiIqKXUeDUjSy72R7EuOhk/qvL2zFvGOwUAsOGjP5XNfl87OX6aD6ahBwoWl1YrBQPMUj7kbPMI72TPatPfhdVucS9N2XSaplFCxK
  template:
    metadata:
      name: timescaledb-db-grafana-ro-secret
      namespace: timescaledb
    type: kubernetes.io/basic-auth
