apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: timescaledb-db-connect-secret
  namespace: timescaledb

spec:
  encryptedData:
    password: AgB8imz3fyHNw8VqiUM+tPqsc3+0BxAh1siWWCxBFNClcVVZOCLQldfWyy0Pwnr+FksuLVA7xG7y9hHy96KB327Xnjqm+STitGmyaAkls78w1f1HlGiYeVI+R+ehyH0IZRcHKYkogPexEEsNB1sA+3A14a81DVbEQ5lOclcEuZUZEDp1aMjp4An9PHdYVQQkB9qBIbZgbpgi7kfsv1eACamTcpct5cVm8SJuvVx/MezFy4bwIv0lG2LIZ304OyCAiJbwBV0ijR/T+alZGD9XLptG+WsZkxzkmxbrZynTChq1JrPYlHKw8I4BgFrXemgq70uTZsnVkMXfYRgzkA0HC33hn0/f7IZzTLYj+c14LPusta+r8fJ3faQUyJ3CpMsTv6NI6DG/hql1X0L5KOKRuGId3bgiaIF65ZtYFX5e+gLhp9/WPhH/GxHZMPHZpZM2J+fNoyV1qniuJEywEopAJawRq7tyBBu4AvldMWdmlWkimDgZ94bSy2IOFHvqYOkjytF5SBUfDbsF+/YJXN3KiOESLekq2/8u+1fDeH6fuz4pvjqPMHiNxuu8Ct+WuH+0eBALREW5BszzcuKCq3jtUKuhz7zJZIRHcFUSJjrY8gvfwEQ49R8zVvsX7RRgytSs+sno6MVq2BdjDhtp/s9MjKJdKm8cp2JTZMOd2WEU66E8Xx3el381XYhdavDGRFeq51cmvra0pjaxddJW3mM5XzcadJl/4+FpOo7zdT/KMlDdjw==
    username: AgBj9GSFtrjcV5UWM8S2Y5zODUdRjEiiWp6JdUFIhISdtUOpUodEGVNW2DAiHflGUgxzswrHVeGmpAHHFtIDmLzvpcuK+VDmE6qKykm3qI7DYi6OaXhPkhd/eBa1KsZ5irRzY6TLqTyjxtgyfFeK2lOYBk6sLiV6oOy9uWHYIWYlh2gL66n0dk0J2Im9YpXsXLh1AKJtDlPl/vUJHyjZa04vYkzdKdq09o5yCCdA0Z1zbt0lYUlvfwmos1YrdWPoDTiu0m+8JsboGzhSY3z3RsOltGppYIb4aPRRouVvhw27hmG2bRNlOL5PSLENVKK1XR4c2jfBf0Yu9ls/WNcYUCdSnCduxikkB4cymeyhyhV5FB1U/faaHPcwi4wb7LORuWdmlGosxs8IrupXyII5Uq1RYWC0UX0C7zN+hbTREcojQvygR9PJOgKP2UPyY/RNo+NVmUhenqtK8tbN8r/LN6x0w2Y9qgPf57Zxzjeg9a2USlpzvuKaprphnfm1AQTHRDeb0cyhxq5AERK+QIf+zDrWw7goTZ73dOasqyaiY5LYqBHa8LVVREJdCnmJKBMSU/zsJG4tq3kLIhEeY8t1TjrCBEJD/r2RLCuMVHQyiNzWX8gdRebhONg+pdop7FP5+t+oPgyyDckQkNkXyAm6DWz2LrI38GB3AMtv83DPikWzTlnFDrDZiXH+R3qV/4LvKOsm5S8pHa/5
  template:
    metadata:
      name: timescaledb-db-connect-secret
      namespace: timescaledb
    type: kubernetes.io/basic-auth

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: timescaledb-db-iot-mcp-bridge-ro-secret
  namespace: timescaledb

spec:
  encryptedData:
    password: AgCZVjOeoo7Wd3iELO4gT+DZsHh1yHGzk5r9OFNceP9wbewbL/7tGo+pbMdXYxra7MappGkGwVRgYkwvRitySd26Q3fT0+b9bXoWfC9GBpIWnclXNate06VkcyXpM7iiJjYu4NrNyXSkVyNPwlS952Fbmr0EJfEfPMEHu3GsChsfIlPZNX5GRLvdvygUUvhvxCVDRaJcDiBB/B2Yug0NANch0KBe9DtzRU+wT/aGi8C9tnOAS3Iq+nqg0aaHPF3DcTJ2lvaOK14U4ObXQe+6tagbhGIg7c3jUbvGFJ4Z4POoEpIb3XowgH5Z3z398o9ZjsA9Jukh/vSeXj8gM050MqZNL1tE0nWTgs6OH0pwzeZVzYenxs2km/YrQ0DDvarAS2T3dx9yEs3LMonK4+zubcw1sisheNg+40hYS8akwApZqsKJAO5bJU3WEn63G6wa3lG2fZPYKJwpKVWL+wSw3dyvdoEGLLrEHCWuXETiXmMpoeu+S7ujbmpp2mjr15I9LvSAc6wHmaNTxlZ2R7ExestogNe1litBLuS9B6qz4Htg7joWAXKidDjhiWlPNo1Y/dQn0ONg+5gmJwh/2JOB7C77F7+DS+ao+3MEAQNEoh+moBjmcW2aPlOwN8TDfOpiwNez8S2JV7gNPInvC2aqVDM7k2lPTEki5/+2+zT05M56hEBdGzK6iHBoj1CgAsDTfRRCCjtJ+9CsPkyAzobkzNQJjx3sH/3iC9PuefD45aFsDQ==
    username: AgAOsInWVBZCERR0nvJoDgDXj8rxCf8zWb//0XffS+zQ3dhaxlZxSvVCHvHIBgkyEjH0YJrECwc5eNHjCpIlV1KEiGtjHgduXj9dhZGMAHYkDtJohLZxKdispz27qt66HmCN/U9HJsnRBXoK3W6Uj6UqsZtQtC4Whp4fp+i3B978qDaMelSu+z9w65tP7UO9awYt5lg/pvMyKvrqDTu1FcYwkuyScK+ot4L68WHD76LGo66ovm1+/B7H8Nj+WvdU1nJDpMZkhMflAbgqyDXPMvOIPmCiY+nL+O7cK+Jg98mzU3B2TOo1LxEdbVAuU4hLar9hbdcHlzA68DVmiqKUsBTsPmB/zOWCFpLYmFwviMmewmwU8obapfuWwB4Atv1Lct/rVFSXiVaGJhHYEh2uCWbdQLYz6Yo6x5lqLzLwbHVsGaFyJPxM7l3gO20IoMC6udrgdsdV3kznK50NjE/hJgOPychViGq9pLRzCb5SfYUp0uAaJdqNdvxdcyw0kYn+X8Um7fLlapnI/FytFkyRzcNcZcq7sZeaRbZbb9Nbk3eLN6Q8PX0djd5jYjkXoD2B8AEvzPIkBSCBKKyw7ToPJp1kcRAJIB1KK8hwDaTI6AvpcS38wt8/0t/WFXfAB74W9RLOmz3Kor0kSx2o8GpUf08z5bxwHIiuEjdRv+M1hVRVw3hBJJm1miLA3WsNCBzxtUCuPrqaFttW+U7eoMzPKLiFeQ==
  template:
    metadata:
      name: timescaledb-db-iot-mcp-bridge-ro-secret
      namespace: timescaledb
    type: kubernetes.io/basic-auth

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: timescaledb-db-grafana-ro-secret
  namespace: timescaledb

spec:
  encryptedData:
    password: AgAPvn9dUH5bxIGXCgv6blzQ4RHnjo6OlKn66WMHSufjWIp88QfL9KmZT2liYbjuuH2m1tMvidfKp3TQSRI9vMvJ9I0iTYeeY5ZAmsHOirRTS//GaoftVNs6Qw2pArshp814B1scuHZYVxXM0dsPQcgK8Jf7Twx8S35t6x4W3HvADqZWKswlmgLjySuziUS+bpVGpZkV+6FpD7THQfRDg2m3huFXtZPxIQ2cOClzYJviBUd9acxfRH/OQKZ3UUQ2/OHt59cI/cN7uZc0KAcE9+LYoVGqbjWM+8ejeFSLDrySR+06wMYgSiYARV9gqx030WtQcQuMtG3GixY06TjeBQY2pL/MLT5rQxKDfc5I9qcYlpseXAHQ4rrHJgNWdrMONNw8ZDXJYZRkrJC/cJ56fC88H12YBEDPmUcXhBQgfYTvXSTkSptiwJLCx7XAMBltQTXmi1pS1qfFV8Vr/1QHk374+zjTW2HtOKoyhhgD7qzr0IZVOK+fMFm1zjqk7EHa5MuDi3g9C9RI9Wj8zaKog/27OysSUYZXOx6qqRi7XMGkyUGERm+qPcIWS0SyW93FvQdPnKCZZ+kB03/A56ZQkR87zDACqszDDo1H8XKzIrhQL/cI5vtNT4ubTt5s2+p9mXan0JaIgB/rSXbG0luSRLL6kSlWz5Lxy7OrWtSe9b9nI/NLVU8XT2KzMsHU8xtBXCEC4urgGiqGXbA5pTgCiIYvAR9jWsUJXkxPS9tUQymc
    username: AgAm3Xkj/xCuceDm1TqJEQT+XjipKOEnZXUr+V/i8EV1DazwY/VIZlyKqot/2U5HQO3QsarOLPQKfJRNISXGDvEgJfr6V94eBOyAEXfru0LAXrJJ+FQgdI6VTR6eTxanvda7ck82BUGgQkrDRXf86IkSGCF89w1FgczxkReQpHTCJLTiC6GTK7OX1NAeLN0YVbIDrLcNcvQk2S57OQNwaOLKpigK1K4UAGAGWFtFd4eOQ8/oe7laDCOd1lmFgw3mj3Wc75UYeTcEJwxmGyDxexxXWKWr1WlF+nmsHuKkuTJ7W6KjqWvWbLvZJ5+h1+e5ieyxwG9ng8eDEqSLL1f9uguGNHA/rBpenhxunnthhHi0EBoJDm9upAReOwL8pRJv/gkkDmpsPWFjZU2MgZ7c1dKCXGxNNyWoj0uUJRUam35od9x8qkQIC+DLyZxIvjlTI7PrX4eV0VzVa9blqhvOuaJq0p5S2FVDEXpKEOx6VATVSrXqsLTdaL0KiLoOlcU7CXXFUKMlTTnNnAgto6ngRXq+HmsBvtMl0TyNJ1dT2Xdki0Nw0juFUhmWfnFgJP3QZcl1W+1Kd/K7020PNpQaHIUthxiBwrYz2mG5+gqi7/7N0ygK3p+SumnBNBKU/pFkNSAh/vMQpmEz99fQw71wD68XZXixsMM2XrvFJzCwX2snHvH+lkcJ3Ggx0AQEqh0jnBBfC4Da71nk/jNl
  template:
    metadata:
      name: timescaledb-db-grafana-ro-secret
      namespace: timescaledb
    type: kubernetes.io/basic-auth

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: timescaledb-db-iot-mcp-bridge-rw-secret
  namespace: timescaledb

spec:
  encryptedData:
    password: AgALc542ExV/chQTGYreywlYRuohSoWh7MgURBABxAQQVBnWPGVntfQj+hjZ3S4BD6bQqezU7bteSATyhK85Da4nmPUSsX7ycz+qN29tTvcqoYEA8DLTQ+mbgVxD2feauq192xRlTB2MM+W+GwwBQQJx5StiTBtfAFzeWCVsuxfPCSTTPL5AlSsmP13d1eD8mjOx5Vtr6FnIrwV7F9a8avYeSlFQZMMgUYbInFqVpmGFip0RY/H4PxPJOORx+qAd/o5lfYanRd1dbba/1DVrfET5Vox2rnWN3ydBrjhWQGa+6q3Z1yPezcGg1vUIwsXbrsiz4MHghMl2IpSoFUw3XkBhkAJ+VaLa2YtQw68FsXkANeVf/toKacj1ZsTtJPskX5RTcBTlPVsT5ftgMZJi17VwGLg1I9JZAXy9Ls9ywhpQFFBQMF/zPDjw+xmty0LJ/hQpxzPcgG95sGqqCH6DXHGaOjwbCrIEZA2lw/uK5JSsD0sYM05VD4zce3yHJyKJFJnd3CUZr7yY7l7z2Wn2TRum34uX0JFL1EDyclW3TGhrDA6crYaNTc+WJkcygFyGKI7DzZaP+7S/FVijVR/31knWf+gU74ErU4pwtMDi+CEyU9YbloqU7+SGDVZqcapAci0i9Z+AccSSsJMk8dC8KJdcpucT8gJCIEDDegHZLc5c2LchTapUM5MeFq5wSy46uRLlpNx0nPxBxCxAjR191uV+1PTgLLZprqwbRLxN9KUVmc/ZMw49/zYb4zEZJw==
    username: AgAAUCT4/soqhWxab7YDKaSQ0UZBPmiWN0CG1XWYo0IiK5GsYPJrS3NMNmX4L70vNcSnn8nyca0s8MO9Wtfz0fTk6RGVVtwQoZoMfADRi2PFIg3HHc4R+efGNRt0+0jXn9L0JVCrGw6U+CXFLWYc9q2N0MqTJMmJ6/Ux0ujNpGriavklnw1Tq8ZeMs2jqfrdc4ho66d9s1y8UZXn44qkKzQ2wvT9CeZEzgPSkH0R6JPa326u3sYIJTOM38Q7JDhAPEqYskhOGgbZTAth/6kL+zX1UntjA8ayHmFaLRtZztZUdxzVZgsWp++2aVD++qjxL5d+2ROvGP92vPA0ZjhhHjv3WxpzYUJXseaoG2plz3i/zTkL69kz1fMyC31a4yS7X879LlBcFYHFdKKzhze7r54xkQyC5hkrVVUytArIPbjDNUtXl5KM/f/YKD2GJ6PkYOa7FnmbyG5KMhUxFnnjAZ2aj5crDerNZHAyWzu40J47V377g9+zTG59UnwEToQqfo2PfXVT0mQisODTJKdj+4NMmGhLJ0ZLQxQPI7F06LlkVo9JsNXA6NwWE/u3LY97lERvSzjvR6V0lGige9OPTCgEqrC3GFQXmgBiPVSRBF1inyrXxgRz2JDqhwD0TMV/DvH2zZoojQ+xHOJPTDxztFO1yC9rEn53m98o8LHJc/Je0cATcjGQLZosHavS7plqyogfIFsYzJKlPYwc2LmVHUq0cA==
  template:
    metadata:
      name: timescaledb-db-iot-mcp-bridge-rw-secret
      namespace: timescaledb
    type: kubernetes.io/basic-auth
