{
 "title": "Energiezähler",
 "tags": [
  "influxdb",
  "knx",
  "telegraf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Netzbezug", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Aktueller Netzbezug",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, value FROM knx WHERE knx_name = 'Versorgungstechnik.Energiezähler.Strom.Netzbezug.Wirkleistung-Gesamt' AND time > now() - INTERVAL '15 minutes' ORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Netzbezug über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS \"Netzbezug\" FROM knx WHERE $__timeFilter(time) AND knx_name = 'Versorgungstechnik.Energiezähler.Strom.Netzbezug.Wirkleistung-Gesamt' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Netzbezug & Kosten pro Woche der letzten 3 Monate",
   "type": "table",
   "gridPos": { "h": 15, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('1 week', bucket, 'Europe/Berlin'::text) AS _time, max(max_value) - min(min_value) AS _value, (max(max_value) - min(min_value)) * 0.2937 AS _cost FROM knx_1h WHERE bucket >= date_trunc('month', now() AT TIME ZONE 'Europe/Berlin') - INTERVAL '2 months' AND bucket <= now() AND knx_name = 'Versorgungstechnik.Energiezähler.Strom.Netzbezug.Zählerstand-Gesamt' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Netzbezug & Kosten pro Monat im aktuellen Jahr",
   "type": "table",
   "gridPos": { "h": 15, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('1 month', bucket, 'Europe/Berlin'::text) AS _time, max(max_value) - min(min_value) AS _value, (max(max_value) - min(min_value)) * 0.2937 AS _cost FROM knx_1h WHERE bucket >= date_trunc('year', now() AT TIME ZONE 'Europe/Berlin') AND bucket <= now() AND knx_name = 'Versorgungstechnik.Energiezähler.Strom.Netzbezug.Zählerstand-Gesamt' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Zählerstand Netzbezug",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, value FROM knx WHERE knx_name = 'Versorgungstechnik.Energiezähler.Strom.Netzbezug.Zählerstand-Gesamt' AND time > now() - INTERVAL '1 hour' ORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Netzbezug heute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('day', now() AT TIME ZONE 'Europe/Berlin') AS time, max(value) - min(value) AS value FROM knx WHERE time >= date_trunc('day', now() AT TIME ZONE 'Europe/Berlin') AT TIME ZONE 'Europe/Berlin' AND knx_name = 'Versorgungstechnik.Energiezähler.Strom.Netzbezug.Zählerstand-Gesamt';"
    }
   ]
  },
  {
   "title": "Kosten heute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('day', now() AT TIME ZONE 'Europe/Berlin') AS time, (max(value) - min(value)) * 0.2937 AS value FROM knx WHERE time >= date_trunc('day', now() AT TIME ZONE 'Europe/Berlin') AT TIME ZONE 'Europe/Berlin' AND knx_name = 'Versorgungstechnik.Energiezähler.Strom.Netzbezug.Zählerstand-Gesamt';"
    }
   ]
  },
  {
   "title": "Einspeisung",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true
  },
  {
   "title": "Aktuelle Einspeisung",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, value FROM knx WHERE knx_name = 'Versorgungstechnik.Energiezähler.Strom.Einspeisung.Wirkleistung-Gesamt-1' AND time > now() - INTERVAL '15 minutes' ORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Einspeisung über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 10, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS \"Einspeisung\" FROM knx WHERE $__timeFilter(time) AND knx_name = 'Versorgungstechnik.Energiezähler.Strom.Einspeisung.Wirkleistung-Gesamt-1' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Einspeisung & Ertrag pro Woche der letzten 3 Monate",
   "type": "table",
   "gridPos": { "h": 15, "w": 5, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('1 week', bucket, 'Europe/Berlin'::text) AS _time, max(max_value) - min(min_value) AS _value, (max(max_value) - min(min_value)) * 0.0328 AS _cost FROM knx_1h WHERE bucket >= date_trunc('month', now() AT TIME ZONE 'Europe/Berlin') - INTERVAL '2 months' AND bucket <= now() AND knx_name = 'Versorgungstechnik.Energiezähler.Strom.Einspeisung.Zählerstand-Gesamt-1' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Einspeisung & Ertrag pro Monat im aktuellen Jahr",
   "type": "table",
   "gridPos": { "h": 15, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('1 month', bucket, 'Europe/Berlin'::text) AS _time, max(max_value) - min(min_value) AS _value, (max(max_value) - min(min_value)) * 0.0328 AS _cost FROM knx_1h WHERE bucket >= date_trunc('year', now() AT TIME ZONE 'Europe/Berlin') AND bucket <= now() AND knx_name = 'Versorgungstechnik.Energiezähler.Strom.Einspeisung.Zählerstand-Gesamt-1' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Zählerstand Einspeisung",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, value FROM knx WHERE knx_name = 'Versorgungstechnik.Energiezähler.Strom.Einspeisung.Zählerstand-Gesamt-1' AND time > now() - INTERVAL '1 hour' ORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Einspeisung heute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('day', now() AT TIME ZONE 'Europe/Berlin') AS time, max(value) - min(value) AS value FROM knx WHERE time >= date_trunc('day', now() AT TIME ZONE 'Europe/Berlin') AT TIME ZONE 'Europe/Berlin' AND knx_name = 'Versorgungstechnik.Energiezähler.Strom.Einspeisung.Zählerstand-Gesamt-1';"
    }
   ]
  },
  {
   "title": "Ertrag heute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('day', now() AT TIME ZONE 'Europe/Berlin') AS time, (max(value) - min(value)) * 0.0328 AS value FROM knx WHERE time >= date_trunc('day', now() AT TIME ZONE 'Europe/Berlin') AT TIME ZONE 'Europe/Berlin' AND knx_name = 'Versorgungstechnik.Energiezähler.Strom.Einspeisung.Zählerstand-Gesamt-1';"
    }
   ]
  },
  { "title": "Außenleiter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Leistung L1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS \"L1\" FROM knx WHERE $__timeFilter(time) AND knx_name = 'Versorgungstechnik.Energiezähler.Strom.Netzbezug.Wirkleistung-L1' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Leistung L2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS \"L2\" FROM knx WHERE $__timeFilter(time) AND knx_name = 'Versorgungstechnik.Energiezähler.Strom.Netzbezug.Wirkleistung-L2' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Leistung L3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS \"L3\" FROM knx WHERE $__timeFilter(time) AND knx_name = 'Versorgungstechnik.Energiezähler.Strom.Netzbezug.Wirkleistung-L3' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Stromstärke L1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS \"L1\" FROM knx WHERE $__timeFilter(time) AND knx_name = 'Versorgungstechnik.Energiezähler.Strom.Stromstärke-L1' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Stromstärke L2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS \"L2\" FROM knx WHERE $__timeFilter(time) AND knx_name = 'Versorgungstechnik.Energiezähler.Strom.Stromstärke-L2' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Stromstärke L3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS \"L3\" FROM knx WHERE $__timeFilter(time) AND knx_name = 'Versorgungstechnik.Energiezähler.Strom.Stromstärke-L3' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Spannung L1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS \"L1\" FROM knx WHERE $__timeFilter(time) AND knx_name = 'Versorgungstechnik.Energiezähler.Strom.Spannung-L1' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Spannung L2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS \"L2\" FROM knx WHERE $__timeFilter(time) AND knx_name = 'Versorgungstechnik.Energiezähler.Strom.Spannung-L2' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Spannung L3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS \"L3\" FROM knx WHERE $__timeFilter(time) AND knx_name = 'Versorgungstechnik.Energiezähler.Strom.Spannung-L3' GROUP BY 1 ORDER BY 1;"
    }
   ]
  }
 ]
}