{
 "title": "Wohnraumlüftung",
 "tags": [
  "timescaledb",
  "knx"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Aktuelle Lüfterstufe",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, value FROM knx WHERE knx_name = 'Versorgungstechnik.KWL.Lüftermodi-Status' AND time > now() - INTERVAL '1 hour' ORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Betriebsstunden Filter",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, value FROM knx WHERE knx_name = 'Versorgungstechnik.KWL.Filter-Betriebsstunden' AND time > now() - INTERVAL '1 hour' ORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Filterwechsel",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, value FROM knx WHERE knx_name = 'Versorgungstechnik.KWL.Filterwechsel-Status' AND time > now() - INTERVAL '1 hour' ORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Wartungsmodus",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, value FROM knx WHERE knx_name = 'Versorgungstechnik.KWL.Wartungsmodus-Status' AND time > now() - INTERVAL '1 hour' ORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Fehlerstatus Lüftungsgerät",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, value FROM knx WHERE knx_name = 'Versorgungstechnik.KWL.Status' AND time > now() - INTERVAL '1 hour' ORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Fehlertstatus ComfoConnect",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, value FROM knx WHERE knx_name = 'Versorgungstechnik.KWL.ComfoConnect-Status' AND time > now() - INTERVAL '1 hour' ORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Luftstrom über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m³/s" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Versorgungstechnik.KWL.Luftstrom' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Außenluft über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Versorgungstechnik.KWL.Temperatur-Außenluft' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Fortluft über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Versorgungstechnik.KWL.Temperatur-Fortluft' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Zuluft über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Versorgungstechnik.KWL.Temperatur-Zuluft' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Abluft über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Versorgungstechnik.KWL.Temperatur-Abluft' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Außenluft über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Versorgungstechnik.KWL.Luftfeuchtigkeit-Außenluft' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Fortluft über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Versorgungstechnik.KWL.Luftfeuchtigkeit-Fortluft' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Zuluft über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Versorgungstechnik.KWL.Luftfeuchtigkeit-Zuluft' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Abluft über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Versorgungstechnik.KWL.Luftfeuchtigkeit-Abluft' GROUP BY 1 ORDER BY 1;"
    }
   ]
  }
 ]
}