{
 "title": "Gastherme",
 "description": "EMS-ESP",
 "tags": [
  "timescaledb",
  "knx"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Warmwassertemperatur",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(curtemp) AS \"Warmwassertemperatur\" FROM ems_esp WHERE $__timeFilter(time) AND curtemp IS NOT NULL GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Heizkreispumpe",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(heatingpump, time) AS \"Heizkreispumpe\" FROM ems_esp WHERE $__timeFilter(time) AND heatingpump IS NOT NULL GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Mischerpumpe",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(pumpstatus, time) AS \"Mischerpumpe\" FROM ems_esp WHERE $__timeFilter(time) AND pumpstatus IS NOT NULL GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Heating",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(heatingactive, time) AS \"Heizung\" FROM ems_esp WHERE $__timeFilter(time) AND heatingactive IS NOT NULL GROUP BY 1 ORDER BY 1;",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Heating",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(charging, time) AS \"Warmwasser\" FROM ems_esp WHERE $__timeFilter(time) AND charging IS NOT NULL GROUP BY 1 ORDER BY 1;",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Temperaturfühler über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(outdoortemp) AS \"Außentemperatur\" FROM ems_esp WHERE $__timeFilter(time) AND outdoortemp IS NOT NULL GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Wasserdruck",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(syspress, time) AS \"Druck\" FROM ems_esp WHERE $__timeFilter(time) AND syspress IS NOT NULL GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Warmwasserdurchfluss",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(curflow, time) AS \"Druck\" FROM ems_esp WHERE $__timeFilter(time) AND curflow IS NOT NULL GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Therme über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(selflowtemp) AS \"Soll Temperatur\" FROM ems_esp WHERE $__timeFilter(time) AND selflowtemp IS NOT NULL GROUP BY 1 ORDER BY 1;"
    },
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(curflowtemp) AS \"Ist Temperatur\" FROM ems_esp WHERE $__timeFilter(time) AND curflowtemp IS NOT NULL GROUP BY 1 ORDER BY 1;"
    },
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(rettemp) AS \"Rücklauf\" FROM ems_esp WHERE $__timeFilter(time) AND rettemp IS NOT NULL GROUP BY 1 ORDER BY 1;"
    },
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(switchtemp) AS \"Hydraulische Weiche\" FROM ems_esp WHERE $__timeFilter(time) AND switchtemp IS NOT NULL GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Warmwasser über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(settemp) AS \"Soll Temperatur\" FROM ems_esp WHERE $__timeFilter(time) AND settemp IS NOT NULL AND topic = 'boiler_data_dhw' GROUP BY 1 ORDER BY 1;"
    },
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(curtemp) AS \"Ist Temperatur\" FROM ems_esp WHERE $__timeFilter(time) AND curtemp IS NOT NULL AND topic = 'boiler_data_dhw' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Fußbodenheizung über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(flowsettemp) AS \"Soll Temperatur\" FROM ems_esp WHERE $__timeFilter(time) AND flowsettemp IS NOT NULL GROUP BY 1 ORDER BY 1;"
    },
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(flowtemphc) AS \"Ist Temperatur\" FROM ems_esp WHERE $__timeFilter(time) AND flowtemphc IS NOT NULL GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Brennerleistung",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(curburnpow, time) AS \"power\" FROM ems_esp WHERE $__timeFilter(time) AND curburnpow IS NOT NULL GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Brennerleistung über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 2, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(curburnpow) AS \"Brennerleistung\" FROM ems_esp WHERE $__timeFilter(time) AND curburnpow IS NOT NULL GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Mischerposition",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(valvestatus, time) AS \"Fußbodenheizung\" FROM ems_esp WHERE $__timeFilter(time) AND valvestatus IS NOT NULL GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Mischerposition über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(valvestatus) AS \"Ventilöffnung\" FROM ems_esp WHERE $__timeFilter(time) AND valvestatus IS NOT NULL AND topic = 'mixer_data_hc1' GROUP BY 1 ORDER BY 1;"
    },
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(valvestatus) AS \"Heizkörper\" FROM ems_esp WHERE $__timeFilter(time) AND valvestatus IS NOT NULL AND topic = 'mixer_data_hc2' GROUP BY 1 ORDER BY 1;"
    }
   ]
  }
 ]
}