{
 "title": "5. Außen - Alarm",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Fassade - Außensensor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperatur",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.A.Fassade.Außensensor.Temperatur-Alarm-1' GROUP BY 1 ORDER BY 1;"
    },
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.A.Fassade.Außensensor.Temperatur-Alarm-2' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  { "title": "Dach - Wetterstation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Temperatur",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.A.Dach.Wetterstation.Temperatur-Alarm-1' GROUP BY 1 ORDER BY 1;"
    },
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.A.Dach.Wetterstation.Temperatur-Alarm-2' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Regen",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.A.Dach.Wetterstation.Regen-Alarm-1' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Frost",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.A.Dach.Wetterstation.Frost-Alarm-1' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Windgeschwindigkeit",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.A.Dach.Wetterstation.Windgeschwindigkeit-Alarm-Erweitert-1' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  { "title": "Dach - Außensensor SO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Temperatur",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.A.Dach.Außensensor.SO.Temperatur-Alarm-1' GROUP BY 1 ORDER BY 1;"
    },
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.A.Dach.Außensensor.SO.Temperatur-Alarm-2' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Luftfeuchte",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.A.Dach.Außensensor.SO.Luftfeuchte-Alarm-1' GROUP BY 1 ORDER BY 1;"
    },
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.A.Dach.Außensensor.SO.Luftfeuchte-Alarm-2' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Luftdruck",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.A.Dach.Außensensor.SO.Luftdruck-Alarm-1' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Dach - Außensensor NW",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true
  },
  {
   "title": "Temperatur",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.A.Dach.Außensensorn.NW.Temperatur-Alarm-1' GROUP BY 1 ORDER BY 1;"
    },
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.A.Dach.Außensensor.NW.Temperatur-Alarm-2' GROUP BY 1 ORDER BY 1;"
    }
   ]
  }
 ]
}