{
 "title": "4. Dachgeschoss",
 "tags": [
  "timescaledb",
  "knx"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Speicher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.DG.Speicher.Sensor.Temperatur' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Luftfeuchte",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.DG.Speicher.Sensor.Luftfeuchtigkeit' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Luftdruck",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) / 100.0 AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.DG.Speicher.Sensor.Luftdruck-Relativ' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.DG.Speicher.Sensor.CO2' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "VOC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, avg(value) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.DG.Speicher.Sensor.VOC' GROUP BY 1 ORDER BY 1;"
    }
   ]
  }
 ]
}