{
 "title": "4. Dachgeschoss - Alarm",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Speicher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Temperatur",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.DG.Speicher.Sensor.Temperatur-Alarm-1' GROUP BY 1 ORDER BY 1;"
    },
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.DG.Speicher.Sensor.Temperatur-Alarm-2' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Luftfeuchte",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.DG.Speicher.Sensor.Luftfeuchtigkeit-Alarm-1' GROUP BY 1 ORDER BY 1;"
    },
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.DG.Speicher.Sensor.Luftfeuchtigkeit-Alarm-2' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Taupunkt",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.DG.Speicher.Sensor.Taupunkt-Alarm-1' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Luftdruck",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.DG.Speicher.Sensor.Luftdruck-Alarm-1' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.DG.Speicher.Sensor.CO2-Alarm-1' GROUP BY 1 ORDER BY 1;"
    },
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.DG.Speicher.Sensor.CO2-Alarm-2' GROUP BY 1 ORDER BY 1;"
    },
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.DG.Speicher.Sensor.CO2-Alarm-3' GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "VOC",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time, '$__interval') AS time, last(value, time) AS value FROM knx WHERE $__timeFilter(time) AND knx_name = 'Sensorik.DG.Speicher.Sensor.VOC-Alarm-1' GROUP BY 1 ORDER BY 1;"
    }
   ]
  }
 ]
}