apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: dyson-nats-bridge-device-credential
  namespace: dyson-nats-bridge

spec:
  encryptedData:
    credential: AgBz4HH0DNuGeH3KSNsu3/NSCiq1SNKKN96WJSM4HxWJsC/w93uU5k4hwIGUuFu+WSheyFxU4pyhy1HKIZv+GZd2jeY70CrjfA3HT769+CzNJeHNeAuFhxBmbiF8oIoixrhqgKnVLvEvySf9qG1SxAblb2JkTNy85v6IqvLXxQmFH1MDEOwfBejuhDzW09tLJz9KaTW1FFPDgvIfPKN+eUTSVs/vgNpTJ5nGAi4qzqaH0vH6ysSFT6A61+TBusvn09vbKh0Mo4I10EogOATD20BK4lYN1UaI3xuUSGO7o8Q3QyuvD1BaZsKykdj0YLKg92XDkI7IQHRFFUXF1OMeRzp6+BisARBsgefUEhwvV0iN1wjT/89DhgscVEPQWOvzZWR4CEaV///S51LJ48s+kMgVh1jm6WaQf0ry/dttoY+PMMXvQrh+PbH9Rxo1NM05zdQM6f7leFlEOrlemyTWbTjSy3amcVNQyP9Msex1FjgQzQakdvFvXLhAeD+2mGjx468Uqd1zWFHgKHof7rDcRbLIuW3k759baTY69GgBx6awqfNk10pklqN19KExDa+0DO226PnnLOD7TBvncnCyfW+nbRNuMbktk+Xnjxw5kPKCNGtSWA6KRz0ndvCFp0YY4GoxplIoPgJ4zvEKLUF+4MWtVad6G54xcwl2749DPZ+oojHZioGhc70i3LjhpvsHXW77dt/JiDUiGBPQfZvYCY+3uaJXjW8rg8vQlbWcye9UVYHGv8QB2xP8vUk6MTtGRytVnbd+Fvoxr9wLTAwVRwhFBF5GuHNMEtfUen4UmBsfIe6d2TsbCB0t
  template:
    metadata:
      name: dyson-nats-bridge-device-credential
      namespace: dyson-nats-bridge
    type: Opaque
