apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: dyson-nats-bridge-device-credentials
  namespace: dyson-nats-bridge

spec:
  encryptedData:
    ventilator-1: AgBipsS07LZL6zCucC3arKIvAru7Kw3B84gjm+8P4s7FYK6oMbfdyrT98Ii20iMwpzXmGIRAxpsPupsq9IKCXq4VwMY4jHf8sonjDzIuPjui+03fjfON7NRdfk9gp58NlxPcAU5RJI0k6s3ZyA0DF08D92reZIc/e2EDi08OsBqEyIO/kbg9OPvjGe27Pw7XU0VVcuABZVlmdE9cZl4PTWV/OVUOSPHFQisRax9mpONum8lpo6Z0Zb+0ee8pCLz+oeGYM482BzqjCZfTflL9NMeS7l5DFpf+hb+7v6/qsqSLyCSqRFg+Jg2sV4e2x7kPKZy5C+LgIJeIiaLefq0HpakyjHVWD9oM8iHznqtL/+cjySe9LaLpYHfm8SQv3FGFSnrhmG4NxYH0hYcJjf4dlhhV4cIDdxBHTRTLbQvDmbcKOZt8EL2WlHi48roeX1IoJ+HXdsEXRB3Fc5kk2Jvw0mgKQWnsE6TRl/s3B8pPDbLiCCgjmDjsRlcfqX9AIB1kPfaSD9KkwtN/9TwIf1DIKFwZ7EbofuxqUXp78KewqDsZBAg4nvI/xJgX/7OMDJhDOC2W4kqp8B6pZx92feIPwAkcYbS89tViNp8qQAmfX8h6WFuYGq20x/4cNEVWfpJ1j0h+Y+CbAUmf0ZrN5R8bUhkBGiu8LZ7GtRlfq7jekNxAwwmOJzNCZG37I7LiWICPnNiVXC+iVyVv6pMz4EG1d+jKSWP5I75mRb6sdvjeWxS7FZYLeh4SW+rMxxccCl6eYB/dvjdbigkWI0RP32a/LSTQva2qb1FIw9zFfUw5Jvxh5ZM+dJsnpHuA
  template:
    metadata:
      name: dyson-nats-bridge-device-credentials
      namespace: dyson-nats-bridge
    type: Opaque
