apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: dyson-nats-bridge-device-credentials
  namespace: dyson-nats-bridge

spec:
  encryptedData:
    ventilator-og7: AgBHOyk9fwAD1bX2tpYAFO02kTiHbziIi91xAPVydWyzSUG/hA6bj9Evd2p46B8523eTdZCbUJ562otACp6GhNOmG+PKgptHFZnpoKo56zl1A66l2ApXvduzfBb0KYqfZqhjI45OxUg0sX0qFTv4NtUhctyjd3LRxopuxyxLLmmFropSIcpaWNnvszR/hTECUn93ME9nmq1huczWjX8ansDFPbz48SXwCL+e2oZdidHdJtty1nNt5wPkx3gNU9D7rpMkXBKpNnHl0fnpNMGX13dIXOLhWVFb9pvGQ/tV42rtMFwbj8Y7XFeFaSIXCBf1iX20BnRiHcPPOd5pG+AWi7k1BZdrEaYJvl92H/NyBOQYqnC3nopbt05mWfJVA1DPVrhwC6Uz8nXJNY7TfSQ3A5JLvOgBriJGwFZzlmpX5dkU2FJfkYSX9+6Seuqfg0/x6SF0AV3TOa1ne60IQPB3kAgaQTHNYlYB7eCU9M3ffrDplW9ARjNv+FakUKqdp/0IIGX3xp81/beqL7YakcI/3jUGex54qDi/AfrT4+chQFmfieAQi2uoqn8jFtUtArtaAfqyvBtaClH/JdHwB/TaE1Fzxgrq7YRJi0/bZqm47bFnyZnvGtFT9DzsdGzyoTB4NAe0jxesmYt3BT/1KcZDqEwklpKWLoKPRym75A6IUG/N8mbQGetzk3RgPWGaXGzR3Fqw6OOnDwVURi5KUQrtBZvGsVObNwV7mmOfjQDiFFj3I4DT7gCDHUwGvsqcpiG5Qfl6EqeehRYkJ000NCbk2uzDxfJafVE2PKAkt8dff7Qt3H6r8MBVxUAb
  template:
    metadata:
      name: dyson-nats-bridge-device-credentials
      namespace: dyson-nats-bridge
    type: Opaque
