"""Generate the fault writer rules from the fault list and the GA catalog.

    uv run --no-project --with pyyaml python scripts/fault_writer_rules.py \
        <faults.yaml> <ga-catalog.yaml> <writer-rules.yaml>

A fault whose target is "one address per main group" (channel silence) is
delivered by one writer rule per main group: the engine publishes the
group's severity on `anomaly.<fault>.<main group>`, the bridge carries it
to that group's address in its Zentral block. A block of near-identical
rules that must follow every ETS renumbering is exactly the list that went
wrong once already when it was copied by hand, so it is written here instead.

Two files decide everything: the fault list says which faults deliver per
main group, the catalog says which address that is in each group and with
which DPT. What is neither is the naming rule that ties the two together —
that a channel-silence target is the group's `Telegrammstille-Anomalie` —
and it is declared once, in TARGET_NAME below, rather than resolved from a
list of addresses that could drift.

The rules are spliced into the writer-rules file between its markers, so
regenerating after a catalog change is the whole procedure and the diff
shows what moved.

Faults delivering to a single house-wide address — the notification-volume
watchdog on 0/0/251 — are not generated here: none is declared in the fault
list yet, and the target form they need is a plain address rather than a
name per main group.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

# Which address in a main group's Zentral block a per-main-group fault
# writes to, by the suffix of its catalog name. The address plan gives
# every main group the same Diagnose block, which is what makes one
# suffix enough for all of them.
TARGET_NAME = {
    "channel_silence": ".Zentral.Diagnose.Telegrammstille-Anomalie",
}

# The engine's delivery contract, identical for every fault: the current
# tier as a number, written on every change including the clearing 0, and
# re-read from JetStream at bridge startup so a redeploy does not leave the
# address at no_value until the next state change.
PAYLOAD_PATH = "$.severity_level"
MIN_DELTA = 0
SEED_ON_START = True

BEGIN = "  # >>> generated by `task knx:fault-writer-rules`"
END = "  # <<< generated"


def main_group(ga: str) -> int:
    """The KNX main group of a group address — the granularity silence
    reports at."""
    return int(ga.split("/")[0])


def per_main_group_faults(path: Path) -> list[str]:
    """The faults the fault list declares as delivering one severity per
    main group, in file order."""
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    return [
        fault["name"]
        for fault in raw["faults"]
        if fault.get("target", {}).get("per_main_group")
    ]


def targets(catalog: dict, suffix: str) -> dict[int, tuple[str, dict]]:
    """Each main group's target address for a name suffix — exactly one per
    main group the catalog knows.

    Both ways of missing that are errors, because both are silent otherwise:
    two matches leave the rule ambiguous, and none at all drops that group's
    rule while everything downstream still validates, so its severities would
    go nowhere and nothing would say so.
    """
    found: dict[int, tuple[str, dict]] = {}
    for ga, entry in catalog.items():
        if not entry["name"].endswith(suffix):
            continue
        group = main_group(ga)
        if group in found:
            raise SystemExit(
                f"main group {group} has two addresses ending in {suffix}: "
                f"{found[group][0]} and {ga}"
            )
        found[group] = (ga, entry)
    missing = sorted({main_group(ga) for ga in catalog} - set(found))
    if missing:
        raise SystemExit(
            f"main groups {missing} carry no address ending in {suffix} — "
            "either it was renamed in ETS or it was never created"
        )
    return found


def rules(fault: str, addresses: dict[int, tuple[str, dict]]) -> list[str]:
    """One writer rule per main group, in the file's own key order."""
    lines = []
    for group in sorted(addresses):
        ga, entry = addresses[group]
        if '"' in entry["name"] or "\\" in entry["name"]:
            raise SystemExit(f"{ga}: name needs YAML escaping, which this does not do")
        lines += [
            f'  - subject: "anomaly.{fault}.{group}"',
            f'    ga: "{ga}"',
            f'    dpt: "{entry["dpt"]}"',
            f'    payload_path: "{PAYLOAD_PATH}"',
            f'    description: "{entry["name"]}"',
            f"    min_delta: {MIN_DELTA}",
            f"    seed_on_start: {str(SEED_ON_START).lower()}",
        ]
    return lines


def splice(text: str, block: list[str]) -> str:
    """Replace what stands between the markers, leaving both in place."""
    lines = text.splitlines()
    try:
        begin = lines.index(BEGIN)
        end = lines.index(END)
    except ValueError:
        raise SystemExit(
            f"writer rules carry no generated block — add\n{BEGIN}\n{END}\n"
            "where the rules belong, then re-run"
        ) from None
    return "\n".join(lines[: begin + 1] + block + lines[end:]) + "\n"


def main() -> int:
    faults_path, catalog_path, rules_path = (Path(a) for a in sys.argv[1:4])
    catalog = yaml.safe_load(catalog_path.read_text(encoding="utf-8"))

    block: list[str] = []
    for fault in per_main_group_faults(faults_path):
        suffix = TARGET_NAME.get(fault)
        if suffix is None:
            raise SystemExit(
                f"fault {fault} delivers per main group, but TARGET_NAME does not "
                "say which address in the group that is"
            )
        addresses = targets(catalog, suffix)
        block += rules(fault, addresses)
        groups = ", ".join(str(g) for g in sorted(addresses))
        print(f"{fault}: {len(addresses)} rules on main groups {groups}")

    generated = splice(rules_path.read_text(encoding="utf-8"), block)
    rules_path.write_text(generated, encoding="utf-8")
    print(f"{rules_path.name}: generated block is {len(block)} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
