"""Generate the channel fault mappings from the fault list and the GA catalog.

    uv run --no-project --with pyyaml python scripts/fault_writer_rules.py \
        <faults.yaml> <ga-catalog.yaml> <ga-mappings-dir>

Two target forms are generated, both of them faults the engine delivers to
addresses nobody should type twice:

* "one address per main group" (channel silence, and constancy on its own
  address once ETS has it) becomes one rule per main group and fault — the
  engine publishes the group's severity on
  `anomaly.<fault>.<main group>`, the bridge carries it to that group's
  address in its Zentral block. A block of near-identical rules that must
  follow every ETS renumbering is exactly the list that went wrong once
  already when it was copied by hand, so it is written here instead.
* a single house-wide address (the notification-volume watchdog on 0/0/251)
  becomes one rule on the 1:1 subject `anomaly.<fault>`. The address is
  declared in the fault file; DPT and description come from the catalog, so
  a renumbering that leaves the fault file behind fails here rather than
  publishing into nothing.

Two files decide everything: the fault list says which faults deliver which
way, the catalog says which address that is and with which DPT. What is
neither is the naming rule that ties the two together for the per-main-group
form — which address in the group a fault of that form writes — and it is
declared once, in TARGET_NAME below, rather than resolved from a list of
addresses that could drift.

The rules are written whole into <ga-mappings-dir>/channels.yaml, marked by
its first line as generated, so regenerating after a catalog change is the
whole procedure and the diff shows what moved. The validate task regenerates
the file to a temporary directory and diffs, so a stale one cannot be
committed.

Per-device and per-room targets are not generated: their addresses follow
the device and room names rather than one suffix per group, and their rules
are written by hand in insights.yaml. Nor is a fault listed in HAND_WRITTEN,
whose one address is reached on a subject carrying an entity this file
cannot know.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

# Which address in a main group's Zentral block a per-main-group fault
# writes to, by the suffix of its catalog name. The address plan gives
# every main group the same Diagnose block, which is what makes one
# suffix enough for all of them.
TARGET_NAME = {
    "channel_silence": ".Zentral.Diagnose.Telegrammstille-Anomalie",
    "channel_constancy": ".Zentral.Diagnose.Konstanz-Anomalie",
}

# Faults that deliver to one declared address, but whose subject carries an
# entity the fault file does not name — heat recovery publishes on its
# exchanger's own slug, not on the bare fault name. Their rule is written
# by hand in insights.yaml, like the per-device and per-room ones; generating
# a bare subject for them would put a second, never-firing rule on a live
# address.
HAND_WRITTEN = {"heat_recovery_decay"}

# The engine's delivery contract, identical for every fault: the current
# tier as a number, written on every change including the clearing 0, and
# re-read from JetStream at bridge startup so a redeploy does not leave the
# address at no_value until the next state change.
PAYLOAD_PATH = "$.severity_level"
MIN_DELTA = 0
SEED_ON_START = True

GENERATED_FILE = "channels.yaml"
HEADER = [
    "# generated by `task knx:fault-writer-rules` — do not edit",
    "# Fault severities → KNX (iot-insights-engine) for the two channel-scoped",
    "# faults, one severity per main group on its own Zentral Diagnose address —",
    "# silence on x/0/250, constancy on x/0/252 — and for the faults delivering",
    "# to one declared house-wide address. Resolved against faults.yaml and",
    "# ga-catalog.yaml; re-run the task after every catalog change.",
    "",
    "mappings:",
]


def main_group(ga: str) -> int:
    """The KNX main group of a group address — the granularity the
    channel-scoped faults report at."""
    return int(ga.split("/")[0])


def targeted_faults(path: Path) -> list[tuple[str, dict]]:
    """Every schedulable fault that declares a delivery target — its name and
    that target, in file order. Which target shapes are generated is decided
    in one place, in main().

    A dormant fault is skipped: it publishes nothing, and its addresses are
    typically the very thing it is waiting for, so generating rules for it
    would fail on a catalog that cannot know them yet.
    """
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    return [
        (fault["name"], fault["target"])
        for fault in raw["faults"]
        if "target" in fault and "dormant" not in fault
    ]


def targets(catalog: dict, suffix: str) -> dict[int, tuple[str, dict]]:
    """Each main group's target address for a name suffix — exactly one per
    main group the catalog knows.

    Both ways of missing that are errors, because both are silent otherwise:
    two matches leave the rule ambiguous, and none at all drops that group's
    rule while everything downstream still validates, so its severities would
    go nowhere and nothing would say so.
    """
    found: dict[int, tuple[str, dict]] = {}
    for ga, entry in catalog.items():
        if not entry["name"].endswith(suffix):
            continue
        group = main_group(ga)
        if group in found:
            raise SystemExit(
                f"main group {group} has two addresses ending in {suffix}: "
                f"{found[group][0]} and {ga}"
            )
        found[group] = (ga, entry)
    missing = sorted({main_group(ga) for ga in catalog} - set(found))
    if missing:
        raise SystemExit(
            f"main groups {missing} carry no address ending in {suffix} — "
            "either it was renamed in ETS or it was never created"
        )
    return found


def rule(subject: str, ga: str, entry: dict) -> list[str]:
    """One writer rule: the engine's subject, the catalog's address."""
    if '"' in entry["name"] or "\\" in entry["name"]:
        raise SystemExit(f"{ga}: name needs YAML escaping, which this does not do")
    return [
        f'  - subject: "{subject}"',
        f'    ga: "{ga}"',
        f'    dpt: "{entry["dpt"]}"',
        f'    payload_path: "{PAYLOAD_PATH}"',
        f'    description: "{entry["name"]}"',
        f"    min_delta: {MIN_DELTA}",
        f"    seed_on_start: {str(SEED_ON_START).lower()}",
    ]


def per_main_group_rules(fault: str, addresses: dict[int, tuple[str, dict]]) -> list[str]:
    """One writer rule per main group, in the file's own key order."""
    lines: list[str] = []
    for group in sorted(addresses):
        ga, entry = addresses[group]
        lines += rule(f"anomaly.{fault}.{group}", ga, entry)
    return lines


def house_wide_rule(fault: str, ga: str, catalog: dict) -> list[str]:
    """The one rule for a fault delivering to a single address: a 1:1
    subject, and the address the fault file names — which has to exist in
    the catalog, or the severity would go nowhere and nothing would say so.
    """
    entry = catalog.get(ga)
    if entry is None:
        raise SystemExit(
            f"fault {fault} delivers to {ga}, which the catalog does not know — "
            "either it was renumbered in ETS or it was never created"
        )
    return rule(f"anomaly.{fault}", ga, entry)


def main() -> int:
    faults_path, catalog_path, mappings_dir = (Path(a) for a in sys.argv[1:4])
    catalog = yaml.safe_load(catalog_path.read_text(encoding="utf-8"))

    block: list[str] = []
    for fault, target in targeted_faults(faults_path):
        if fault in HAND_WRITTEN:
            print(f"{fault}: skipped, its subject carries an entity — rule written by hand")
        elif "ga" in target:
            block += house_wide_rule(fault, target["ga"], catalog)
            print(f"{fault}: 1 rule on {target['ga']}")
        elif target.get("per_main_group"):
            suffix = TARGET_NAME.get(fault)
            if suffix is None:
                raise SystemExit(
                    f"fault {fault} delivers per main group, but TARGET_NAME does not "
                    "say which address in the group that is"
                )
            addresses = targets(catalog, suffix)
            block += per_main_group_rules(fault, addresses)
            groups = ", ".join(str(g) for g in sorted(addresses))
            print(f"{fault}: {len(addresses)} rules on main groups {groups}")
        # Per-device and per-room targets are written by hand: their
        # addresses follow device and room names, not one suffix per group.

    out = mappings_dir / GENERATED_FILE
    out.write_text("\n".join(HEADER + block) + "\n", encoding="utf-8")
    print(f"{out.name}: {len(block)} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
