"""Generate the GA mappings whose rules follow a pattern lares already knows.

    uv run --no-project --python 3.14 --with "<package> @ git+<repo>@v<tag>" \
        python scripts/ga_mappings.py <source> <ga-catalog.yaml> <out-dir> <input>

One run writes one file, <out-dir>/<source>.yaml, whole — its first line
marks it as generated. The sources, each in the environment of the package
that describes it, installed at the tag the app manifest deploys:

* `miele`, `midea`, `dyson` — input: the sidecar's app config. Every
  device there carries a binding, `ga_name`, the group-address name prefix
  of its block; the bridge package ships a descriptor, `knx.yaml`, that
  says per published field the datapoint name, the DPT and the writer
  behaviour. device × field → the address named `<ga_name>.<datapoint>`.
* `insights` — input: the fault list. The per-device and per-room faults
  declare a name template, `target.name`, with `{entity}` standing for the
  entity as the fault's device or room map names it; entity × fault → the
  address the template renders to. The subject entity is what the engine
  publishes: the device's channel address, the room's key, slugged with the
  engine's own function.
* `channels` — input: the fault list. The per-main-group faults (one
  address in every main group's Zentral block, named by the suffix in
  TARGET_NAME) and the faults delivering to one declared house-wide
  address.

Every rule is resolved against the catalog by name, so an ETS renumbering
changes the addresses in the generated files and nothing else. The
descriptor's DPT and the catalog's must agree, or the run fails naming the
device and field — a field is never silently encoded wrong. A field the
catalog has no name for is left out and reported per device: not every
appliance has every datapoint, ETS decides what exists. `description` is
always the catalog name.

The validate task regenerates every file into a temporary directory and
diffs, so a stale one cannot be committed. Hand-written files are never
touched here.
"""

from __future__ import annotations

import importlib
import re
import sys
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

GENERATED_BY = "# generated by `task knx:create-ga-mappings` — do not edit"


@dataclass(frozen=True)
class Sidecar:
    """A sidecar bridge whose package describes its fields."""

    # Import name of the package; the descriptor is `knx.yaml` at its root
    package: str
    # Top-level list in the app config, and the pydantic model the bridge
    # loads each entry with — the same model rejects what the pod would
    model: str
    config_key: str
    header: str


SIDECARS = {
    "miele": Sidecar(
        package="miele_nats_bridge",
        model="ApplianceConfig",
        config_key="appliances",
        header="Miele appliances → KNX (miele-nats-bridge), read-only status from the cloud bridge.",
    ),
    "midea": Sidecar(
        package="midea_nats_bridge",
        model="DeviceConfig",
        config_key="devices",
        header="Midea Entfeuchter → KNX (midea-nats-bridge), status feedback per dehumidifier.",
    ),
    "dyson": Sidecar(
        package="dyson_nats_bridge",
        model="DeviceConfig",
        config_key="devices",
        header="Dyson Luftreiniger → KNX (dyson-nats-bridge), status feedback per purifier.",
    ),
}

# Which address in a main group's Zentral block a per-main-group fault
# writes to, by the suffix of its catalog name. The address plan gives
# every main group the same Diagnose block, which is what makes one
# suffix enough for all of them.
TARGET_NAME = {
    "channel_silence": ".Zentral.Diagnose.Telegrammstille-Anomalie",
    "channel_constancy": ".Zentral.Diagnose.Konstanz-Anomalie",
}

# Faults that deliver to one declared address on a subject carrying their
# single reference — heat recovery publishes on its exchanger's own label,
# not on the bare fault name. Which kinds do that is the runner's business
# and not in the fault file, so it is declared here; a bare subject for
# them would put a second, never-firing rule on a live address.
SUBJECT_CARRIES_REFERENCE = {"heat_recovery_decay"}

# The engine's delivery contract, identical for every fault: the current
# tier as a number, written on every change including the clearing 0, and
# re-read from JetStream at bridge startup so a redeploy does not leave the
# address at no_value until the next state change.
SEVERITY_PATH = "$.severity_level"
SEVERITY_DPT = "5.010"


@dataclass(frozen=True)
class Rule:
    """One writer rule: a subject and payload path, the catalog's address."""

    subject: str
    ga: str
    dpt: str
    payload_path: str
    description: str
    seed_on_start: bool
    min_delta: float | None = None
    min_delta_pct: float | None = None

    def lines(self) -> list[str]:
        if '"' in self.description or "\\" in self.description:
            raise SystemExit(
                f"{self.ga}: name needs YAML escaping, which this does not do"
            )
        out = [
            f'  - subject: "{self.subject}"',
            f'    ga: "{self.ga}"',
            f'    dpt: "{self.dpt}"',
            f'    payload_path: "{self.payload_path}"',
            f'    description: "{self.description}"',
        ]
        if self.min_delta is not None:
            out.append(f"    min_delta: {self.min_delta}")
        if self.min_delta_pct is not None:
            out.append(f"    min_delta_pct: {self.min_delta_pct}")
        out.append(f"    seed_on_start: {str(self.seed_on_start).lower()}")
        return out


def ga_key(ga: str) -> tuple[int, ...]:
    return tuple(int(part) for part in ga.split("/"))


def natural_key(text: str) -> list[int | str]:
    """Sort key with digit runs compared as numbers, so main group 2 sorts
    before 10 and device 2-1-27 before 2-1-117."""
    return [int(run) if run.isdigit() else run for run in re.split(r"(\d+)", text)]


def main_group(ga: str) -> int:
    """The KNX main group of a group address — the granularity the
    channel-scoped faults report at."""
    return ga_key(ga)[0]


class Catalog:
    """The GA catalog, indexed both ways: by address as the file is, and by
    name — the key everything here resolves through."""

    def __init__(self, path: Path) -> None:
        self.by_ga: dict[str, dict[str, Any]] = yaml.safe_load(
            path.read_text(encoding="utf-8")
        )
        self.by_name: dict[str, str] = {}
        for ga, entry in self.by_ga.items():
            if entry["name"] in self.by_name:
                raise SystemExit(
                    f"catalog name {entry['name']!r} is carried by both "
                    f"{self.by_name[entry['name']]} and {ga} — names are the key here"
                )
            self.by_name[entry["name"]] = ga

    def rule(
        self,
        subject: str,
        ga: str,
        payload_path: str,
        *,
        seed_on_start: bool,
        min_delta: float | None = None,
        min_delta_pct: float | None = None,
    ) -> Rule:
        entry = self.by_ga[ga]
        return Rule(
            subject=subject,
            ga=ga,
            dpt=entry["dpt"],
            payload_path=payload_path,
            description=entry["name"],
            seed_on_start=seed_on_start,
            min_delta=min_delta,
            min_delta_pct=min_delta_pct,
        )


def like(pattern: str, name: str) -> bool:
    """SQL LIKE against a full name (`%` any run, `_` any character) — the
    dialect the fault list's scope lines are written in."""
    regex = ".*".join(re.escape(part).replace("_", ".") for part in pattern.split("%"))
    return re.fullmatch(regex, name) is not None


# --- sidecar sources -------------------------------------------------------


def sidecar_rules(
    source: str, sidecar: Sidecar, catalog: Catalog, config_path: Path
) -> list[Rule]:
    """device × descriptor field → the address named `<ga_name>.<datapoint>`."""
    from nats_bridge_core.knx_descriptor import load_package

    descriptor = load_package(sidecar.package)
    # Load the entries with the bridge's own model at its deployed tag: what
    # the pod would refuse — an unknown key, a bad name — fails here first.
    model = getattr(importlib.import_module(f"{sidecar.package}.config"), sidecar.model)
    raw = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    try:
        devices = [model(**entry) for entry in raw[sidecar.config_key]]
    except ValueError as exc:
        raise SystemExit(
            f"{config_path.name}: {sidecar.package} at its deployed tag refuses an entry, "
            f"and so would the pod:\n{exc}"
        ) from exc

    rules: list[Rule] = []
    for device in devices:
        if not device.ga_name:
            raise SystemExit(
                f"{source}.{device.name}: no ga_name binding in {config_path.name} — "
                "add the device's group-address name prefix"
            )
        missing: list[str] = []
        count = 0
        for subject in descriptor.subjects.values():
            for field in subject.fields.values():
                names = [
                    f"{device.ga_name}.{candidate}" for candidate in field.datapoints
                ]
                hits = [name for name in names if name in catalog.by_name]
                if not hits:
                    missing.append(f"{subject.suffix}.{field.name}")
                    continue
                if len(hits) > 1:
                    raise SystemExit(
                        f"{source}.{device.name}: {field.name} could go to any of {hits} — "
                        "the catalog carries more than one of the descriptor's candidates"
                    )
                ga = catalog.by_name[hits[0]]
                dpt = catalog.by_ga[ga]["dpt"]
                if dpt != field.dpt:
                    raise SystemExit(
                        f"{source}.{device.name}: {field.name} is DPT {field.dpt} in the "
                        f"descriptor, but {hits[0]} ({ga}) is DPT {dpt} in the catalog"
                    )
                rules.append(
                    catalog.rule(
                        f"{source}.{device.name}.{subject.suffix}",
                        ga,
                        field.payload_path,
                        seed_on_start=field.seed_on_start,
                        min_delta=field.min_delta,
                        min_delta_pct=field.min_delta_pct,
                    )
                )
                count += 1
        left_out = f", no address for {', '.join(missing)}" if missing else ""
        print(f"{source}.{device.name}: {count} rules{left_out}")
    return rules


# --- engine sources --------------------------------------------------------


def targeted_faults(faults_path: Path) -> list[Any]:
    """Every schedulable fault that declares a delivery target, loaded with
    the engine's own loader at its deployed tag. A dormant fault is skipped:
    it publishes nothing, and its addresses are typically the very thing it
    is waiting for."""
    from iot_insights_engine.faults import FaultList

    faults = FaultList.load(faults_path)
    return [fault for fault in faults.schedulable() if fault.target is not None]


def per_main_group_rules(fault: Any, catalog: Catalog) -> list[Rule]:
    """One rule per main group the catalog knows — exactly one address per
    group ending in the fault's suffix.

    Both ways of missing that are errors, because both are silent otherwise:
    two matches leave the rule ambiguous, and none at all drops that group's
    rule while everything downstream still validates, so its severities would
    go nowhere and nothing would say so.
    """
    suffix = TARGET_NAME.get(fault.name)
    if suffix is None:
        raise SystemExit(
            f"fault {fault.name} delivers per main group, but TARGET_NAME does not "
            "say which address in the group that is"
        )
    found: dict[int, str] = {}
    for ga, entry in catalog.by_ga.items():
        if not entry["name"].endswith(suffix):
            continue
        group = main_group(ga)
        if group in found:
            raise SystemExit(
                f"main group {group} has two addresses ending in {suffix}: {found[group]} and {ga}"
            )
        found[group] = ga
    missing = sorted({main_group(ga) for ga in catalog.by_ga} - set(found))
    if missing:
        raise SystemExit(
            f"main groups {missing} carry no address ending in {suffix} — "
            "either it was renamed in ETS or it was never created"
        )
    print(
        f"{fault.name}: {len(found)} rules on main groups {', '.join(map(str, sorted(found)))}"
    )
    return [
        catalog.rule(
            f"anomaly.{fault.name}.{group}",
            ga,
            SEVERITY_PATH,
            seed_on_start=True,
            min_delta=0,
        )
        for group, ga in sorted(found.items())
    ]


def declared_ga(fault: Any, catalog: Catalog) -> str:
    """The one address a fault declares — which has to exist in the catalog,
    or the severity would go nowhere and nothing would say so."""
    if fault.target.ga not in catalog.by_ga:
        raise SystemExit(
            f"fault {fault.name} delivers to {fault.target.ga}, which the catalog does not "
            "know — either it was renumbered in ETS or it was never created"
        )
    return fault.target.ga


def channel_rules(faults_path: Path, catalog: Catalog) -> list[Rule]:
    """The per-main-group faults and the house-wide ones on a bare subject."""
    rules: list[Rule] = []
    for fault in targeted_faults(faults_path):
        if fault.target.per_main_group:
            rules += per_main_group_rules(fault, catalog)
        elif (
            fault.target.ga is not None and fault.name not in SUBJECT_CARRIES_REFERENCE
        ):
            ga = declared_ga(fault, catalog)
            rules.append(
                catalog.rule(
                    f"anomaly.{fault.name}",
                    ga,
                    SEVERITY_PATH,
                    seed_on_start=True,
                    min_delta=0,
                )
            )
            print(f"{fault.name}: 1 rule on {ga}")
    return rules


def severity_rule(fault: Any, catalog: Catalog, entity: str, ga: str) -> Rule:
    """The rule for one entity of a fault: the subject the engine publishes
    on, built with its own slug function."""
    from iot_insights_engine import entity_slug

    dpt = catalog.by_ga[ga]["dpt"]
    if dpt != SEVERITY_DPT:
        raise SystemExit(
            f"fault {fault.name}: {catalog.by_ga[ga]['name']} ({ga}) is DPT {dpt}, "
            f"a severity address is DPT {SEVERITY_DPT}"
        )
    return catalog.rule(
        f"anomaly.{fault.name}.{entity_slug(entity)}",
        ga,
        SEVERITY_PATH,
        seed_on_start=True,
        min_delta=0,
    )


def device_channel(fault: Any, key: str, catalog: Catalog) -> str:
    """The address of the channel a device key names — the engine's own
    match: the key is a fragment of exactly one catalog name in the fault's
    scope. That address is the entity the engine publishes a device on."""
    scope = fault.channel_scope()
    hits = [
        ga
        for ga, entry in catalog.by_ga.items()
        if key in entry["name"]
        and (not scope.dpt or entry["dpt"] in scope.dpt)
        and (
            not scope.name_like or any(like(p, entry["name"]) for p in scope.name_like)
        )
        and not any(like(p, entry["name"]) for p in scope.exclude_name_like)
    ]
    if len(hits) != 1:
        raise SystemExit(
            f"fault {fault.name}: device {key!r} matches {len(hits)} channels in scope"
            + (f": {', '.join(hits)}" if hits else "")
        )
    return hits[0]


def per_entity_rules(fault: Any, catalog: Catalog) -> list[Rule]:
    """One rule per entity of a per-device or per-room fault: the address
    its name template renders to for that entity."""
    target = fault.target
    if target.name is None:
        raise SystemExit(
            f"fault {fault.name} delivers {target.form.replace('_', ' ')}, "
            "but declares no target.name template"
        )
    if target.per_room:
        keys = [room.match for room in fault.rooms]
    else:
        keys = [limit.match for limit in fault.devices] or [
            ref.match for ref in fault.references
        ]
    if not keys:
        raise SystemExit(
            f"fault {fault.name} delivers {target.form.replace('_', ' ')}, but names no entity"
        )

    rules: list[Rule] = []
    for key in keys:
        name = target.name.replace("{entity}", key)
        if name not in catalog.by_name:
            raise SystemExit(
                f"fault {fault.name}: {name!r} (entity {key!r}) is not in the catalog — "
                "either it was renamed in ETS or it was never created"
            )
        entity = device_channel(fault, key, catalog) if target.per_device else key
        rules.append(severity_rule(fault, catalog, entity, catalog.by_name[name]))
    print(
        f"{fault.name}: {len(rules)} rules, one per {target.form.removeprefix('per_')}"
    )
    return rules


def insights_rules(faults_path: Path, catalog: Catalog) -> list[Rule]:
    """The faults whose subject carries an entity."""
    rules: list[Rule] = []
    for fault in targeted_faults(faults_path):
        if fault.target.per_device or fault.target.per_room:
            rules += per_entity_rules(fault, catalog)
        elif fault.name in SUBJECT_CARRIES_REFERENCE:
            if len(fault.references) != 1:
                raise SystemExit(
                    f"fault {fault.name} carries its reference in the subject, "
                    f"so it needs exactly one — it names {len(fault.references)}"
                )
            ga = declared_ga(fault, catalog)
            rules.append(severity_rule(fault, catalog, fault.references[0].match, ga))
            print(f"{fault.name}: 1 rule on {ga}")
    return rules


# --- output ----------------------------------------------------------------

ENGINE_HEADERS = {
    "insights": (
        "Fault severities → KNX (iot-insights-engine) for the faults whose subject "
        "carries an entity: one rule per device or room, on the address the fault's "
        "name template renders to, plus the faults publishing on their reference's label."
    ),
    "channels": (
        "Fault severities → KNX (iot-insights-engine) for the two channel-scoped "
        "faults, one severity per main group on its own Zentral Diagnose address — "
        "silence on x/0/250, constancy on x/0/252 — and for the faults delivering "
        "to one declared house-wide address."
    ),
}


def header(source: str) -> list[str]:
    text = SIDECARS[source].header if source in SIDECARS else ENGINE_HEADERS[source]
    return [
        GENERATED_BY,
        *(f"# {line}" for line in textwrap.wrap(text, 76)),
        "",
        "mappings:",
    ]


def write(source: str, rules: list[Rule], out_dir: Path) -> None:
    ordered = sorted(rules, key=lambda r: (natural_key(r.subject), ga_key(r.ga)))
    body = [line for rule in ordered for line in rule.lines()]
    out = out_dir / f"{source}.yaml"
    out.write_text("\n".join(header(source) + body) + "\n", encoding="utf-8")
    print(f"{out.name}: {len(ordered)} rules")


def main() -> int:
    if len(sys.argv) != 5:
        print(__doc__, file=sys.stderr)
        return 2
    source, catalog_path, out_dir, input_path = sys.argv[1:5]
    catalog = Catalog(Path(catalog_path))
    if source in SIDECARS:
        rules = sidecar_rules(source, SIDECARS[source], catalog, Path(input_path))
    elif source == "channels":
        rules = channel_rules(Path(input_path), catalog)
    elif source == "insights":
        rules = insights_rules(Path(input_path), catalog)
    else:
        raise SystemExit(
            f"unknown source {source!r}: one of {', '.join([*SIDECARS, 'channels', 'insights'])}"
        )
    write(source, rules, Path(out_dir))
    return 0


if __name__ == "__main__":
    sys.exit(main())
