apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: forecast-solar-credentials
  namespace: iot-mcp-bridge

spec:
  encryptedData:
    api-key: AgCXxOMPLhWPtla5e5CYY3nVnP0CbgLgld41/CVkxfsX0kZyGWmGXXSWvxj2pdhKn74QYTkoM6w6e6pCPuokhA5FUYwUapR0j5fQGdpfLybyeUfEjxUbXq6H4+bcH9fV97CWL2T6vgPaXgaC8XPAaCPRtkBCyolkPVRFRAxOchio6aNP+21odoT1qmK9ELUdL8+yjSirfFmLKGzCy6MR0m74uYzwAEYlIZB7H/kx46+mxJNa4FsHBHW2tmLuuALaiiKW22D7qmgelqEaA3DQiZpeNVhnxBkyVxRmTDErt+VnFEhdMMifj1J99pp3uPTrS6JfADXt9OETO0+twU5uEzSc6Ow48ruoDlfte17bAGtcwTwiyaWaFBycEgkpQUHC5mht1sy3xJoAibpSMbzhDHgMSkx2ICXwKPPB5AQImsMwALTtE1pDE0LK62OuWGQeFac/jvoHlI5A11GLfFNpmPROSNeAVn5y6PR8mTEHoHe6rHGM/zsX8YaPGqwaM3CWMLcMuhKd+Pyi6ZlKGOt+QVtTcVgzjUT3XzSnzM/qwp9tQtIAjnwU7ARmU8ocZZ8SjKWzU4IAio2zdlbhgjHyI41DmB2K5Ei4ZPCiqHAof8mkRUsjyUwNifvrser0aLN2hroPFe803bo9vANDn7SL02hBIMOoAlX7fdMHoeYALvXmPoqWhFcr7QBG0gOZdrEWxM9rTrD+m0m46fLIHqnaycs+
  template:
    metadata:
      name: forecast-solar-credentials
      namespace: iot-mcp-bridge
    type: Opaque
