apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: iot-mcp-bridge-wikijs-token
  namespace: iot-mcp-bridge

spec:
  encryptedData:
    token: AgAp98CptOPoNJw2CV/ePqiwyZ1PnrFO7YxAhGsDpG/jn8nITN4SjlPvhQfNLsYDs0ihJLxYUupGUr+CgLV0QX9VpdY7gzJgT3vCnoKGgJrt4tcuSXOUEm9tDEUP5MjfHV+HNAErW8QYIHPFpRdXgJ4jK/sn0285ulgxqAeWCnID2DS90+zc7fQ8Gs8SOd33H8oogSFepQT4yG1f989yhIDDAHqVHx2vGFRAYFFZVKo75pcGwpPS/QOZa36PPRuDyr+BjWwpci8YDTaNi2HPdAsMIEddv4vJcyjgNayTe8bGtkg45s33i1BPKCd8Ah9RzLaeRdz4U5kXy8/XCSBe1Z7Ld+QsjN9HczxD7x8BRWB5azZwN3e8KY6oqP2TFif89sUr/n5arMKlbAuTzREPfwCSGVwCZvXz1Coptqt2e09aoYb9PlBDku50+6U1y7285xEfMYSTUIl79jsNVT0ZbT9SxnDJClSkq38K48V9445JPfC72sjhuqLEAvvrr6yC2+aaQzA4z64xHqeDE8QbrM2pAW9rqjafvUx+Xr6iGInoaNbqQfVDwnXlLYCUUXFLOOqD2KMxO7+2Y3A1xnMzzcJu8Uelf36I041w2A5Av2g0QnlK0RRDg7YCkyOEUPhp9sTmxkmTlAnl2f0onD69IVCffScUzTl1Jl8dCxbvgcgXAzLuAhXkdNu7omlRrn6anyazxmscJUoAuHEHvA7az9lgMqNQTGRNY30qDPikA3uiXHJKAjbihvwvLOrLXBe3niv6zuiUoVACg8k7C1ShXG2d5bfsLM7eLJp1y62FTBHz9ZDhAf18dpOx2TnRb8abPXcdac0ltkTHa5lcDdLkUxkkJ+wp3n39GcPEQQ6A+veFCdCs4FN2rI+/Uzm7vqa8nHCoD+5PVNBf29kRXDvci48QDOp+N/e51ibgyZF+3eIkqwtLh3Xgm1tHncYHVaYv4j/jPZe43uHd6+76/yTUlpSGNuLsueXlB32xb7Fnim6VcxdA5K0uC6gEIYsKThPq2+Nshb81Oexos52wgjV3BkzVrfrH/g91GGHfKgvFJZV2O1Gn5OR4HQ6qxIA8d3KGktOSzHWXsIY7cqumIbvCSxDZbC+MpKjV2BCB2HZKaz756P7mH21ZNhNilCGxUU9Lj1mpgDtdgrO0Rg5bzmpWPTdNfTbHI2LuTmSE2ZwHy9i96TJgTf4pXi2opBlBGQxaw7PyccCExicG+C2is+z7LwQ6laE4Go7ZxiXi76LB002jgRveM13NrFs/E+mC2hHiVokiaA7P5WOVzIrfTNdOg9WiSPBD4qvKud4pOaMeCS7XbliikpRlFXpoQu0WQiEPo4KY6moSYlHzHVEjQhbi0C0IB8Ex0Ipi
  template:
    metadata:
      name: iot-mcp-bridge-wikijs-token
      namespace: iot-mcp-bridge
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: iot-mcp-bridge-auth-clients
  namespace: iot-mcp-bridge

spec:
  encryptedData:
    clients.json: AgBqv52EYWxRlp6KCKCM5gXkHMgEKVIM/cRrMg7xaJJml2JgF7QUEKVWc7LT+fcEbTgdBES5AHN6VODuzltDmo0Ii0q49TtPleVexHnQD6j3g/JkGzc9un/U8oCMfS8IUx/LS3g3AVFzEoqCKD1+Vn9PuRQBGT+sKjUh5m6wqXvFglNzrt84TDDcQyaSficun3LWCiGKEDa3T0RMVsgAhkrKCyhCp7r5E1u/YEm+eMEkQhVrJnVFaGfP91iZRZE/kJdOqrYYInqBRDZj77el0PhZuh6Jl4J43K6B/7JXUpj0e7zm/QzrdDrTYYWvDtWKToqnHdDAgysIf1HCaaHJR0Bc+/iziWyWl+d7592g8Tj2pSAnsmmumcbo8b7mf+cYwH6TbYovIsZWDOlD0gVZXArduN78+Ndg/DbRRpkQjiwrnK0fWfMybiruIV3bCFIofLF8zQV9SrgaeLOTHRbA9acjZa4h3M4e3bSLbOSrPFOKGHv/KK3aKZFO23eJM6bfGNgFVIyAc+SwlpEVN1L1jGfUQ/Yz99/2ax6LgDxkYikdvLg8otceLsBiYgPErsQyalI+PZsaLKZNnGecQsl/6XqkSWvIn+7ISA/FFzNtFhhWMfjWqeSdBuA19OgPOWoe9PRwcggm6KnR/CtIe6qFjebfzrUEdE4GqRYiTK78dyq/h2Vri/FXsLcNuLK0fZzsR8QG84Y+zLxYuoRXyMX0195kQs0fr9mJr/fLbIdHtmEMdd61YuyLxDPMh6m4Cw1+9v921cNMjHWjvnviPgr5T8NDeMpB1CdEFTrk/tBA642/7mh4pg==
  template:
    metadata:
      name: iot-mcp-bridge-auth-clients
      namespace: iot-mcp-bridge
    type: Opaque
