apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replacements:
  # Inject domain name into Certificate, IngressRoute, and Homepage href
  - sourceValue: node-red.zimmermann.phd
    targets:
      - select:
          kind: Certificate
          name: node-red-tls-cert
        fieldPaths:
          - spec.dnsNames.0
      - select:
          kind: IngressRoute
          name: node-red
        fieldPaths:
          - spec.routes.0.match
        options:
          delimiter: "`"
          index: 1
      - select:
          kind: IngressRoute
          name: node-red
        fieldPaths:
          - metadata.annotations.[gethomepage.dev/href]
        options:
          delimiter: "//"
          index: 1

  # Inject Authentik base URL for OIDC
  - sourceValue: https://auth.zimmermann.phd
    targets:
      - select:
          kind: Deployment
          name: node-red
        fieldPaths:
          - spec.template.spec.containers.0.env.[name=AUTHENTIK_HOST].value

  # Inject Node-RED OIDC callback URL
  - sourceValue: https://node-red.zimmermann.phd/auth/strategy/callback/
    targets:
      - select:
          kind: Deployment
          name: node-red
        fieldPaths:
          - spec.template.spec.containers.0.env.[name=NODE_RED_CALLBACK_URL].value

  # Inject storage size
  - sourceValue: 128Mi
    targets:
      - select:
          kind: PersistentVolumeClaim
          name: node-red-data
        fieldPaths:
          - spec.resources.requests.storage

  # Rewrite external-dns target annotation to dev UDM Pro
  - sourceValue: udm-pro.zimmermann.phd
    targets:
      - select:
          kind: IngressRoute
        fieldPaths:
          - metadata.annotations.[external-dns.alpha.kubernetes.io/target]
