image:
  ## Linux VM images
  vm_debian_trixie:
    image_type: import
    image_url: https://cloud.debian.org/images/cloud/trixie/20260327-2429/debian-13-genericcloud-amd64-20260327-2429.qcow2
    image_filename: debian-13-genericcloud-amd64.qcow2
    image_checksum: 09559ec27d263997827dd8cddf76e97ea8e0f1803380aa501ea7eaa4b4968cd76ffef4ec7eb07ef1a9ccbeb0925a5020492ea9ed53eb167d62f3a2285039912c
    image_checksum_algorithm: sha512

  vm_ubuntu_noble:
    image_type: import
    image_url: https://cloud-images.ubuntu.com/noble/20260911/noble-server-cloudimg-amd64.img
    image_filename: ubuntu-noble-server-cloudimg-amd64.qcow2
    image_checksum: 612b2c0cc1bc413a6cb8c38fd611794caf0f2b436c50013d8b3794db12ad7354

  ## Ubuntu LXC images
  lxc_ubuntu_noble:
    image_type: vztmpl
    image_url: https://images.linuxcontainers.org/images/ubuntu/noble/amd64/cloud/20260330_07:42/rootfs.tar.xz
    image_filename: ubuntu-noble-cloud-amd64-202603300742.tar.xz
    image_checksum: 97f1e355e5df25725b3557697d4d61adb0e5671aee1b2470abc75d1db821c5e4

  lxc_ubuntu_plucky:
    image_type: vztmpl
    image_url: https://images.linuxcontainers.org/images/ubuntu/plucky/amd64/cloud/20260330_07:42/rootfs.tar.xz
    image_filename: ubuntu-plucky-cloud-amd64-202603300742.tar.xz
    image_checksum: 2a87c930c22b56445a9c0283fda9c6a2617d1ef97a911d4fc0091c7d688abae8

  ## Windows images
  vm_windows_11_25h2:
    image_type: iso
    image_url: ""
    image_filename: windows-11-25H2-amd64.iso
    image_checksum: ""

  vm_windows_virtio_0_1_285:
    image_type: iso
    image_url: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win-0.1.285.iso
    image_filename: windows-virtio-0.1.285.iso
    image_checksum: e14cf2b94492c3e925f0070ba7fdfedeb2048c91eea9c5a5afb30232a3976331
