apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replacements:
  # Inject domain name into Certificate and IngressRoute
  - sourceValue: kromgo.zimmermann.sh
    targets:
      - select:
          kind: Certificate
          name: kromgo-tls
        fieldPaths:
          - spec.dnsNames.0
      - select:
          kind: IngressRoute
          name: kromgo
        fieldPaths:
          - spec.routes.0.match
        options:
          delimiter: "`"
          index: 1

  # Rewrite external-dns target annotation to prod UDM Pro
  - sourceValue: udm-pro.zimmermann.sh
    targets:
      - select:
          kind: IngressRoute
        fieldPaths:
          - metadata.annotations.[external-dns.alpha.kubernetes.io/target]

patches:
  # kromgo service with static IP and BGP advertisement
  - target:
      kind: Service
      name: kromgo
    patch: |-
      - op: test
        path: /spec/type
        value: LoadBalancer
      - op: add
        path: /metadata/annotations/io.cilium~1lb-ipam-ips
        value: "192.168.10.36"
