apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: holmesgpt-llm
  namespace: holmesgpt

spec:
  encryptedData:
    api-key: AgBpykbq9U5IqEpZMLeuYQBBQaNgNLXJzahHFMVmpFTsFcMHM0AxnX483y7+hQ9MX72qQ7vT7jeamYllLQrYk5Z7ZB7zuAYYmyS/4yiVqMYscxreoriP09KWYYQJjEPVMRLFv10rkhea/i2Bk6PqBnExfXUgu5prKeGEWqMk8BJkeH2LF6Qjl6Oigj3kxgWm3ZfOnEnFtr05ZIHE5GL0XwgaJNJY5YP095flKKKwjBX3/mnKJkEFJNpYIaElnV7rCu9uTW9mcyinUegrBoGrJi1nezJK9sy07W1a7rilXySp8GrkNo4mb81H+zSipP3OJ8ZK8HYlFQYsI/3JEmpLVxfEWFpcG/vBJz9Ifj8pLaUmojknIww539BLBHRcZkzT2m99/cskeyoRGneVhaVJm1T5yK1mQKvXSkyRTYLn+xN0Oy6kxKeWYuep2XhxHgIplzxcR4TUmIgMzuMRZ36hAmAZ/DCxPzTNoWGypPSszfLtnoaiJTbihGI1RZ5lwPg+NYD/6ElIhlloUub9ahynVs9xVWsJP+RjVz3Sdu/LR/q2GEEHtW5Xtz62FbXUCZ5aTd9Ti0yF39A8xxDU+rQhrgChJT9rFWzOLIT6gwCUtY8wJtqbucvgdJFI8lePo7eQSNTyRIBRKZxsSBrL+0Gr3SZLLDuJA9Yvx0PieCXttgpRR9XjnQnPKhz0RYnW7S9+Oj7a8+JxiGj6muw43w6oXMQhwpCVAS4O6dKo
  template:
    metadata:
      name: holmesgpt-llm
      namespace: holmesgpt
    type: Opaque
