apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: holmesgpt-llm
  namespace: holmesgpt

spec:
  encryptedData:
    api-key: AgCH0+gwPQKnaMjDcshGbn2VqmeQigYg/esUz+UOtva0iufJ3T6LAShY4njj2M0j23I6P0Tphe9FVhJQ6NjYGSHfwTtB4SA/ptzDhHklBr40qP5/2LuezNB+EBVrKEULdis4CgzDvIyx6o19WwjVGUCL4iok9PGDoITjc6ABNsu7nnV6TOLn7cwxZHdXQXZyt/bsYkDwfh1CJVs8/62x6cU/dhSRk/KpT+y/NU6r75mGjOFAGgNXxBLgfY5U8tzQzQl/EP03pZjmM/RpTaw2kpGk/qDspX6FyPboOCoo1cpx14dQOCtw+38vRYGreZDh5r1F5BcKkdplyGXQX2Xauyvq11iWZ9wF96UCX+4IuEQZWJDsIHfvq/fR1eyDg0DryOTihqHOshFAB5/lC/qcGOFnGzdQ6mTjXXU+U2cmtI/XK27drN3OGu19E02ee3IM4fpiNeWE8NCS3yBcjD0BwegGuaJxySLyEhN8nPxyF7o2t+FLdgNP6Y3/jpEIAegIGcOgGRITv5TQgoBxi57HXuQM49IZq6GNpuztNqpsa5XhR0jUK0x1Nbavdv7y93ITAQD+fXVL2av+kvEtyOQPT+FGtm/vUBk9Z+UZEqsEfqMIE8tlLv6Fp4TkadIzpKNDIpcFNFcHQGmcHslZmiky11gKJfJx+wj/N8JHOGzMWcQrCsaB06n1hxfPFceiw7uZ0GNcPPtbFzitwEd8LcBZzx26+3LLwrp0uoz5
  template:
    metadata:
      name: holmesgpt-llm
      namespace: holmesgpt
    type: Opaque
