apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: holmesgpt-llm
  namespace: holmesgpt

spec:
  encryptedData:
    anthropic-api-key: AgBrzOnvyft4JEz2yqByz8J5VMC7n0g/S7eHJuiOuDekpcNYlarMtaZWqquz2Xa9j4d1mVHMTHDWJ3nid7atEciYStwOe0D5x1djEDVFgu3dAUUEf7N3Anm9qvdHRp1M8glE9OMhThmFaWkMQgV3aJ9EFhZ1Y++zegJ9/iGdsoZ/AGNBH2T4rd/ZlC/YwjwN+BoirzyzOn1yqGv8w3nwQPjgBfOSY/IEku5QxXIQSsW8yBauRPfl3B65Ze5K6uXVMWHW0THJ9DnMcMVPBOi/iLYpoGpxXB3waWo+0wCIGzvLgaszuJcZ/lqK1g1efuY/WQ0YYsxgcj9XYM5zOvylxfaxhT0fd2P2O0eJ08dd8gf7ZlN39JXF5I6Mg/qNtD8xfd3fUCBl0gUUNK8vv67xw+pT8Nt9KfXFshw/OMcyuPVwe9u036qWfybfBovd4cCHUjG5WiXBlY4j7nDQMSJrC6e5qT7AukvAuNxgJSXFFJ+bCpsmYlmVh9XAAk7NfFqppRi9TJdVO+DqoPuZAzj/+xTlCn0j7EFrxF+WkY8rcjNf1SGMl24h1yN6gUu+blIwtcdwLJm/Z9Hi+WdDXMtzFWL8BucCnrISUpoeX0nAcSwnvTXAvTSOg0jVjrDuX/eUd0+legsvg34qdtzBGFWUFHgdicupvrCTVHu5MDJekJQZpQjAt84yPMSaRXttKoYjEEgnwamYPgsUlRaKIXsRPNwdF2UqOAXZrML93R3Qs4cUrwJpltSF59aWksxHf813gP3/w48tr5wkTTGY4O9W5UPQyJWVOJYEnfe7KOkIKqtFnC73QXdiDGKu8FKuwLELQZgP2fnFmSvwtbJW
  template:
    metadata:
      name: holmesgpt-llm
      namespace: holmesgpt
    type: Opaque
